// Code generated by alef — DO NOT EDIT.
// alef:hash:cf1ad37e57d3434a5abf52f65b51d56ad2c68279fb96614807d4ee8b1f312950
package xberg

// RequireNativeSetup_1_3_0 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_3_0 = "1.3.0"
