// Code generated by alef — DO NOT EDIT.
// alef:hash:2fa26e59341e3697e080d58958ffbfe6cb1b1ed2f9b3a1a02dab9c05a47eca34
package xberg

// RequireNativeSetup_1_2_1 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_2_2 = "1.2.2"
