// Code generated by alef — DO NOT EDIT.
// alef:hash:7cd91abce82fbbcf7dde1914e8b20b16827643118b40a22c940ea4da4e8b426e
package xberg

// RequireNativeSetup_1_2_6 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_2_6 = "1.2.6"
