// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c1b3979948b46a11476b15f67d7acb00bf71dd7fe07bb31c515fb55f27f9a5a0
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 60000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
		setupFiles: ["./setup.ts"],
	},
});
