# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:89a6e98c053bb7c4306fd6703da930a1f556474abe64915f11f2de628ef73be3
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: post_processor_management
defmodule E2e.PostProcessorManagementTest do
  use ExUnit.Case, async: false

  describe "post_processors_clear" do
    test "post_processors_clear" do
      result = Xberg.clear_post_processors()
      assert result == :ok
    end
  end

  describe "post_processors_list" do
    test "post_processors_list" do
      result = Xberg.list_post_processors()
      refute result in [nil, :error]
    end
  end
end
