# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56f8f559a4b18c628d6717b8d0d47da70a612e3bfe9ef38e31233b9321c05825
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: registry
defmodule E2e.RegistryTest do
  use ExUnit.Case, async: false

  describe "list_embedding_backends" do
    test "list_embedding_backends" do
      result = Xberg.list_embedding_backends()
      refute result in [nil, :error]
    end
  end

  describe "list_ocr_backends" do
    test "list_ocr_backends" do
      result = Xberg.list_ocr_backends()
      refute result in [nil, :error]
    end
  end

  describe "list_post_processors" do
    test "list_post_processors" do
      result = Xberg.list_post_processors()
      refute result in [nil, :error]
    end
  end

  describe "list_renderers" do
    test "list_renderers" do
      result = Xberg.list_renderers()
      refute result in [nil, :error]
    end
  end

  describe "list_validators" do
    test "list_validators" do
      result = Xberg.list_validators()
      refute result in [nil, :error]
    end
  end
end
