# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4d31d6122016ad621e290274433a20be8f128a28743c76645c9e22de8c3cf2dc
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: reranker_backend_management
defmodule E2e.RerankerBackendManagementTest do
  use ExUnit.Case, async: false

  describe "clear_reranker_backends" do
    test "clear_reranker_backends" do
      result = Xberg.clear_reranker_backends()
      assert result == :ok
    end
  end

  describe "list_reranker_backends" do
    test "list_reranker_backends" do
      result = Xberg.list_reranker_backends()
      refute result in [nil, :error]
    end
  end
end
