# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:883793ae45f51047021c3783bf1ce4b709affff596a30f72bd965f94c60ddb70
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: validator_management
defmodule E2e.ValidatorManagementTest do
  use ExUnit.Case, async: false

  describe "validators_clear" do
    test "validators_clear" do
      result = Xberg.clear_validators()
      assert result == :ok
    end
  end

  describe "validators_list" do
    test "validators_list" do
      result = Xberg.list_validators()
      refute result in [nil, :error]
    end
  end
end
