// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c50011e5997f310c3d59cabdb4ee45ae2ebc52d859a9a617d9320d9d30a5a5f5
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;
import org.junit.jupiter.api.BeforeAll;

/** E2e tests for category: ocr_backend_management. */
public class OcrBackendManagementTest {

    @BeforeAll
    static void initEnv() {
        if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
            System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true");
        }
        if (System.getProperty("RUST_MIN_STACK") == null) {
            System.setProperty("RUST_MIN_STACK", "16777216");
        }
    }


    @Test
    void testOcrBackendCapabilitiesList() throws Exception {
        // List all registered OCR backends with their declared language capabilities
        var result = Xberg.listOcrBackendCapabilities();
        assertNotNull(result, "expected non-null response");


    }


    @Test
    void testOcrBackendSupportsLanguageUnknownBackend() throws Exception {
        // Checking language support on an unregistered OCR backend is an error
        // Wrap setup_lines + call_expr inside the lambda so error fixtures
        // catch failures at *any* step — including `<Type>.fromJson(...)`
        // calls that throw on malformed JSON (e.g. error fixtures with an
        // invalid enum value like `"purpose":"invalid-purpose"`). Mirrors
        // the C# `Assert.ThrowsAnyAsync(() => client.X(Type.FromJson(...)))`
        // pattern.
        assertThrows(Exception.class, () -> {
            Xberg.ocrBackendSupportsLanguage("nonexistent-backend-xyz", "eng");
        });

    }


    @Test
    void testOcrBackendsClear() throws Exception {
        // Clear all OCR backends and verify list is empty
        assertDoesNotThrow(() -> Xberg.clearOcrBackends());


    }


    @Test
    void testOcrBackendsList() throws Exception {
        // List all registered OCR backends
        var result = Xberg.listOcrBackends();
        assertNotNull(result, "expected non-null response");


    }


    @Test
    void testOcrBackendsUnregister() throws Exception {
        // Unregister nonexistent OCR backend gracefully
        assertDoesNotThrow(() -> Xberg.unregisterOcrBackend("nonexistent-backend-xyz"));


    }

}
