// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1884b966a9fb476f913e823c09a0825adf5f45e05f3fd1e942110e3fc46f8bb9
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;
import org.junit.jupiter.api.BeforeAll;

/** E2e tests for category: post_processor_management. */
public class PostProcessorManagementTest {

    @BeforeAll
    static void initEnv() {
        if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
            System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true");
        }
        if (System.getProperty("RUST_MIN_STACK") == null) {
            System.setProperty("RUST_MIN_STACK", "16777216");
        }
    }


    @Test
    void testPostProcessorsClear() throws Exception {
        // Clear all post-processors and verify list is empty
        assertDoesNotThrow(() -> Xberg.clearPostProcessors());


    }


    @Test
    void testPostProcessorsList() throws Exception {
        // List all registered post-processors
        var result = Xberg.listPostProcessors();
        assertNotNull(result, "expected non-null response");


    }

}
