// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d3487b65e72155d3a00e2271438b6adf6e0fd3344df161235f99e2a4fd19bb8b
// To regenerate: alef generate
// To verify freshness: alef verify
//! E2e tests for category: registry

use xberg::{list_embedding_backends, list_ocr_backends, list_post_processors, list_renderers, list_validators};

#[test]
fn test_list_embedding_backends() {
    // List embedding backends
    let _ = list_embedding_backends().expect("call failed");
}

#[test]
fn test_list_ocr_backends() {
    // List OCR backends
    let _ = list_ocr_backends().expect("call failed");
}

#[test]
fn test_list_post_processors() {
    // List post-processors
    let _ = list_post_processors().expect("call failed");
}

#[test]
fn test_list_renderers() {
    // List renderers
    let _ = list_renderers().expect("call failed");
}

#[test]
fn test_list_validators() {
    // List validators
    let _ = list_validators().expect("call failed");
}
