# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a1c4d9998c7ff7e3b305550bca3038f8d357482ee28b477cdc28ac2e1906a8b8
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.BrowserConfig do
  @moduledoc "Browser fallback configuration."

  @typedoc "Browser fallback configuration."
  @type t :: %__MODULE__{
          mode: Xberg.BrowserMode.t(),
          backend: Xberg.BrowserBackend.t(),
          endpoint: String.t() | nil,
          timeout: non_neg_integer(),
          overall_timeout: non_neg_integer(),
          shutdown_timeout: non_neg_integer(),
          wait: Xberg.BrowserWait.t(),
          wait_selector: String.t() | nil,
          extra_wait: non_neg_integer() | nil,
          proxy: Xberg.ProxyConfig.t() | nil,
          block_url_patterns: [String.t()],
          eval_script: String.t() | nil,
          robots_user_agent: String.t() | nil,
          capture_network_events: boolean(),
          session_affinity: boolean()
        }

  defstruct mode: :auto,
            backend: :chromiumoxide,
            endpoint: nil,
            timeout: 30_000,
            overall_timeout: 60_000,
            shutdown_timeout: 5_000,
            wait: :network_idle,
            wait_selector: nil,
            extra_wait: nil,
            proxy: nil,
            block_url_patterns: [],
            eval_script: nil,
            robots_user_agent: nil,
            capture_network_events: false,
            session_affinity: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
