# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cf9b1a619c8afd76769d2b319d1234c243c462d5e3e21419bd89fa5d954347c9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ContentConfig do
  @moduledoc """
  Content extraction and conversion configuration.

  Controls how HTML is converted to the output format. Uses
  html-to-markdown-rs as the conversion engine for all formats
  (markdown, plain text, djot).
  """

  @typedoc "Content extraction and conversion configuration."
  @type t :: %__MODULE__{
          output_format: String.t() | nil,
          preprocessing_preset: String.t() | nil,
          remove_navigation: boolean(),
          remove_forms: boolean(),
          strip_tags: [String.t()],
          preserve_tags: [String.t()],
          exclude_selectors: [String.t()],
          skip_images: boolean(),
          max_depth: non_neg_integer() | nil,
          wrap: boolean(),
          wrap_width: non_neg_integer(),
          include_document_structure: boolean(),
          extract_metadata: boolean()
        }

  defstruct output_format: "markdown",
            preprocessing_preset: "standard",
            remove_navigation: true,
            remove_forms: true,
            strip_tags: [],
            preserve_tags: [],
            exclude_selectors: ["noscript"],
            skip_images: false,
            max_depth: nil,
            wrap: false,
            wrap_width: 80,
            include_document_structure: true,
            extract_metadata: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
