# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:edb6ff41d9470826fc18f324d2e6ce72d6d01c56e1c459c98d0eae30f8fad113
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.CredentialProviderConfig do
  @moduledoc """
  Managed credential-provider configuration for OAuth2/STS-based authentication modes liter-llm
  cannot express via a static `api_key`. See [`LlmConfig::credential_provider`].

  `Debug` is implemented by hand: [`CredentialProviderConfig::AzureAd`]'s `client_secret` is a
  credential and must never be printed, matching [`LlmConfig`]'s own redaction policy. The
  other variants carry no secret material — [`CredentialProviderConfig::VertexOauth2`] and
  [`CredentialProviderConfig::BedrockWebIdentity`] reference a *file path*, never the key or
  token itself.
  """

  @typedoc "Managed credential-provider configuration for OAuth2/STS-based authentication modes liter-llm cannot express via a static `api_key`. See [`LlmConfig::credential_provider`]."
  @type t :: term()

  @typedoc "Azure AD OAuth2 client-credentials flow (Azure OpenAI / Azure Cognitive Services)."
  @type azure_ad :: %{type: :azure_ad, tenant_id: String.t(), client_id: String.t(), client_secret: String.t(), scope: String.t()}
  @typedoc "Google Vertex AI OAuth2 via a service-account JSON key file on disk."
  @type vertex_oauth2 :: %{type: :vertex_oauth2, service_account_key_file: String.t(), scope: String.t()}
  @typedoc "Google Vertex AI Application Default Credentials, resolved from the GCE/GKE/Cloud Run metadata server. Carries no secret material at all."
  @type vertex_adc :: %{type: :vertex_adc, scope: String.t()}
  @typedoc "AWS STS `AssumeRoleWithWebIdentity` (EKS IRSA / OIDC federation) for Bedrock."
  @type bedrock_web_identity :: %{
          type: :bedrock_web_identity,
          role_arn: String.t(),
          token_file: String.t(),
          session_name: String.t(),
          region: String.t()
        }

  def azure_ad(tenant_id, client_id, client_secret, scope),
    do: {:azure_ad, %{tenant_id: tenant_id, client_id: client_id, client_secret: client_secret, scope: scope}}

  def vertex_oauth2(service_account_key_file, scope),
    do: {:vertex_oauth2, %{service_account_key_file: service_account_key_file, scope: scope}}

  def vertex_adc(scope), do: {:vertex_adc, %{scope: scope}}

  def bedrock_web_identity(role_arn, token_file, session_name, region),
    do: {:bedrock_web_identity, %{role_arn: role_arn, token_file: token_file, session_name: session_name, region: region}}

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:azure_ad), do: "azure_ad"
  def wire_value(:vertex_oauth2), do: "vertex_oauth2"
  def wire_value(:vertex_adc), do: "vertex_adc"
  def wire_value(:bedrock_web_identity), do: "bedrock_web_identity"
  def wire_value(value) when is_tuple(value), do: wire_value(elem(value, 0))
end
