# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cd5686bb095802576e8fef0459def76b905c5ca4257492e8b5f1a37ffcf35711
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DeepseekOcrBackendOptions do
  @moduledoc "Runtime options accepted by the `candle-deepseek-ocr` backend."

  @typedoc "Runtime options accepted by the `candle-deepseek-ocr` backend."
  @type t :: %__MODULE__{
          model_path: String.t() | nil,
          model_id: String.t() | nil,
          hf_revision: String.t() | nil,
          cache_dir: String.t() | nil,
          device: Xberg.CandleDevicePreference.t() | nil,
          version: non_neg_integer() | nil,
          dtype: Xberg.CandleDeepseekOcrDtype.t() | nil
        }

  defstruct model_path: nil,
            model_id: nil,
            hf_revision: nil,
            cache_dir: nil,
            device: nil,
            version: nil,
            dtype: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
