# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:adfad9ecba354d74aed9327ba4ac0c47cf9ed134663e57800098b7f326602dc3
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.GridCell do
  @moduledoc "Individual grid cell with position and span metadata."

  @typedoc "Individual grid cell with position and span metadata."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          row: non_neg_integer(),
          col: non_neg_integer(),
          row_span: non_neg_integer(),
          col_span: non_neg_integer(),
          is_header: boolean(),
          bbox: Xberg.BoundingBox.t() | nil,
          heading_level: non_neg_integer() | nil,
          style_name: String.t() | nil
        }

  defstruct content: nil,
            row: 0,
            col: 0,
            row_span: 1,
            col_span: 1,
            is_header: false,
            bbox: nil,
            heading_level: nil,
            style_name: nil
end
