# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:945e3243e4aaa6db260a031cbb035f4199b282b0ff39ee88ec7af798dd393abc
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.HtmlTheme do
  @moduledoc "Built-in HTML theme selection."

  @typedoc "Built-in HTML theme selection."
  @type t :: :default | :git_hub | :dark | :light | :unstyled

  @default :default
  @git_hub :git_hub
  @dark :dark
  @light :light
  @unstyled :unstyled

  @doc "Sensible defaults: system font stack, neutral colours, readable line measure. CSS custom properties (`--kb-*`) are all defined so user CSS can override individual values."
  @spec default() :: t()
  def default, do: @default
  @doc "GitHub Markdown-inspired palette and spacing."
  @spec git_hub() :: t()
  def git_hub, do: @git_hub
  @doc "Dark background, light text."
  @spec dark() :: t()
  def dark, do: @dark
  @doc "Minimal light theme with generous whitespace."
  @spec light() :: t()
  def light, do: @light

  @doc "No built-in stylesheet emitted. CSS custom properties are still defined on `:root` so user stylesheets can reference `var(--kb-*)` tokens."
  @spec unstyled() :: t()
  def unstyled, do: @unstyled

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:default), do: "default"
  def wire_value(:git_hub), do: "github"
  def wire_value(:dark), do: "dark"
  def wire_value(:light), do: "light"
  def wire_value(:unstyled), do: "unstyled"
end
