# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.LateInteractionModelType do
  @moduledoc "Late-interaction model types supported by Xberg."

  @typedoc "Late-interaction model types supported by Xberg."
  @type t :: term()

  @typedoc "Use a preset ColBERT model (recommended)."
  @type preset :: %{type: :preset, name: String.t()}
  @typedoc "Use a custom ColBERT ONNX model from HuggingFace."
  @type custom :: %{type: :custom, model_id: String.t(), model_file: String.t(), additional_files: [String.t()], max_length: integer()}
  @typedoc "In-process late-interaction backend registered via the plugin system."
  @type plugin :: %{type: :plugin, name: String.t()}

  def preset(name), do: {:preset, %{name: name}}

  def custom(model_id, model_file, additional_files, max_length),
    do: {:custom, %{model_id: model_id, model_file: model_file, additional_files: additional_files, max_length: max_length}}

  def plugin(name), do: {:plugin, %{name: name}}

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:preset), do: "preset"
  def wire_value(:custom), do: "custom"
  def wire_value(:plugin), do: "plugin"
  def wire_value(value) when is_tuple(value), do: wire_value(elem(value, 0))
end
