# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1c4bb1c6b786955e961fea109ca9a5fd863d15efb9c5ce7fb782997aebfc2542
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.LateInteractionConfig do
  @moduledoc """
  Configuration for the late-interaction (ColBERT) pipeline.

  Controls which model to use, batching, and download/cache behavior for the
  local ONNX ColBERT model.
  """

  @typedoc "Configuration for the late-interaction (ColBERT) pipeline."
  @type t :: %__MODULE__{
          model: Xberg.LateInteractionModelType.t(),
          batch_size: non_neg_integer(),
          max_length: non_neg_integer(),
          query_max_length: non_neg_integer(),
          show_download_progress: boolean(),
          cache_dir: String.t() | nil,
          acceleration: Xberg.AccelerationConfig.t() | nil,
          max_embed_duration_secs: non_neg_integer() | nil
        }

  defstruct model: :preset,
            batch_size: 16,
            max_length: 512,
            query_max_length: 32,
            show_download_progress: false,
            cache_dir: nil,
            acceleration: nil,
            max_embed_duration_secs: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
