# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.NoChunkingReason do
  @moduledoc "Reason for not chunking a document."

  @typedoc "Reason for not chunking a document."
  @type t :: term()

  @typedoc "File is below size threshold."
  @type small_file :: %{type: :small_file, size_bytes: non_neg_integer(), threshold_bytes: non_neg_integer()}
  @typedoc "Document has fewer pages than threshold."
  @type few_pages :: %{type: :few_pages, page_count: non_neg_integer(), threshold: non_neg_integer()}
  @typedoc "PDF has substantial text layer (OCR not needed)."
  @type text_layer_detected :: %{type: :text_layer_detected, text_coverage: float(), avg_chars_per_page: non_neg_integer()}
  @typedoc "Document format does not support chunking."
  @type format_not_chunkable :: %{type: :format_not_chunkable, mime_type: String.t()}
  @typedoc "Chunking is disabled by configuration."
  @type chunking_disabled :: :chunking_disabled
  @typedoc "Force OCR is disabled and text extraction is fast."
  @type fast_text_extraction :: :fast_text_extraction

  def small_file(size_bytes, threshold_bytes), do: {:small_file, %{size_bytes: size_bytes, threshold_bytes: threshold_bytes}}
  def few_pages(page_count, threshold), do: {:few_pages, %{page_count: page_count, threshold: threshold}}

  def text_layer_detected(text_coverage, avg_chars_per_page),
    do: {:text_layer_detected, %{text_coverage: text_coverage, avg_chars_per_page: avg_chars_per_page}}

  def format_not_chunkable(mime_type), do: {:format_not_chunkable, %{mime_type: mime_type}}

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:small_file), do: "SmallFile"
  def wire_value(:few_pages), do: "FewPages"
  def wire_value(:text_layer_detected), do: "TextLayerDetected"
  def wire_value(:format_not_chunkable), do: "FormatNotChunkable"
  def wire_value(:chunking_disabled), do: "ChunkingDisabled"
  def wire_value(:fast_text_extraction), do: "FastTextExtraction"
  def wire_value(value) when is_tuple(value), do: wire_value(elem(value, 0))
end
