# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5d46f51dd22dabdd277025b6d848a79aeb4112cbd66affd26874b87dd76466a9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrBackendCapabilities do
  @moduledoc """
  A registered OCR backend's declared name and language capabilities.

  Returned by [`list_ocr_backend_capabilities`]. See that function's documentation for the
  determinism guarantees and the important caveat about what an empty `supported_languages`
  means.
  """

  @typedoc "A registered OCR backend's declared name and language capabilities."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          supported_languages: [String.t()]
        }

  defstruct name: nil,
            supported_languages: []
end
