# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d268385b8a40ac696f57b347b558e90309f13c9e9b9c37d273d7a18d7fb2cbf6
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PdfMetadata do
  @moduledoc """
  PDF-specific metadata.

  Contains metadata fields specific to PDF documents that are not in the common
  `Metadata` structure. Common fields like title, authors, keywords, and dates
  are at the `Metadata` level.
  """

  @typedoc "PDF-specific metadata."
  @type t :: %__MODULE__{
          pdf_version: String.t() | nil,
          producer: String.t() | nil,
          is_encrypted: boolean() | nil,
          width: integer() | nil,
          height: integer() | nil,
          page_count: non_neg_integer() | nil,
          scanned_confidence: float() | nil,
          scanned_pages: [non_neg_integer()] | nil,
          fabricated_text_pages: [non_neg_integer()] | nil,
          layout_gated_pages: [non_neg_integer()] | nil,
          layout_gate_reasons: [String.t()] | nil
        }

  defstruct pdf_version: nil,
            producer: nil,
            is_encrypted: nil,
            width: nil,
            height: nil,
            page_count: nil,
            scanned_confidence: nil,
            scanned_pages: nil,
            fabricated_text_pages: nil,
            layout_gated_pages: nil,
            layout_gate_reasons: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
