# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:52d99bf71e7cd93de88a15bfc38e070e3cad638f6c63e25df32183c739beee97
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.StructuredDataType do
  @moduledoc "Structured data type classification."

  @typedoc "Structured data type classification."
  @type t :: :json_ld | :microdata | :rdfa

  @json_ld :json_ld
  @microdata :microdata
  @rdfa :rdfa

  @doc "JSON-LD structured data"
  @spec json_ld() :: t()
  def json_ld, do: @json_ld
  @doc "Microdata"
  @spec microdata() :: t()
  def microdata, do: @microdata
  @doc "RDFa"
  @spec rdfa() :: t()
  def rdfa, do: @rdfa

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:json_ld), do: "json-ld"
  def wire_value(:microdata), do: "microdata"
  def wire_value(:rdfa), do: "rdfa"
end
