# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b277e272914a2c7663f47c02eee72f8901e3bc3b262d379eab1fefb3fbf85d8f
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.SummaryStrategy do
  @moduledoc "Summarisation strategy."

  @typedoc "Summarisation strategy."
  @type t :: :extractive | :abstractive

  @extractive :extractive
  @abstractive :abstractive

  @doc "Pure-Rust extractive summary (TextRank over the chunk graph). Deterministic, fast, no external service required."
  @spec extractive() :: t()
  def extractive, do: @extractive

  @doc "Abstractive summary produced by liter-llm. Requires `liter-llm` feature and a configured `LlmConfig`. Token usage is captured in [`ExtractedDocument::llm_usage`](super::extraction::ExtractedDocument::llm_usage)."
  @spec abstractive() :: t()
  def abstractive, do: @abstractive

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:extractive), do: "extractive"
  def wire_value(:abstractive), do: "abstractive"
end
