# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4020b96c7966c3be5b5a7ea9308ad95cc206995100677f4d5826dc8ded4b503b
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.Table do
  @moduledoc """
  Extracted table structure.

  Represents a table detected and extracted from a document (PDF, image, etc.).
  Tables are converted to both structured cell data and Markdown format.
  """

  @typedoc "Extracted table structure."
  @type t :: %__MODULE__{
          cells: [[String.t()]],
          markdown: String.t() | nil,
          page_number: non_neg_integer(),
          bounding_box: Xberg.BoundingBox.t() | nil,
          table_id: String.t() | nil,
          cell_styles: [Xberg.TableCellStyle.t()],
          columns: [String.t()] | nil
        }

  defstruct cells: [],
            markdown: nil,
            page_number: 0,
            bounding_box: nil,
            table_id: nil,
            cell_styles: [],
            columns: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
