# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2717fd29c4ad0a0c7d183ce2a9270c8cd4853f375fe6a6044b2461ce01ef7518
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.TextDirection do
  @moduledoc "Text direction enumeration for HTML documents."

  @typedoc "Text direction enumeration for HTML documents."
  @type t :: :left_to_right | :right_to_left | :auto

  @left_to_right :left_to_right
  @right_to_left :right_to_left
  @auto :auto

  @doc "Left-to-right text direction"
  @spec left_to_right() :: t()
  def left_to_right, do: @left_to_right
  @doc "Right-to-left text direction"
  @spec right_to_left() :: t()
  def right_to_left, do: @right_to_left
  @doc "Automatic text direction detection"
  @spec auto() :: t()
  def auto, do: @auto

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:left_to_right), do: "ltr"
  def wire_value(:right_to_left), do: "rtl"
  def wire_value(:auto), do: "auto"
end
