# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8220051b4e42b40ee3a5e3b38fb7d8ef2593b7021645d3d2376c747bb896641d
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.TokenReductionOptions do
  @moduledoc "Token reduction configuration."

  @typedoc "Token reduction configuration."
  @type t :: %__MODULE__{
          mode: String.t() | nil,
          preserve_important_words: boolean()
        }

  defstruct mode: "off",
            preserve_important_words: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
