<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:54d4dc663fbf343889496908404e9954b6b9d73162340a00cb3180563abdf75f
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\XbergApi;
use Xberg\ExtractionConfig;

/** E2e tests for category: post_processor_management. */
final class PostProcessorManagementTest extends TestCase
{


    /** Clear all post-processors and verify list is empty */
    public function test_post_processors_clear(): void
    {
        $result = XbergApi::clearPostProcessors();

        $this->assertTrue(true, 'expected the call not to throw');


    }


    /** List all registered post-processors */
    public function test_post_processors_list(): void
    {
        $result = XbergApi::listPostProcessors();

        $this->assertNotNull($result);


    }

}
