<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:81dc851c2675a98eb759ba02b0b085e3f05eccd8cce43f5b8ba43541b761b289
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\XbergApi;
use Xberg\ExtractionConfig;

/** E2e tests for category: registry. */
final class RegistryTest extends TestCase
{


    /** List embedding backends */
    public function test_list_embedding_backends(): void
    {
        $result = XbergApi::listEmbeddingBackends();

        $this->assertNotNull($result);


    }


    /** List OCR backends */
    public function test_list_ocr_backends(): void
    {
        $result = XbergApi::listOcrBackends();

        $this->assertNotNull($result);


    }


    /** List post-processors */
    public function test_list_post_processors(): void
    {
        $result = XbergApi::listPostProcessors();

        $this->assertNotNull($result);


    }


    /** List renderers */
    public function test_list_renderers(): void
    {
        $result = XbergApi::listRenderers();

        $this->assertNotNull($result);


    }


    /** List validators */
    public function test_list_validators(): void
    {
        $result = XbergApi::listValidators();

        $this->assertNotNull($result);


    }

}
