<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c3fc79841cfc02d1897bf84ad69b267b3a72cb20a6632239e6f542a848a2f35f
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\XbergApi;
use Xberg\ExtractionConfig;

/** E2e tests for category: renderer_management. */
final class RendererManagementTest extends TestCase
{


    /** Clear all renderers and verify list is empty */
    public function test_renderers_clear(): void
    {
        $result = XbergApi::clearRenderers();

        $this->assertTrue(true, 'expected the call not to throw');


    }


    /** List all registered renderers */
    public function test_renderers_list(): void
    {
        $result = XbergApi::listRenderers();

        $this->assertNotNull($result);


    }

}
