<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:88f6edcf4d48c1115a36520a485afb7e99569a258a5ebbef37b1270e3a15ddeb
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\XbergApi;
use Xberg\ExtractionConfig;

/** E2e tests for category: reranker_backend_management. */
final class RerankerBackendManagementTest extends TestCase
{


    /** Clear all reranker backends and verify list is empty */
    public function test_clear_reranker_backends(): void
    {
        $result = XbergApi::clearRerankerBackends();

        $this->assertTrue(true, 'expected the call not to throw');


    }


    /** List all registered reranker backends */
    public function test_list_reranker_backends(): void
    {
        $result = XbergApi::listRerankerBackends();

        $this->assertNotNull($result);


    }

}
