<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c8bac7e95f69cbc0c2fa29c69493bafed1c9144e5e878d5cbe13a04e654e03af
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\XbergApi;
use Xberg\ExtractInput;
use Xberg\ExtractionConfig;

/** E2e tests for category: summarization. */
final class SummarizationTest extends TestCase
{


    /** TextRank extractive summary over a multi-paragraph plain text document. Pure-Rust, deterministic, no external services required. */
    public function test_summarization_extractive_smoke(): void
    {
        $inputMockBaseUrl = getenv("MOCK_SERVER_SUMMARIZATION_EXTRACTIVE_SMOKE") ?: (getenv("MOCK_SERVER_URL") . "/fixtures/summarization_extractive_smoke");
        $inputJson = str_replace("\$mock_url", $inputMockBaseUrl, json_encode(["kind" => "uri", "uri" => "\$mock_url/text/book_war_and_peace_1p.txt"]));
        $input = \Xberg\ExtractInput::from_json($inputJson);
        $config = \Xberg\ExtractionConfig::from_json(json_encode(["summarization" => ["maxTokens" => 80, "strategy" => "extractive"]]));
        $result = XbergApi::extract($input, $config);

            $this->assertEquals("text/plain", $result->getResults()[0]->mimeType);
            $this->assertNotSame('', $result->getResults()[0]->getSummary()?->text ?? '', 'expected non-empty value');
            $this->assertEquals("extractive", $result->getResults()[0]->getSummary()?->strategy);


    }

}
