<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1b63d850b0fdb995ed1f25141f744215c45493b6589ac3eb0b48fe3ba7a4b311
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\XbergApi;
use Xberg\ExtractionConfig;

/** E2e tests for category: tokenizer_backend_management. */
final class TokenizerBackendManagementTest extends TestCase
{


    /** Clear all tokenizer backends and verify list is empty */
    public function test_tokenizer_backends_clear(): void
    {
        $result = XbergApi::clearTokenizerBackends();

        $this->assertTrue(true, 'expected the call not to throw');


    }


    /** List all registered tokenizer backends */
    public function test_tokenizer_backends_list(): void
    {
        $result = XbergApi::listTokenizerBackends();

        $this->assertNotNull($result);


    }

}
