// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ef9e959d8f8ae9114a794f9ce96b6d813d25307e745733166914c0cef1b54eab
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: embedding_backend_management.
final class EmbeddingBackendManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
        _ = "16777216".withCString { val in
            "RUST_MIN_STACK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testEmbeddingBackendsClear() throws {
        // Clear all embedding backends and verify list is empty
        XCTAssertNoThrow(try Xberg.clearEmbeddingBackends())
    }

    func testEmbeddingBackendsList() throws {
        // List all registered embedding backends
        XCTAssertNoThrow(try Xberg.listEmbeddingBackends())
    }

}
