// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3b437b234579641828d48faf5ffd0f1235775a56955bac65aec894712c64763c
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: ocr_backend_management.
final class OcrBackendManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
        _ = "16777216".withCString { val in
            "RUST_MIN_STACK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testOcrBackendCapabilitiesList() throws {
        // List all registered OCR backends with their declared language capabilities
        XCTAssertNoThrow(try Xberg.listOcrBackendCapabilities())
    }

    func testOcrBackendSupportsLanguageUnknownBackend() throws {
        // Checking language support on an unregistered OCR backend is an error
        do {
            _ = try Xberg.ocrBackendSupportsLanguage(backend: "nonexistent-backend-xyz", language: "eng")
            XCTFail("expected to throw")
        } catch {
            // success
        }
    }

    func testOcrBackendsClear() throws {
        // Clear all OCR backends and verify list is empty
        XCTAssertNoThrow(try Xberg.clearOcrBackends())
    }

    func testOcrBackendsList() throws {
        // List all registered OCR backends
        XCTAssertNoThrow(try Xberg.listOcrBackends())
    }

    func testOcrBackendsUnregister() throws {
        // Unregister nonexistent OCR backend gracefully
        XCTAssertNoThrow(try Xberg.unregisterOcrBackend(name: "nonexistent-backend-xyz"))
    }

}
