// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2ebc29a99fdb4b22b142a3c685068d40830a06e3773a32cd886b434102b90747
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: post_processor_management.
final class PostProcessorManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
        _ = "16777216".withCString { val in
            "RUST_MIN_STACK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testPostProcessorsClear() throws {
        // Clear all post-processors and verify list is empty
        XCTAssertNoThrow(try Xberg.clearPostProcessors())
    }

    func testPostProcessorsList() throws {
        // List all registered post-processors
        XCTAssertNoThrow(try Xberg.listPostProcessors())
    }

}
