// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d4aabb35c45182e969c27c1a73847039b5a5929fb1b4347a5914f837ca95f9bf
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: registry.
final class RegistryTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
        _ = "16777216".withCString { val in
            "RUST_MIN_STACK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testListEmbeddingBackends() throws {
        // List embedding backends
        XCTAssertNoThrow(try Xberg.listEmbeddingBackends())
    }

    func testListOcrBackends() throws {
        // List OCR backends
        XCTAssertNoThrow(try Xberg.listOcrBackends())
    }

    func testListPostProcessors() throws {
        // List post-processors
        XCTAssertNoThrow(try Xberg.listPostProcessors())
    }

    func testListRenderers() throws {
        // List renderers
        XCTAssertNoThrow(try Xberg.listRenderers())
    }

    func testListValidators() throws {
        // List validators
        XCTAssertNoThrow(try Xberg.listValidators())
    }

}
