// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6bab9867c3a1aa447a0384a2960e4506fd33eb0f438e773a123808934853f5ba
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: reranker_backend_management.
final class RerankerBackendManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
        _ = "16777216".withCString { val in
            "RUST_MIN_STACK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testClearRerankerBackends() throws {
        // Clear all reranker backends and verify list is empty
        XCTAssertNoThrow(try Xberg.clearRerankerBackends())
    }

    func testListRerankerBackends() throws {
        // List all registered reranker backends
        XCTAssertNoThrow(try Xberg.listRerankerBackends())
    }

}
