// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:de2c1301e211fd4a701797fcc6c7463097247547f74fb4ec781df6bf356d6343
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: validator_management.
final class ValidatorManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
        _ = "16777216".withCString { val in
            "RUST_MIN_STACK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testValidatorsClear() throws {
        // Clear all validators and verify list is empty
        XCTAssertNoThrow(try Xberg.clearValidators())
    }

    func testValidatorsList() throws {
        // List all registered validators
        XCTAssertNoThrow(try Xberg.listValidators())
    }

}
