// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:09ad6673ba471143f089fd8eff5383470861ba93cc6410543989cc4dd6effc74
// To regenerate: alef e2e generate
// To verify freshness: alef verify
package io.xberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.Xberg

/** E2e tests for category: pdf. */
class PdfTest {

    companion object {
        init {
            // Suite-level environment defaults from [e2e.env]. JVM OS env is
            // immutable; System.setProperty is the runtime-mutable analog. Each
            // entry uses setdefault semantics: only applied when not already set.
            if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
                System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true")
            }
            if (System.getProperty("RUST_MIN_STACK") == null) {
                System.setProperty("RUST_MIN_STACK", "16777216")
            }
            try {
                System.loadLibrary("xberg_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load xberg_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
    }
    @Test
    fun testPdfPageCountInvalid(): Unit = runBlocking {
        // pdf_page_count: a plain text file is not a PDF
        assertFailsWith<Exception> {
            Xberg.pdfPageCount(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get("text/plain.txt")), null)
        }
        Unit
    }

    @Test
    fun testPdfPageCountPassword(): Unit = runBlocking {
        // pdf_page_count: encrypted PDF opened with its user password
        val result = Xberg.pdfPageCount(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get("pdf/password_protected.pdf")), "")
        // not_error: covered by the bare Optional's own assertion
        assertEquals(2, result)
    }

    @Test
    fun testPdfPageCountValid(): Unit = runBlocking {
        // pdf_page_count: page count of a multi-page PDF
        val result = Xberg.pdfPageCount(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get("pdf/sample_contract.pdf")), null)
        // not_error: covered by the bare Optional's own assertion
        assertEquals(10, result)
    }

    @Test
    fun testPdfPageCountWrongPassword(): Unit = runBlocking {
        // pdf_page_count: a wrong non-empty password is rejected, proving the argument reaches the engine
        assertFailsWith<Exception> {
            Xberg.pdfPageCount(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get("pdf/password_protected.pdf")), "xberg-test-fake-wrong-password-1879")
        }
        Unit
    }

}
