// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ac89ce8a639994793c693637b61957f45754137d22ec13c81a826f2ddc70d7d9
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.Xberg
import io.xberg.RendererBridge
import io.xberg.IRenderer
import io.xberg.*

/** E2e tests for category: renderer_management. */
class RendererManagementTest {

    companion object {
        init {
            // Suite-level environment defaults from [e2e.env]. JVM OS env is
            // immutable; System.setProperty is the runtime-mutable analog. Each
            // entry uses setdefault semantics: only applied when not already set.
            if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
                System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true")
            }
            if (System.getProperty("RUST_MIN_STACK") == null) {
                System.setProperty("RUST_MIN_STACK", "16777216")
            }
            try {
                System.loadLibrary("xberg_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load xberg_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
    }
    @Test
    fun testRenderersClear(): Unit = runBlocking {
        // Clear all renderers and verify list is empty
        val result = RendererBridge.clearAll()
        assertNotNull(result, "expected non-null result")
    }

    @Test
    fun testRenderersList(): Unit = runBlocking {
        // List all registered renderers
        val result = Xberg.listRenderers()
        assertNotNull(result, "expected non-null result")
    }

}
