// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:758623f23789e838bb2cc8e122b978488762e0e44901f45260c735a64dff8f5e
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The extraction stopped after a cooperative cancellation request.
///
/// Rust callers can request cancellation through
/// `CancellationToken`. The REST async-jobs API uses the
/// same mechanism. Generated language bindings do not currently expose
/// in-process cancellation.
/// </summary>
public class CancelledException : XbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
