// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// Controls thread usage for constrained environments.
///
/// Set `max_threads` to cap all internal thread pools (Rayon, ONNX Runtime
/// intra-op) and batch concurrency to a single limit.
///
/// # Default budget when `max_threads` is unset
///
/// Without an explicit `max_threads`, the effective budget is
/// `min(detected_cpu_cores, 8)` — a deliberate ceiling chosen for
/// serverless/shared-tenant defaults, not a full-host auto-scale. On a host
/// with more than 8 cores this means the extra cores go **unused** unless one
/// of the following applies:
///
/// - `max_threads` is set explicitly above 8 (the only way to exceed the
///   ceiling on a bare-metal or VM host with no CPU quota).
/// - The process runs under a Linux cgroup CPU quota (containers, Kubernetes
///   `resources.limits.cpu`); in that case the quota itself is used as the
///   ceiling instead of the hardcoded 8, since the quota already reflects a
///   deliberately-configured resource limit.
///
/// When neither applies and the host has more than 8 cores, a single
/// `WARN`-level log is emitted the first time the budget is resolved,
/// naming the detected core count and the applied cap, so the ceiling is
/// discoverable without reading source.
/// </summary>
public sealed record ConcurrencyConfig {
  /// <summary>
  /// Maximum number of threads for all internal thread pools.
  ///
  /// Caps Rayon global pool size, ONNX Runtime intra-op threads, and the
  /// combined document/inner-task budget for batch extraction. When `None`,
  /// the effective budget is `min(detected_cpu_cores, 8)` unless a Linux
  /// cgroup CPU quota is present, in which case the quota is used as the
  /// ceiling instead. On hosts with more than 8 cores and no cgroup quota,
  /// set `max_threads` explicitly to use the additional cores — the
  /// default will not scale past 8 on its own.
  /// </summary>
  [JsonPropertyName("max_threads")]
  public ulong ? MaxThreads { get; init; } = null;

  /// <summary>
  /// Parse a <see cref="ConcurrencyConfig"/> from a JSON string.
  /// </summary>
  /// <exception cref="XbergException">When the JSON cannot be
  /// deserialised.</exception>
  public static ConcurrencyConfig FromJson(string json) {
    try {
      return JsonSerializer.Deserialize<ConcurrencyConfig>(json, JsonOptions) ??
             throw new XbergException(
                 $"Failed to parse ConcurrencyConfig from JSON: deserializer returned null");
    } catch (XbergException) {
      throw;
    } catch (Exception e) {
      throw new XbergException(
          $"Failed to parse ConcurrencyConfig from JSON: {e.Message}", e);
    }
  }

  private static readonly JsonSerializerOptions JsonOptions = new() {
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
    Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower),
                   new ByteArrayJsonConverter() },
  };

  /// <summary>Options for serializing config/input objects to FFI. Strips nulls
  /// (nullable C# fields default to null and would override required Rust
  /// fields with non-deserialisable nulls) but preserves explicit false/0 so
  /// caller intent is kept.</summary>
  private static readonly JsonSerializerOptions JsonSerializationOptions =
      new() {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(
                           JsonNamingPolicy.SnakeCaseLower),
                       new ByteArrayJsonConverter() },
      };
}
