// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3cc8609564f277cf37637e7f9b6d2581f33b1942b7140d22d5f9bfc734f5caff
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Invalid configuration value.
/// </summary>
public class ConfigErrorException : HeuristicsErrorException
{
    public ConfigErrorException(string message) : base(message) { }

    public ConfigErrorException(string message, Exception innerException) : base(message, innerException) { }
}
