// This file is auto-generated by alef. DO NOT EDIT.
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;
/// <summary>
/// How a backend's reported page-level confidence must be interpreted.
///
/// Backend confidence scores are not interchangeable. Tesseract's mean word
/// confidence is a classifier score validated to track legibility on a 0-100
/// scale. Sceptre (EasyOCR-based) reports a length-penalised `custom_mean` that
/// is rescaled into the same 0-100 range but is *not* comparable — its ordering
/// can be inverted relative to legibility (a dense prose page can score lower
/// than a nearly-blank one). A page-rejection gate calibrated on Tesseract's
/// scale was once applied unconditionally to sceptre's output and rejected
/// every page of a 16-page document, emptying it. This descriptor exists so
/// gating code can ask a backend what its number means instead of assuming.
/// </summary>
[JsonConverter(typeof(ConfidenceSemanticsJsonConverter))]
public enum ConfidenceSemantics {
  /// <summary>
  /// Validated to track legibility on a known scale — usable as an absolute
  /// quality gate.
  /// </summary>
  [JsonPropertyName("Legibility")] Legibility,
  /// <summary>
  /// A number is reported, but it is not validated to correlate with
  /// legibility. Never gate on it.
  /// </summary>
  [JsonPropertyName("Uncalibrated")] Uncalibrated,
  /// <summary>
  /// No page-level confidence is reported at all.
  /// </summary>
  [JsonPropertyName("None")] None,
}

/// <summary>
/// Custom JSON converter for <see cref="ConfidenceSemantics"/> that respects
/// explicit variant names.
/// </summary>
internal sealed class ConfidenceSemanticsJsonConverter
    : JsonConverter<ConfidenceSemantics> {
  public override ConfidenceSemantics Read(ref Utf8JsonReader reader,
                                           Type typeToConvert,
                                           JsonSerializerOptions options) {
    var value = reader.GetString();
    return value switch { "Legibility" => ConfidenceSemantics.Legibility,
                          "Uncalibrated" => ConfidenceSemantics.Uncalibrated,
                          "None" => ConfidenceSemantics.None,
                          _ => throw new JsonException(
                              $"Unknown ConfidenceSemantics value: {value}") };
  }

  public override void Write(Utf8JsonWriter writer, ConfidenceSemantics value,
                             JsonSerializerOptions options) {
    var str =
        value switch { ConfidenceSemantics.Legibility => "Legibility",
                       ConfidenceSemantics.Uncalibrated => "Uncalibrated",
                       ConfidenceSemantics.None => "None",
                       _ => throw new JsonException(
                           $"Unknown ConfidenceSemantics value: {value}") };
    writer.WriteStringValue(str);
  }
}
