// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:abec44a599c251e0d524a60de517c8171d10fb33625b437dca302d7b4844a949
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The embedding model or embedding pipeline returned an error.
/// </summary>
public class EmbeddingException : XbergErrorException
{
    public EmbeddingException(string message) : base(message) { }

    public EmbeddingException(string message, Exception innerException) : base(message, innerException) { }
}
