// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:26ce1f240441fb60945c327e391ebd616343ec2d0b34775de467a4865c65b1e0
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors that can occur during heuristics analysis.
/// </summary>
public class HeuristicsErrorException : XbergException
{
    public HeuristicsErrorException(string message) : base(message) { }

    public HeuristicsErrorException(string message, Exception innerException) : base(message, innerException) { }
}
