// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// A text block with hierarchy level assignment.
///
/// Represents a block of text with semantic heading information extracted from
/// font size clustering and hierarchical analysis.
/// </summary>
public sealed record HierarchicalBoundingBox {
  /// <summary>
  /// Left coordinate.
  /// </summary>
  [JsonPropertyName("left")]
  public float Left { get; init; } = 0.0f;

  /// <summary>
  /// Top coordinate.
  /// </summary>
  [JsonPropertyName("top")]
  public float Top {
    get; init;
  } = 0.0f;

  /// <summary>
  /// Right coordinate.
  /// </summary>
  [JsonPropertyName("right")]
  public float Right {
    get; init;
  } = 0.0f;

  /// <summary>
  /// Bottom coordinate.
  /// </summary>
  [JsonPropertyName("bottom")]
  public float Bottom {
    get; init;
  } = 0.0f;

  /// <summary>
  /// Parse a <see cref="HierarchicalBoundingBox"/> from a JSON string.
  /// </summary>
  /// <exception cref="XbergException">When the JSON cannot be
  /// deserialised.</exception>
  public static HierarchicalBoundingBox FromJson(string json) {
    try {
      return JsonSerializer.Deserialize<HierarchicalBoundingBox>(json,
                                                                 JsonOptions) ??
             throw new XbergException(
                 $"Failed to parse HierarchicalBoundingBox from JSON: deserializer returned null");
    } catch (XbergException) {
      throw;
    } catch (Exception e) {
      throw new XbergException(
          $"Failed to parse HierarchicalBoundingBox from JSON: {e.Message}", e);
    }
  }

  private static readonly JsonSerializerOptions JsonOptions = new() {
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
    Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower),
                   new ByteArrayJsonConverter() },
  };

  /// <summary>Options for serializing config/input objects to FFI. Strips nulls
  /// (nullable C# fields default to null and would override required Rust
  /// fields with non-deserialisable nulls) but preserves explicit false/0 so
  /// caller intent is kept.</summary>
  private static readonly JsonSerializerOptions JsonSerializationOptions =
      new() {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(
                           JsonNamingPolicy.SnakeCaseLower),
                       new ByteArrayJsonConverter() },
      };
}
