// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:14c8432cf36fc78a64a18efc0a3ec91fca260dfbbb06884b64b77b79649a4395
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// Image preprocessing configuration for OCR.
///
/// These settings control how images are preprocessed before OCR to improve
/// text recognition quality. Different preprocessing strategies work better
/// for different document types.
/// </summary>
public sealed record ImagePreprocessingConfig
{
    /// <summary>
    /// Target DPI for the image (300 is standard, 600 for small text).
    ///
    /// For a PDF page, this resamples the already-rendered raster; it does not make the page
    /// re-render at a higher native resolution. A value above what
    /// `image.preprocessing.calculate_target_dpi`'s memory/dimension clamp allows is
    /// silently capped (GH#1786: 400 and 600 both clamped to the same ~372 on a Letter page
    /// and produced byte-identical output), so upscaling interpolated pixels this way adds no
    /// detail. To change the actual PDF render resolution, set `images.target_dpi` on
    /// `ExtractionConfig` instead
    /// (`image.dpi.effective_pdf_render_dpi`).
    /// </summary>
    [JsonPropertyName("target_dpi")]
    public int TargetDpi { get; init; } = 300;

    /// <summary>
    /// Auto-detect and correct image rotation.
    /// </summary>
    [JsonPropertyName("auto_rotate")]
    public bool AutoRotate { get; init; } = false;

    /// <summary>
    /// Correct skew (tilted images). Must be `false` with `none` or `off` binarization.
    /// </summary>
    [JsonPropertyName("deskew")]
    public bool Deskew { get; init; } = true;

    /// <summary>
    /// Remove noise from the image.
    /// </summary>
    [JsonPropertyName("denoise")]
    public bool Denoise { get; init; } = false;

    /// <summary>
    /// Enhance contrast for better text visibility. With `none` or `off` binarization, this
    /// applies background normalization and sharpening while preserving grayscale pixels.
    /// </summary>
    [JsonPropertyName("contrast_enhance")]
    public bool ContrastEnhance { get; init; } = false;

    /// <summary>
    /// Binarization method: "none" (alias "off"), "otsu", "sauvola", or "adaptive".
    /// `deskew` must be `false` when this is `none` or `off`.
    /// </summary>
    [JsonPropertyName("binarization_method")]
    public string BinarizationMethod { get; init; } = "otsu";

    /// <summary>
    /// Invert colors (white text on black → black on white).
    /// </summary>
    [JsonPropertyName("invert_colors")]
    public bool InvertColors { get; init; } = false;

    /// <summary>
    /// Normalize shaded table rows (e.g. a subtotal row on a light or dark fill) before
    /// binarization, so each shaded band is stretched to its own dark-text-on-white
    /// polarity instead of being lost to a single whole-page threshold (GH#1785).
    ///
    /// This is a per-band step, not a replacement for `binarization_method`: no single
    /// whole-page method recovers every fill color, and the per-band step itself can
    /// regress a row style it does not fully model (e.g. a mid-grey fill with white
    /// text), so it defaults to `false` rather than being enabled unconditionally.
    /// </summary>
    [JsonPropertyName("normalize_shaded_rows")]
    public bool NormalizeShadedRows { get; init; } = false;


    /// <summary>
    /// Parse a <see cref="ImagePreprocessingConfig"/> from a JSON string.
    /// </summary>
    /// <exception cref="XbergException">When the JSON cannot be deserialised.</exception>
    public static ImagePreprocessingConfig FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ImagePreprocessingConfig>(json, JsonOptions)
                ?? throw new XbergException($"Failed to parse ImagePreprocessingConfig from JSON: deserializer returned null");
        }
        catch (XbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new XbergException($"Failed to parse ImagePreprocessingConfig from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    public static ImagePreprocessingConfig Default()
    {
        var nativeResult = NativeMethods.ImagePreprocessingConfigDefault();
        var jsonPtr = NativeMethods.ImagePreprocessingConfigToJson(nativeResult);
        var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.ImagePreprocessingConfigFree(nativeResult);
        return JsonSerializer.Deserialize<ImagePreprocessingConfig>(json ?? "null", JsonOptions)!;
    }
}
