// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:693bf4460b0989c6c400e10de9e13663ea2125b511ce38a948ccb79c46817633
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An image manipulation operation (resize, decode, DPI conversion) failed.
/// </summary>
public class ImageProcessingException : XbergErrorException
{
    public ImageProcessingException(string message) : base(message) { }

    public ImageProcessingException(string message, Exception innerException) : base(message, innerException) { }
}
