// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// Inclusive word-count range used to form keyword candidates.
/// </summary>
public sealed record NgramRange {
  /// <summary>
  /// Minimum number of words in a candidate.
  /// </summary>
  [JsonPropertyName("min")]
  public ulong Min { get; init; } = 1;

  /// <summary>
  /// Maximum number of words in a candidate.
  /// </summary>
  [JsonPropertyName("max")]
  public ulong Max {
    get; init;
  } = 3;

  /// <summary>
  /// Parse a <see cref="NgramRange"/> from a JSON string.
  /// </summary>
  /// <exception cref="XbergException">When the JSON cannot be
  /// deserialised.</exception>
  public static NgramRange FromJson(string json) {
    try {
      return JsonSerializer.Deserialize<NgramRange>(json, JsonOptions) ??
             throw new XbergException(
                 $"Failed to parse NgramRange from JSON: deserializer returned null");
    } catch (XbergException) {
      throw;
    } catch (Exception e) {
      throw new XbergException(
          $"Failed to parse NgramRange from JSON: {e.Message}", e);
    }
  }

  private static readonly JsonSerializerOptions JsonOptions = new() {
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
    Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower),
                   new ByteArrayJsonConverter() },
  };

  /// <summary>Options for serializing config/input objects to FFI. Strips nulls
  /// (nullable C# fields default to null and would override required Rust
  /// fields with non-deserialisable nulls) but preserves explicit false/0 so
  /// caller intent is kept.</summary>
  private static readonly JsonSerializerOptions JsonSerializationOptions =
      new() {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(
                           JsonNamingPolicy.SnakeCaseLower),
                       new ByteArrayJsonConverter() },
      };

  public static NgramRange Default() {
    var nativeResult = NativeMethods.NgramRangeDefault();
    var jsonPtr = NativeMethods.NgramRangeToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.NgramRangeFree(nativeResult);
    return JsonSerializer.Deserialize<NgramRange>(json ?? "null", JsonOptions)!;
  }
}
