// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// A unified OCR element representing detected text with full metadata.
///
/// This is the primary type for structured OCR output, preserving all
/// information from both Tesseract and PaddleOCR backends.
/// </summary>
public sealed record OcrElement {
  /// <summary>
  /// The recognized text content.
  /// </summary>
  [JsonPropertyName("text")]
  public string Text { get; init; } = "";

  /// <summary>
  /// Bounding geometry (rectangle or quadrilateral).
  /// </summary>
  [JsonPropertyName("geometry")]
  public required OcrBoundingGeometry Geometry {
    get; init;
  }

  /// <summary>
  /// Confidence scores for detection and recognition.
  /// </summary>
  [JsonPropertyName("confidence")]
  public OcrConfidence Confidence {
    get; init;
  } = new OcrConfidence();

  /// <summary>
  /// Hierarchical level (word, line, block, page).
  /// </summary>
  [JsonPropertyName("level")]
  public OcrElementLevel Level {
    get; init;
  } = OcrElementLevel.Line;

  /// <summary>
  /// Rotation information (if detected).
  /// </summary>
  [JsonPropertyName("rotation")]
  public OcrRotation
      ? Rotation {
          get; init;
        } = null;

  /// <summary>
  /// Page number (1-indexed).
  /// </summary>
  [JsonPropertyName("page_number")]
  public uint PageNumber {
    get; init;
  } = 1;

  /// <summary>
  /// Parent element ID for hierarchical relationships.
  ///
  /// When hierarchy output is enabled, this resolves to another emitted
  /// element's `backend_metadata["element_id"]` value.
  /// </summary>
  [JsonPropertyName("parent_id")]
  public string
      ? ParentId {
          get; init;
        } = null;

  /// <summary>
  /// Backend-specific metadata that doesn't fit the unified schema.
  /// </summary>
  [JsonPropertyName("backend_metadata")]
  public Dictionary<string, JsonElement> BackendMetadata {
    get; init;
  } = new Dictionary<string, JsonElement>();

  /// <summary>
  /// Parse a <see cref="OcrElement"/> from a JSON string.
  /// </summary>
  /// <exception cref="XbergException">When the JSON cannot be
  /// deserialised.</exception>
  public static OcrElement FromJson(string json) {
    try {
      return JsonSerializer.Deserialize<OcrElement>(json, JsonOptions) ??
             throw new XbergException(
                 $"Failed to parse OcrElement from JSON: deserializer returned null");
    } catch (XbergException) {
      throw;
    } catch (Exception e) {
      throw new XbergException(
          $"Failed to parse OcrElement from JSON: {e.Message}", e);
    }
  }

  private static readonly JsonSerializerOptions JsonOptions = new() {
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
    Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower),
                   new ByteArrayJsonConverter() },
  };

  /// <summary>Options for serializing config/input objects to FFI. Strips nulls
  /// (nullable C# fields default to null and would override required Rust
  /// fields with non-deserialisable nulls) but preserves explicit false/0 so
  /// caller intent is kept.</summary>
  private static readonly JsonSerializerOptions JsonSerializationOptions =
      new() {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(
                           JsonNamingPolicy.SnakeCaseLower),
                       new ByteArrayJsonConverter() },
      };
}
