// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1113ee4dab39b13c1012e0ec69d2fba6690b8fbbefccf44952dd58b81f5897c7
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file is not valid JSON.
/// </summary>
public class ParseException : LoadErrorException
{
    public ParseException(string message) : base(message) { }

    public ParseException(string message, Exception innerException) : base(message, innerException) { }
}
