// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ea6e1eb88dbc58f6c8a2ecdb600b2a7dd88479ba6a3d600322696b706176f783
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// PDF analysis step failed (only when `heuristics-pdf` feature is active).
/// </summary>
public class PdfAnalysisErrorException : HeuristicsErrorException
{
    public PdfAnalysisErrorException(string message) : base(message) { }

    public PdfAnalysisErrorException(string message, Exception innerException) : base(message, innerException) { }
}
