// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:818a7ad0eccde3cf4a093d7bca5890d58477320697761fc6a4d12714cd272d22
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A registered plugin returned an error during extraction.
/// </summary>
public class PluginException : XbergErrorException
{
    public PluginException(string message) : base(message) { }

    public PluginException(string message, Exception innerException) : base(message, innerException) { }
}
