// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c1f22aeafe6c80f45cf6382369aade7f3573fd60d38426782eaf061dc57df430
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// Configuration for the redaction post-processor.
/// </summary>
public sealed record RedactionConfig
{
    /// <summary>
    /// Categories to redact. Empty means "every category supported by the engine."
    /// </summary>
    [JsonPropertyName("categories")]
    public List<PiiCategory> Categories { get; init; } = [];

    /// <summary>
    /// Strategy applied to every match.
    /// </summary>
    [JsonPropertyName("strategy")]
    public RedactionStrategy Strategy { get; init; } = RedactionStrategy.Mask;

    /// <summary>
    /// Optional NER backend — required to redact PERSON / ORGANIZATION / LOCATION
    /// categories (the pure-Rust pattern engine only covers regex-detectable PII).
    /// </summary>
    [JsonPropertyName("ner")]
    public NerConfig? Ner { get; init; } = null;

    /// <summary>
    /// When `true`, chunk byte ranges are kept consistent with the rewritten content by
    /// adjusting `byte_start` / `byte_end` after replacement. When `false`, chunk byte
    /// ranges still refer to the *original* content offsets — useful when downstream
    /// consumers want to map findings back to the original document.
    /// </summary>
    [JsonPropertyName("preserve_offsets")]
    public bool PreserveOffsets { get; init; } = true;

    /// <summary>
    /// Arbitrary user-supplied literal terms to redact.
    ///
    /// Each term is treated as a regex hit against the document, surfacing as
    /// `PiiCategory.Custom(label)` in `RedactionFinding`
    /// where `label` is the per-term label (defaulting to the literal value itself).
    /// Case-insensitive by default; set `RedactionTerm.case_sensitive` for exact match.
    ///
    /// Use this when you need to redact tenant-specific tokens (employee IDs,
    /// project codes, internal product names) without writing a custom plugin.
    /// </summary>
    [JsonPropertyName("custom_terms")]
    public List<RedactionTerm> CustomTerms { get; init; } = [];

    /// <summary>
    /// Arbitrary user-supplied regex patterns to redact.
    ///
    /// Same surfacing semantics as `custom_terms`: each
    /// hit becomes a `PiiCategory.Custom(label)` finding. Patterns are validated
    /// at config-construction time via `RedactionConfig.validate`.
    /// </summary>
    [JsonPropertyName("custom_patterns")]
    public List<RedactionPattern> CustomPatterns { get; init; } = [];

    /// <summary>
    /// Findings supplied inline by an external inspection engine.
    /// </summary>
    [JsonPropertyName("findings")]
    public List<ExternalRedactionFinding> Findings { get; init; } = [];

    /// <summary>
    /// Minimum accepted confidence for scored external findings. Findings without a score remain eligible.
    /// </summary>
    [JsonPropertyName("min_score")]
    public float? MinScore { get; init; } = null;

    /// <summary>
    /// JSON array or JSON Lines file containing external findings.
    /// </summary>
    [JsonPropertyName("findings_path")]
    public string? FindingsPath { get; init; } = null;

    /// <summary>
    /// Unit used by configured findings that derive their text from offsets.
    /// </summary>
    [JsonPropertyName("findings_offset_encoding")]
    public RedactionOffsetEncoding FindingsOffsetEncoding { get; init; } = RedactionOffsetEncoding.UnicodeCodePoints;


    /// <summary>
    /// Parse a <see cref="RedactionConfig"/> from a JSON string.
    /// </summary>
    /// <exception cref="XbergException">When the JSON cannot be deserialised.</exception>
    public static RedactionConfig FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<RedactionConfig>(json, JsonOptions)
                ?? throw new XbergException($"Failed to parse RedactionConfig from JSON: deserializer returned null");
        }
        catch (XbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new XbergException($"Failed to parse RedactionConfig from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    public static RedactionConfig Default()
    {
        var nativeResult = NativeMethods.RedactionConfigDefault();
        var jsonPtr = NativeMethods.RedactionConfigToJson(nativeResult);
        var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.RedactionConfigFree(nativeResult);
        return JsonSerializer.Deserialize<RedactionConfig>(json ?? "null", JsonOptions)!;
    }
}
