// This file is auto-generated by alef. DO NOT EDIT.
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Collections.Generic;

namespace Xberg;

// The native handle is the scalar `AlefHandle` (`uint64_t`) registry index, not
// a pointer. `SafeHandle`'s only storage slot is a pointer-width `IntPtr`, so
// the `ulong` is packed into that slot as a raw bit pattern (never
// dereferenced) to keep `SafeHandle`'s guaranteed finalization and
// `DangerousAddRef`/`DangerousRelease` ref-counting, which the borrow/lease/
// transfer machinery below builds on. This is lossless on every currently
// supported .NET target (IntPtr is 8 bytes on all 64-bit platforms .NET 5+
// ships on); on a true 32-bit process a handle value above `uint.MaxValue`
// would truncate, but that requires over four billion concurrently live handles
// of this type, and 32-bit .NET targets are legacy-only.
internal sealed class RegistrySafeHandle : SafeHandle {
  internal RegistrySafeHandle(ulong handle) : base(IntPtr.Zero, true) {
    SetHandle(Pack(handle));
  }

  public override bool IsInvalid => handle == IntPtr.Zero;

  internal static IntPtr Pack(ulong value) => unchecked((IntPtr)(long)value);

  internal static ulong Unpack(IntPtr value) => unchecked((ulong)(long)value);

  protected override bool ReleaseHandle() {
    NativeMethods.RegistryFree(Unpack(handle));
    return true;
  }
}
/// <summary>/// Sorted map of preset id → `Preset`./// </summary>
public sealed class Registry : IDisposable {
  private static readonly JsonSerializerOptions JsonOptions =
      new() { Converters = { new JsonStringEnumConverter(
                  JsonNamingPolicy.SnakeCaseLower) },
              DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

  private static readonly JsonSerializerOptions JsonSerializationOptions =
      new() {
        Converters = { new JsonStringEnumConverter(
            JsonNamingPolicy.SnakeCaseLower) },
      };
  private RegistrySafeHandle _safeHandle;
  private readonly object _handleLock = new();
  private int _activeBorrows;
  private bool _handleUnavailable;
  private bool _transferPending;

  internal sealed class HandleLease : IDisposable {
    private Registry? _owner;

    internal HandleLease(Registry owner, ulong handle) {
      _owner = owner;
      Handle = handle;
    }

    internal ulong Handle { get; }

    public void Dispose() {
      var owner =
          global::System.Threading.Interlocked.Exchange(ref _owner, null);
      owner?.ReleaseBorrow();
    }
  }

  private sealed class HandleTransfer : IDisposable {
    private Registry? _owner;
    private RegistrySafeHandle? _transferredHandle;

    internal HandleTransfer(Registry owner, ulong handle) {
      _owner = owner;
      _transferredHandle = new RegistrySafeHandle(handle);
    }

    internal ulong Handle => _transferredHandle is {}
    transferredHandle? RegistrySafeHandle.Unpack(
        transferredHandle.DangerousGetHandle())
        : throw new InvalidOperationException(
              "Handle transfer is no longer active");

    internal void Commit() {
      var transferredHandle =
          _transferredHandle ?? throw new InvalidOperationException(
                                    "Handle transfer is no longer active");
      transferredHandle.SetHandleAsInvalid();
      _transferredHandle = null;
      var owner = _owner;
      _owner = null;
      owner?.CommitTransfer();
    }

    public void Dispose() {
      var transferredHandle = global::System.Threading.Interlocked.Exchange(
          ref _transferredHandle, null);
      var owner =
          global::System.Threading.Interlocked.Exchange(ref _owner, null);
      if (transferredHandle is null)
        return;
      if (owner is null) {
        transferredHandle.Dispose();
        return;
      }
      var handle =
          RegistrySafeHandle.Unpack(transferredHandle.DangerousGetHandle());
      transferredHandle.SetHandleAsInvalid();
      owner.RollbackTransfer(handle);
    }
  }

  internal Registry(ulong handle) {
    _safeHandle = new RegistrySafeHandle(handle);
  }

  internal ulong Handle => GetHandle();

  private ulong GetHandle() {
    lock (_handleLock) {
      ThrowIfHandleUnavailable();
      return RegistrySafeHandle.Unpack(_safeHandle.DangerousGetHandle());
    }
  }

  internal HandleLease BorrowHandle() {
    lock (_handleLock) {
      ThrowIfHandleUnavailable();
      var lease = new HandleLease(
          this, RegistrySafeHandle.Unpack(_safeHandle.DangerousGetHandle()));
      var addRefSucceeded = false;
      _safeHandle.DangerousAddRef(ref addRefSucceeded);
      if (!addRefSucceeded)
        throw new ObjectDisposedException(nameof(Registry));
      _activeBorrows++;
      return lease;
    }
  }

  private void ReleaseBorrow() {
    lock (_handleLock) {
      _safeHandle.DangerousRelease();
      _activeBorrows--;
      if (_activeBorrows == 0)
        global::System.Threading.Monitor.PulseAll(_handleLock);
    }
  }

  private HandleTransfer TakeHandle() {
    lock (_handleLock) {
      ThrowIfHandleUnavailable();
      WaitForBorrowedCalls();
      var transfer = new HandleTransfer(
          this, RegistrySafeHandle.Unpack(_safeHandle.DangerousGetHandle()));
      _handleUnavailable = true;
      _safeHandle.SetHandleAsInvalid();
      _transferPending = true;
      return transfer;
    }
  }

  private void RollbackTransfer(ulong handle) {
    lock (_handleLock) {
      _transferPending = false;
      _safeHandle = new RegistrySafeHandle(handle);
      _handleUnavailable = false;
      global::System.Threading.Monitor.PulseAll(_handleLock);
    }
  }

  private void CommitTransfer() {
    lock (_handleLock) {
      _transferPending = false;
      global::System.Threading.Monitor.PulseAll(_handleLock);
    }
  }

  private void WaitForBorrowedCalls() {
    var interrupted = false;
    while (_activeBorrows != 0) {
      try {
        global::System.Threading.Monitor.Wait(_handleLock);
      } catch (global::System.Threading.ThreadInterruptedException) {
        interrupted = true;
      }
    }
    if (interrupted)
      global::System.Threading.Thread.CurrentThread.Interrupt();
  }

  private void WaitForPendingTransfer() {
    var interrupted = false;
    while (_transferPending) {
      try {
        global::System.Threading.Monitor.Wait(_handleLock);
      } catch (global::System.Threading.ThreadInterruptedException) {
        interrupted = true;
      }
    }
    if (interrupted)
      global::System.Threading.Thread.CurrentThread.Interrupt();
  }

  private void ThrowIfHandleUnavailable() {
    if (_handleUnavailable || _safeHandle.IsClosed || _safeHandle.IsInvalid) {
      throw new ObjectDisposedException(nameof(Registry));
    }
  }

  public void Dispose() {
    lock (_handleLock) {
      if (_transferPending) {
        WaitForPendingTransfer();
        if (_handleUnavailable)
          return;
      }
      if (_handleUnavailable)
        return;
      _handleUnavailable = true;
      WaitForBorrowedCalls();
      _safeHandle.Dispose();
    }
  }

  /// <summary>
  /// Build the registry from preset files embedded at compile time under
  /// `src/presets/library/`. Validates every file against the meta-schema.
  /// </summary>
  public static Registry LoadEmbedded() {
    var nativeResult = NativeMethods.RegistryLoadEmbedded(

    );
    if (nativeResult == 0) {
      throw XbergException.FromLastError("RegistryLoadEmbedded failed");
    }
    var returnValue = new Registry(nativeResult);
    return returnValue;
  }

  /// <summary>
  /// Look up a preset by its identifier.
  /// </summary>
  public Preset? Get(string id) {
    using var handleLease = BorrowHandle();
    var nativeResult = NativeMethods.RegistryGet(handleLease.Handle, id);
    if (nativeResult == 0) {
      return null;
    }
    var jsonPtr = NativeMethods.PresetToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.PresetFree(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<Preset?>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Materialize a `PresetSummary` list for the public registry endpoint.
  /// </summary>
  public List<PresetSummary> Summaries() {
    using var handleLease = BorrowHandle();
    var nativeResult = NativeMethods.RegistrySummaries(handleLease.Handle);
    if (nativeResult == IntPtr.Zero) {
      throw XbergException.FromLastError("RegistrySummaries failed");
    }
    var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
        nativeResult);
    NativeMethods.FreeString(nativeResult);
    var returnValue = JsonSerializer.Deserialize<List<PresetSummary>>(
        json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Number of presets currently loaded.
  /// </summary>
  public ulong Len() {
    using var handleLease = BorrowHandle();
    var nativeResult = NativeMethods.RegistryLen(handleLease.Handle);
    var returnValue = nativeResult;
    return returnValue;
  }

  /// <summary>
  /// Whether the registry contains zero presets.
  /// </summary>
  public bool IsEmpty() {
    using var handleLease = BorrowHandle();
    var nativeResult = NativeMethods.RegistryIsEmpty(handleLease.Handle);
    var returnValue = nativeResult != 0;
    return returnValue;
  }

  /// <summary>
  /// Read raw sample bytes for `&lt;preset_id&gt;` from
  /// `library/&lt;id&gt;/samples/&lt;name&gt;`. Returns `None` when the file is
  /// absent.
  /// </summary>
  public byte[]? SampleBytes(string presetId, string name) {
    using var handleLease = BorrowHandle();
    var nativeResult =
        NativeMethods.RegistrySampleBytes(handleLease.Handle, presetId, name);
    if (nativeResult == IntPtr.Zero) {
      return null;
    }
    var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
        nativeResult);
    NativeMethods.FreeString(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<byte[]?>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Load additional preset files from a runtime directory and insert them
  /// into this registry.
  ///
  /// Reads every `*.json` file directly under `dir` (non-recursive),
  /// validates each against the meta-schema, and inserts it. Files that fail
  /// validation are rejected — the error is returned immediately and the
  /// registry is left in a partially-updated state. Existing entries with the
  /// same id are overwritten.
  ///
  /// Returns the number of presets successfully loaded from `dir`.
  ///
  /// # Use case
  ///
  /// This is the injection point for downstream catalogs that add curated
  /// presets on top of the single embedded OSS preset.
  /// </summary>
  public ulong ExtendFromDir(string dir) {
    using var handleLease = BorrowHandle();
    var nativeResult =
        NativeMethods.RegistryExtendFromDir(handleLease.Handle, dir);
    if (NativeMethods.LastErrorCode() != 0) {
      throw XbergException.FromLastError("RegistryExtendFromDir failed");
    }
    var returnValue = nativeResult;
    return returnValue;
  }
}
