// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1c54de8a29c381fabbc27f0335dd9179248e4e16d097f8362b4ce818b6192ad1
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors produced while resolving a preset against caller overrides.
/// </summary>
public class ResolveErrorException : XbergException
{
    public ResolveErrorException(string message) : base(message) { }

    public ResolveErrorException(string message, Exception innerException) : base(message, innerException) { }
}
