// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:29ae2deb38883da8c5168c2e79e0b3673f20b2e4eb400faed720773e23d240dc
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file parses as JSON but does not validate against the meta-schema.
/// </summary>
public class SchemaValidationException : LoadErrorException
{
    public SchemaValidationException(string message) : base(message) { }

    public SchemaValidationException(string message, Exception innerException) : base(message, innerException) { }
}
