// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2d456df8d52c82030dcf73a83cf343a2b67180c87b7355f07b5bdf6d06efde25
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A custom schema override was supplied but is not a JSON object.
/// </summary>
public class SchemaNotObjectException : ResolveErrorException
{
    public SchemaNotObjectException(string message) : base(message) { }

    public SchemaNotObjectException(string message, Exception innerException) : base(message, innerException) { }
}
