// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9fe3219c9b7cf84d6d158423156e931597f81e8f681c8eca21eb4d61143eb873
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A security policy was violated (e.g. zip bomb, oversized archive).
/// </summary>
public class SecurityException : XbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
