// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2220a59df36ea510d3469a47158e7b88a6b770d535e7c9867d372c4eec0d9ee9
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// JSON or MessagePack serialization/deserialization failed.
/// </summary>
public class SerializationException : XbergErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
