// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2514e619c5208e967ac765de5db3cb6219e21f9cdf743509b8e9491f488dec0e
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;
/// <summary>
/// Structured data type classification.
/// </summary>
[JsonConverter(typeof(StructuredDataTypeJsonConverter))]
public enum StructuredDataType
{
    /// <summary>
    /// JSON-LD structured data
    /// </summary>
    [JsonPropertyName("json-ld")]
    JsonLd,
    /// <summary>
    /// Microdata
    /// </summary>
    [JsonPropertyName("microdata")]
    Microdata,
    /// <summary>
    /// RDFa
    /// </summary>
    [JsonPropertyName("rdfa")]
    Rdfa,
}


/// <summary>
/// Custom JSON converter for <see cref="StructuredDataType"/> that respects explicit variant names.
/// </summary>
internal sealed class StructuredDataTypeJsonConverter : JsonConverter<StructuredDataType>
{
    public override StructuredDataType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "json-ld" => StructuredDataType.JsonLd,
            "microdata" => StructuredDataType.Microdata,
            "rdfa" => StructuredDataType.Rdfa,
            _ => throw new JsonException($"Unknown StructuredDataType value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, StructuredDataType value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            StructuredDataType.JsonLd => "json-ld",
            StructuredDataType.Microdata => "microdata",
            StructuredDataType.Rdfa => "rdfa",
            _ => throw new JsonException($"Unknown StructuredDataType value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
