// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b57e4fe2f0b6b3f87cc31948f8044214b899d1f74b9824554b63530f03797d77
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The extraction operation exceeded the configured time limit.
/// </summary>
public class TimeoutException : XbergErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
