// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f8d852bf3a08c808792f92fcbb646c24a6b190b1273d606f0d063f8a7de06678
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Invalid configuration or input parameters were supplied.
/// </summary>
public class ValidationException : XbergErrorException
{
    public ValidationException(string message) : base(message) { }

    public ValidationException(string message, Exception innerException) : base(message, innerException) { }
}
