// This file is auto-generated by alef. DO NOT EDIT.
#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace Xberg;

public static class XbergConverter {
  private static readonly JsonSerializerOptions JsonOptions =
      new() { Converters = { new JsonStringEnumConverter(
                  JsonNamingPolicy.SnakeCaseLower) },
              DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

  private static readonly JsonSerializerOptions JsonSerializationOptions =
      new() { Converters = { new JsonStringEnumConverter(
                  JsonNamingPolicy.SnakeCaseLower) },
              DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull };

  /// <summary>
  /// Classify a document's chunks and return the updated document.
  ///
  /// This owned form preserves the mutations when the document crosses a
  /// language-binding boundary. Rust callers that already own a mutable
  /// document can use `classify_chunks` to avoid moving it.
  /// </summary>
  /// <exception cref="XbergException">Returns the same validation and LLM
  /// errors as `classify_chunks`.</exception> <param name="result"></param>
  /// <param name="config"></param>
  public static async Task<ExtractedDocument>
  ClassifyChunksOwnedAsync(ExtractedDocument result,
                           ChunkClassificationConfig config) {
    ArgumentNullException.ThrowIfNull(result);
    ArgumentNullException.ThrowIfNull(config);
    var resultJson = JsonSerializer.Serialize(result, JsonSerializationOptions);
    var resultHandle = NativeMethods.ExtractedDocumentFromJson(resultJson);
    if (resultHandle == 0) {
      throw XbergException.FromLastError("ExtractedDocumentFromJson failed");
    }
    var configJson = JsonSerializer.Serialize(config, JsonSerializationOptions);
    var configHandle =
        NativeMethods.ChunkClassificationConfigFromJson(configJson);
    if (configHandle == 0) {
      throw XbergException.FromLastError(
          "ChunkClassificationConfigFromJson failed");
    }
    try {
      return await Task.Run(() => {
        var nativeResult =
            NativeMethods.ClassifyChunksOwned(resultHandle, configHandle);
        if (NativeMethods.LastErrorCode() != 0) {
          throw GetLastError();
        }
        var jsonPtr = NativeMethods.ExtractedDocumentToJson(nativeResult);
        var json =
            global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.ExtractedDocumentFree(nativeResult);
        var returnValue = JsonSerializer.Deserialize<ExtractedDocument>(
            json ?? "null", JsonOptions)!;
        return returnValue;
      });
    } finally {
      if (resultHandle != 0)
        NativeMethods.ExtractedDocumentFree(resultHandle);
      if (configHandle != 0)
        NativeMethods.ChunkClassificationConfigFree(configHandle);
    }
  }

  /// <summary>
  /// Probe the backends and settings in `config` and report what will actually
  /// execute on this host.
  ///
  /// Runs no downloads and no billable API calls. Backends that are not
  /// compiled in or whose models are not cached report `Skip` rather than
  /// failing.
  /// </summary>
  /// <param name="config"></param>
  public static DoctorReport Doctor(ExtractionConfig config) {
    ArgumentNullException.ThrowIfNull(config);
    var configJson = JsonSerializer.Serialize(config, JsonSerializationOptions);
    var configHandle = NativeMethods.ExtractionConfigFromJson(configJson);
    if (configHandle == 0) {
      throw XbergException.FromLastError("ExtractionConfigFromJson failed");
    }
    try {
      var nativeResult = NativeMethods.Doctor(configHandle);
      if (NativeMethods.LastErrorCode() != 0) {
        throw GetLastError();
      }
      var jsonPtr = NativeMethods.DoctorReportToJson(nativeResult);
      var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
          jsonPtr);
      NativeMethods.FreeString(jsonPtr);
      NativeMethods.DoctorReportFree(nativeResult);
      var returnValue = JsonSerializer.Deserialize<DoctorReport>(json ?? "null",
                                                                 JsonOptions)!;
      return returnValue;
    } finally {
      if (configHandle != 0)
        NativeMethods.ExtractionConfigFree(configHandle);
    }
  }

  /// <summary>
  /// Extract content from a single bytes or URI input.
  /// </summary>
  /// <param name="input"></param>
  /// <param name="config"></param>
  public static async Task<ExtractionResult>
  ExtractAsync(ExtractInput input, ExtractionConfig config) {
    ArgumentNullException.ThrowIfNull(input);
    ArgumentNullException.ThrowIfNull(config);
    var inputJson = JsonSerializer.Serialize(input, JsonSerializationOptions);
    var inputHandle = NativeMethods.ExtractInputFromJson(inputJson);
    if (inputHandle == 0) {
      throw XbergException.FromLastError("ExtractInputFromJson failed");
    }
    var configJson = JsonSerializer.Serialize(config, JsonSerializationOptions);
    var configHandle = NativeMethods.ExtractionConfigFromJson(configJson);
    if (configHandle == 0) {
      throw XbergException.FromLastError("ExtractionConfigFromJson failed");
    }
    try {
      return await Task.Run(() => {
        var nativeResult = NativeMethods.Extract(inputHandle, configHandle);
        if (NativeMethods.LastErrorCode() != 0) {
          throw GetLastError();
        }
        var jsonPtr = NativeMethods.ExtractionResultToJson(nativeResult);
        var json =
            global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.ExtractionResultFree(nativeResult);
        var returnValue = JsonSerializer.Deserialize<ExtractionResult>(
            json ?? "null", JsonOptions)!;
        return returnValue;
      });
    } finally {
      if (inputHandle != 0)
        NativeMethods.ExtractInputFree(inputHandle);
      if (configHandle != 0)
        NativeMethods.ExtractionConfigFree(configHandle);
    }
  }

  /// <summary>
  /// Extract content from multiple bytes or URI inputs.
  /// </summary>
  /// <param name="inputs"></param>
  /// <param name="config"></param>
  public static async Task<ExtractionResult>
  ExtractBatchAsync(List<ExtractInput> inputs, ExtractionConfig config) {
    ArgumentNullException.ThrowIfNull(config);
    var inputsJson = JsonSerializer.Serialize(inputs, JsonSerializationOptions);
    var inputsHandle =
        global::System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(
            inputsJson);
    var configJson = JsonSerializer.Serialize(config, JsonSerializationOptions);
    var configHandle = NativeMethods.ExtractionConfigFromJson(configJson);
    if (configHandle == 0) {
      throw XbergException.FromLastError("ExtractionConfigFromJson failed");
    }
    try {
      return await Task.Run(() => {
        var nativeResult =
            NativeMethods.ExtractBatch(inputsHandle, configHandle);
        if (NativeMethods.LastErrorCode() != 0) {
          throw GetLastError();
        }
        var jsonPtr = NativeMethods.ExtractionResultToJson(nativeResult);
        var json =
            global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.ExtractionResultFree(nativeResult);
        var returnValue = JsonSerializer.Deserialize<ExtractionResult>(
            json ?? "null", JsonOptions)!;
        return returnValue;
      });
    } finally {
      if (inputsHandle != global::System.IntPtr.Zero)
        global::System.Runtime.InteropServices.Marshal.FreeCoTaskMem(
            inputsHandle);
      if (configHandle != 0)
        NativeMethods.ExtractionConfigFree(configHandle);
    }
  }

  /// <summary>
  /// Find unmarked claims in markdown text.
  ///
  /// Returns lines that assert a claim but carry neither a footnote citation
  /// anchor (`[^...]`) nor an inference marker (`[*inference*]`).
  ///
  /// The heuristic is simple: a line that contains alphabetic words, ends with
  /// sentence punctuation, and is not a heading, blank line, or markup-only
  /// line is considered a claim. Exclude lines that appear in the citation
  /// block (after `---` + `&lt;!-- citations ... --&gt;`).
  /// </summary>
  /// <param name="markdown">The markdown text to search</param>
  ///
  /// <returns>A vector of trimmed line text strings for unmarked
  /// claims.</returns> <param name="markdown"></param>
  public static List<string> FindUnmarkedClaims(string markdown) {
    ArgumentNullException.ThrowIfNull(markdown);
    var nativeResult = NativeMethods.FindUnmarkedClaims(markdown);
    if (NativeMethods.LastErrorCode() != 0) {
      throw GetLastError();
    }
    var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
        nativeResult);
    NativeMethods.FreeString(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<List<string>>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// List names of all registered document extractors.
  /// </summary>
  public static List<string> ListDocumentExtractors() {
    var nativeResult = NativeMethods.ListDocumentExtractors();
    if (NativeMethods.LastErrorCode() != 0) {
      throw GetLastError();
    }
    var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
        nativeResult);
    NativeMethods.FreeString(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<List<string>>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// List the names of all registered embedding backends.
  ///
  /// Used by `xberg-cli`, the api/mcp endpoints, and generated language
  /// bindings.
  /// </summary>
  public static List<string> ListEmbeddingBackends() {
    var nativeResult = NativeMethods.ListEmbeddingBackends();
    if (NativeMethods.LastErrorCode() != 0) {
      throw GetLastError();
    }
    var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
        nativeResult);
    NativeMethods.FreeString(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<List<string>>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// List all registered OCR backends.
  ///
  /// Returns the names of all OCR backends currently registered in the global
  /// registry.
  /// </summary>
  /// <returns>A vector of OCR backend names.</returns>
  public static List<string> ListOcrBackends() {
    var nativeResult = NativeMethods.ListOcrBackends();
    if (NativeMethods.LastErrorCode() != 0) {
      throw GetLastError();
    }
    var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
        nativeResult);
    NativeMethods.FreeString(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<List<string>>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// List all registered post-processor names.
  ///
  /// Returns a vector of all post-processor names currently registered in the
  /// global registry.
  /// </summary>
  /// <returns>- `Ok(Vec&lt;String&gt;)` - Vector of post-processor names
  /// - `Err(...)` if the registry lock is poisoned</returns>
  public static List<string> ListPostProcessors() {
    var nativeResult = NativeMethods.ListPostProcessors();
    if (NativeMethods.LastErrorCode() != 0) {
      throw GetLastError();
    }
    var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
        nativeResult);
    NativeMethods.FreeString(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<List<string>>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// List names of all registered renderers.
  /// </summary>
  /// <exception cref="XbergException">Returns an error if the registry lock is
  /// poisoned.</exception>
  public static List<string> ListRenderers() {
    var nativeResult = NativeMethods.ListRenderers();
    if (NativeMethods.LastErrorCode() != 0) {
      throw GetLastError();
    }
    var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
        nativeResult);
    NativeMethods.FreeString(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<List<string>>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// List the names of all registered reranker backends.
  ///
  /// Used by `xberg-cli`, the api/mcp endpoints, and generated language
  /// bindings.
  /// </summary>
  public static List<string> ListRerankerBackends() {
    var nativeResult = NativeMethods.ListRerankerBackends();
    if (NativeMethods.LastErrorCode() != 0) {
      throw GetLastError();
    }
    var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
        nativeResult);
    NativeMethods.FreeString(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<List<string>>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// List all supported document formats.
  ///
  /// Returns every file extension Xberg recognizes together with its
  /// corresponding MIME type, derived from the central format registry.
  /// Formats that have no registered file extension (such as source code,
  /// which is detected dynamically) are not included.
  ///
  /// The static `EXT_TO_MIME` table lists every format the *codebase* knows how
  /// to describe, regardless of which Cargo features were compiled in.
  /// Advertising that table directly would claim support for extractors that
  /// may not exist in this build (see GH#1387). To keep the advertised
  /// catalogue honest, the table is intersected with the document extractor
  /// registry: an extension is only included if some registered extractor
  /// actually claims its MIME type in this build. This can never drift from
  /// reality and automatically covers third-party extractors registered at
  /// runtime.
  ///
  /// The list is sorted alphabetically by file extension.
  /// </summary>
  /// <returns>A vector of `SupportedFormat` entries sorted by extension,
  /// limited to formats with a registered extractor in this build.</returns>
  public static List<SupportedFormat> ListSupportedFormats() {
    var nativeResult = NativeMethods.ListSupportedFormats();
    if (NativeMethods.LastErrorCode() != 0) {
      throw GetLastError();
    }
    var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
        nativeResult);
    NativeMethods.FreeString(nativeResult);
    var returnValue = JsonSerializer.Deserialize<List<SupportedFormat>>(
        json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// List the names of all registered tokenizer backends.
  ///
  /// Used by `xberg-cli`, the api/mcp endpoints, and generated language
  /// bindings.
  /// </summary>
  public static List<string> ListTokenizerBackends() {
    var nativeResult = NativeMethods.ListTokenizerBackends();
    if (NativeMethods.LastErrorCode() != 0) {
      throw GetLastError();
    }
    var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
        nativeResult);
    NativeMethods.FreeString(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<List<string>>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// List names of all registered validators.
  /// </summary>
  public static List<string> ListValidators() {
    var nativeResult = NativeMethods.ListValidators();
    if (NativeMethods.LastErrorCode() != 0) {
      throw GetLastError();
    }
    var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
        nativeResult);
    NativeMethods.FreeString(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<List<string>>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Discover all pages and sitemaps reachable from `uri` without extracting
  /// document content.
  ///
  /// Builds a `crawlberg.CrawlEngine` from `config.crawl`, calls
  /// `CrawlEngine.map`, and returns the set of discovered URLs as a
  /// `crawlberg.MapResult` (re-exported as `MapResult`).
  ///
  /// Use this when you need the URL inventory of a site before committing to
  /// full document extraction — e.g. to build a crawl queue or validate scope.
  /// </summary>
  /// <exception cref="XbergException">Returns `Validation` if the crawl
  /// configuration fails validation or if the map operation itself
  /// fails.</exception> <param name="uri"></param> <param
  /// name="config"></param>
  public static async Task<MapResult> MapUrlAsync(string uri,
                                                  UrlExtractionConfig config) {
    ArgumentNullException.ThrowIfNull(uri);
    ArgumentNullException.ThrowIfNull(config);
    var configJson = JsonSerializer.Serialize(config, JsonSerializationOptions);
    var configHandle = NativeMethods.UrlExtractionConfigFromJson(configJson);
    if (configHandle == 0) {
      throw XbergException.FromLastError("UrlExtractionConfigFromJson failed");
    }
    try {
      return await Task.Run(() => {
        var nativeResult = NativeMethods.MapUrl(uri, configHandle);
        if (NativeMethods.LastErrorCode() != 0) {
          throw GetLastError();
        }
        var jsonPtr = NativeMethods.MapResultToJson(nativeResult);
        var json =
            global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.MapResultFree(nativeResult);
        var returnValue =
            JsonSerializer.Deserialize<MapResult>(json ?? "null", JsonOptions)!;
        return returnValue;
      });
    } finally {
      if (configHandle != 0)
        NativeMethods.UrlExtractionConfigFree(configHandle);
    }
  }

  /// <summary>
  /// Rank a set of documents against a query by MaxSim score, descending.
  ///
  /// Mirrors the sort/truncate shape of `crate.reranking`'s `build_results`,
  /// minus top-k truncation (callers slice the returned `Vec` themselves).
  ///
  /// Pure CPU primitive — available without ONNX Runtime.
  /// </summary>
  /// <param name="query"></param>
  /// <param name="docs"></param>
  public static List<LateInteractionMatch>
  MaxSimRank(MultiVectorEmbedding query, List<MultiVectorEmbedding> docs) {
    ArgumentNullException.ThrowIfNull(query);
    var queryJson = JsonSerializer.Serialize(query, JsonSerializationOptions);
    var queryHandle = NativeMethods.MultiVectorEmbeddingFromJson(queryJson);
    if (queryHandle == 0) {
      throw XbergException.FromLastError("MultiVectorEmbeddingFromJson failed");
    }
    var docsJson = JsonSerializer.Serialize(docs, JsonSerializationOptions);
    var docsHandle =
        global::System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(
            docsJson);
    try {
      var nativeResult = NativeMethods.MaxSimRank(queryHandle, docsHandle);
      if (NativeMethods.LastErrorCode() != 0) {
        throw GetLastError();
      }
      var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
          nativeResult);
      NativeMethods.FreeString(nativeResult);
      var returnValue = JsonSerializer.Deserialize<List<LateInteractionMatch>>(
          json ?? "null", JsonOptions)!;
      return returnValue;
    } finally {
      if (queryHandle != 0)
        NativeMethods.MultiVectorEmbeddingFree(queryHandle);
      if (docsHandle != global::System.IntPtr.Zero)
        global::System.Runtime.InteropServices.Marshal.FreeCoTaskMem(
            docsHandle);
    }
  }

  /// <summary>
  /// Score a query against a document using ColBERT's MaxSim operator: for each
  /// query token vector, take the maximum dot product against any document
  /// token vector, then sum across query tokens.
  ///
  /// Returns `0.0` if `query` and `doc` have mismatched dimensionality, if
  /// either has zero tokens, or if either is not well-formed per
  /// `MultiVectorEmbedding.is_well_formed` (its `data` length does not match
  /// `num_tokens * dim`).
  ///
  /// Pure CPU primitive — available without ONNX Runtime.
  /// </summary>
  /// <param name="query"></param>
  /// <param name="doc"></param>
  public static double MaxSimScore(MultiVectorEmbedding query,
                                   MultiVectorEmbedding doc) {
    ArgumentNullException.ThrowIfNull(query);
    ArgumentNullException.ThrowIfNull(doc);
    var queryJson = JsonSerializer.Serialize(query, JsonSerializationOptions);
    var queryHandle = NativeMethods.MultiVectorEmbeddingFromJson(queryJson);
    if (queryHandle == 0) {
      throw XbergException.FromLastError("MultiVectorEmbeddingFromJson failed");
    }
    var docJson = JsonSerializer.Serialize(doc, JsonSerializationOptions);
    var docHandle = NativeMethods.MultiVectorEmbeddingFromJson(docJson);
    if (docHandle == 0) {
      throw XbergException.FromLastError("MultiVectorEmbeddingFromJson failed");
    }
    try {
      var nativeResult = NativeMethods.MaxSimScore(queryHandle, docHandle);
      var returnValue = nativeResult;
      return returnValue;
    } finally {
      if (queryHandle != 0)
        NativeMethods.MultiVectorEmbeddingFree(queryHandle);
      if (docHandle != 0)
        NativeMethods.MultiVectorEmbeddingFree(docHandle);
    }
  }

  /// <summary>
  /// Verify that an excerpt appears verbatim in source text.
  ///
  /// Performs exact matching by default. Also tries whitespace-normalized
  /// matching (collapsing runs of whitespace on both sides) since PDF-extracted
  /// text often has irregular spacing.
  /// </summary>
  /// <param name="excerpt">The text snippet to find</param>
  ///
  /// <param name="source_text">The full source text to search</param>
  ///
  /// <returns>`true` if the excerpt appears (exactly or with normalized
  /// whitespace), `false` otherwise.</returns> <param name="excerpt"></param>
  /// <param name="sourceText"></param>
  public static bool VerifyExcerpt(string excerpt, string sourceText) {
    ArgumentNullException.ThrowIfNull(excerpt);
    ArgumentNullException.ThrowIfNull(sourceText);
    var nativeResult = NativeMethods.VerifyExcerpt(excerpt, sourceText);
    var returnValue = nativeResult != 0;
    return returnValue;
  }

  /// <summary>
  /// Default `Self.min_image_area`: 1000 px.
  ///
  /// Public and on the type rather than a free private `fn` because generated
  /// bindings have to call it to reproduce the default, and a private one is
  /// out of their reach.
  /// </summary>
  public static uint CaptioningConfigDefaultMinImageArea() {
    var nativeResult = NativeMethods.CaptioningConfigDefaultMinImageArea();
    var returnValue = nativeResult;
    return returnValue;
  }

  /// <summary>
  /// Default `Self.batch_size`: `DEFAULT_BATCH_SIZE`.
  ///
  /// Public and on the type rather than a free private `fn` because generated
  /// bindings have to call it to reproduce the default, and a private one is
  /// out of their reach.
  /// </summary>
  public static ulong ChunkClassificationConfigDefaultBatchSize() {
    var nativeResult =
        NativeMethods.ChunkClassificationConfigDefaultBatchSize();
    var returnValue = nativeResult;
    return returnValue;
  }

  /// <summary>
  /// Default `Self.max_concurrency`: `DEFAULT_MAX_CONCURRENCY`.
  ///
  /// Public and on the type rather than a free private `fn` because generated
  /// bindings have to call it to reproduce the default, and a private one is
  /// out of their reach.
  /// </summary>
  public static ulong ChunkClassificationConfigDefaultMaxConcurrency() {
    var nativeResult =
        NativeMethods.ChunkClassificationConfigDefaultMaxConcurrency();
    var returnValue = nativeResult;
    return returnValue;
  }

  /// <summary>
  /// A `ProbeStatus.Pass` verdict: the checked backend or setting will
  /// work as configured on this host.
  /// </summary>
  /// <param name="name"></param>
  /// <param name="message"></param>
  public static DoctorCheck DoctorCheckPass(string name, string message) {
    ArgumentNullException.ThrowIfNull(name);
    ArgumentNullException.ThrowIfNull(message);
    var nativeResult = NativeMethods.DoctorCheckPass(name, message);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.DoctorCheckToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.DoctorCheckFree(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<DoctorCheck>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// A `ProbeStatus.Warn` verdict: the check ran and found something
  /// actionable, but nothing is broken. Never fails the report.
  /// </summary>
  /// <param name="name"></param>
  /// <param name="message"></param>
  public static DoctorCheck DoctorCheckWarn(string name, string message) {
    ArgumentNullException.ThrowIfNull(name);
    ArgumentNullException.ThrowIfNull(message);
    var nativeResult = NativeMethods.DoctorCheckWarn(name, message);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.DoctorCheckToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.DoctorCheckFree(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<DoctorCheck>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// A `ProbeStatus.Fail` verdict: the configured setup will not work (or
  /// will silently degrade) on this host.
  /// </summary>
  /// <param name="name"></param>
  /// <param name="message"></param>
  public static DoctorCheck DoctorCheckFail(string name, string message) {
    ArgumentNullException.ThrowIfNull(name);
    ArgumentNullException.ThrowIfNull(message);
    var nativeResult = NativeMethods.DoctorCheckFail(name, message);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.DoctorCheckToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.DoctorCheckFree(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<DoctorCheck>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// A `ProbeStatus.Skip` verdict: the check cannot run locally; first
  /// real use decides, possibly after a download.
  /// </summary>
  /// <param name="name"></param>
  /// <param name="message"></param>
  public static DoctorCheck DoctorCheckSkip(string name, string message) {
    ArgumentNullException.ThrowIfNull(name);
    ArgumentNullException.ThrowIfNull(message);
    var nativeResult = NativeMethods.DoctorCheckSkip(name, message);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.DoctorCheckToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.DoctorCheckFree(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<DoctorCheck>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Whether no check failed. Warnings and skips do not count as failures,
  /// so the report stays usable as a scripting/CI gate.
  /// </summary>
  public static bool DoctorReportIsOk(ulong handle) {
    var nativeResult = NativeMethods.DoctorReportIsOk(handle);
    var returnValue = nativeResult != 0;
    return returnValue;
  }

  /// <summary>
  /// Compute and populate the `node_types` field from the current `nodes`.
  ///
  /// Call this after all nodes have been added to the structure. Internal
  /// construction paths (builder, derivation) call this automatically.
  /// </summary>
  public static void DocumentStructureFinalizeNodeTypes(ulong handle) {
    NativeMethods.DocumentStructureFinalizeNodeTypes(handle);
  }

  /// <summary>
  /// Check if the document structure is empty.
  /// </summary>
  public static bool DocumentStructureIsEmpty(ulong handle) {
    var nativeResult = NativeMethods.DocumentStructureIsEmpty(handle);
    var returnValue = nativeResult != 0;
    return returnValue;
  }

  /// <summary>
  /// Build a bytes input with a MIME type and optional filename hint.
  /// </summary>
  /// <param name="bytes"></param>
  /// <param name="mimeType"></param>
  /// <param name="filename">Optional.</param>
  public static ExtractInput
  ExtractInputFromBytes(byte[] bytes, string mimeType, string? filename) {
    ArgumentNullException.ThrowIfNull(bytes);
    ArgumentNullException.ThrowIfNull(mimeType);
    var bytesHandle = GCHandle.Alloc(bytes, GCHandleType.Pinned);
    var nativeResult = NativeMethods.ExtractInputFromBytes(
        bytesHandle.AddrOfPinnedObject(), (UIntPtr)bytes.Length, mimeType,
        filename!);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.ExtractInputToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.ExtractInputFree(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<ExtractInput>(json ?? "null", JsonOptions)!;
    if (bytesHandle.IsAllocated)
      bytesHandle.Free();
    return returnValue;
  }

  /// <summary>
  /// Build a URI input from a local path, `file://` URI, or HTTP(S) URL.
  /// </summary>
  /// <param name="uri"></param>
  public static ExtractInput ExtractInputFromUri(string uri) {
    ArgumentNullException.ThrowIfNull(uri);
    var nativeResult = NativeMethods.ExtractInputFromUri(uri);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.ExtractInputToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.ExtractInputFree(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<ExtractInput>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Default `Self.max_archive_depth`: 3 levels of nested archives.
  ///
  /// Public and on the type rather than a free private `fn` because generated
  /// bindings have to call it to reproduce the default, and a private one is
  /// out of their reach.
  /// </summary>
  public static ulong ExtractionConfigDefaultArchiveDepth() {
    var nativeResult = NativeMethods.ExtractionConfigDefaultArchiveDepth();
    var returnValue = nativeResult;
    return returnValue;
  }

  /// <summary>
  /// Default per-embedded-file cap: 50 MiB.
  ///
  /// A single embedded object larger than this can consume significant memory
  /// when the recursive extractor materialises it. 50 MiB is generous for
  /// real-world embedded documents while still bounding worst-case allocation.
  ///
  /// Public and on the type rather than a free private `fn` because generated
  /// bindings have to call it to reproduce the default, and a private one is
  /// out of their reach.
  /// </summary>
  public static ulong? ExtractionConfigDefaultMaxEmbeddedFileBytes() {
    if (NativeMethods.ExtractionConfigDefaultMaxEmbeddedFileBytesHasResult() !=
        1) {
      return (ulong?)null;
    }
    var nativeResult =
        NativeMethods.ExtractionConfigDefaultMaxEmbeddedFileBytes();
    var returnValue = nativeResult;
    return returnValue;
  }

  /// <summary>
  /// Default extraction timeout: 600 seconds (10 minutes).
  ///
  /// Pathological files (deeply nested archives, sheets with millions of cells,
  /// adversarial PDFs) can otherwise run indefinitely and exhaust caller
  /// resources. 600 s bounds the worst-case cost of a single untrusted input
  /// while giving legitimate but slow paths — VLM-based OCR, large scanned
  /// documents — enough headroom to finish instead of being cut off at the
  /// previous 60 s default.
  ///
  /// Public and on the type rather than a free private `fn` because generated
  /// bindings have to call it to reproduce the default, and a private one is
  /// out of their reach.
  /// </summary>
  public static ulong? ExtractionConfigDefaultExtractionTimeout() {
    if (NativeMethods.ExtractionConfigDefaultExtractionTimeoutHasResult() !=
        1) {
      return (ulong?)null;
    }
    var nativeResult = NativeMethods.ExtractionConfigDefaultExtractionTimeout();
    var returnValue = nativeResult;
    return returnValue;
  }

  /// <summary>
  /// Validate the configuration, returning an error if any settings are
  /// invalid.
  ///
  /// Checks:
  /// - `ocr`: backend name, VLM backend/model requirements, language codes, and
  /// the
  ///   `vlm_fallback` quality threshold.
  /// - `chunking`: `max_characters` is non-zero and `overlap` is smaller than
  /// it.
  ///   `topic_threshold`, when set, is a finite `[0.0, 1.0]` value.
  /// - `token_reduction`: `mode` is one of the recognized reduction levels.
  /// - `images`: `target_dpi`, `min_dpi`, and `max_dpi` are all positive and
  /// within the
  ///   supported range.
  /// - `language_detection`: `min_confidence` is a `[0.0, 1.0]` value.
  /// - `csv`: `delimiter`, when set, is exactly one ASCII character.
  /// - `keywords`: the n-gram range contains positive, ordered bounds and
  /// `min_score` is a
  ///   finite `[0.0, 1.0]` value.
  /// - `layout`: `confidence_threshold`, when set, is a finite `[0.0, 1.0]`
  /// value.
  /// - `redaction`: custom terms are non-empty and custom patterns compile.
  /// - `pdf_options`: hierarchy cluster counts and margin fractions are in
  /// their supported ranges.
  /// - every nested LLM config: sampling ranges and target-specific
  /// authentication support.
  ///
  /// Called automatically when a config is loaded from a file, built from a
  /// JSON override, or passed to the public `extract` and `extract_batch` entry
  /// points. Call this method explicitly before passing a typed config to
  /// lower-level processing APIs.
  /// </summary>
  /// <exception cref="XbergException">Returns `XbergError.Validation`
  /// describing the first invalid setting found.</exception>
  public static void ExtractionConfigValidate(ulong handle) {
    NativeMethods.ExtractionConfigValidate(handle);
  }

  /// <summary>
  /// Check if image processing is needed by examining OCR and image extraction
  /// settings.
  ///
  /// Returns `true` if either OCR is enabled or image extraction is configured,
  /// indicating that image decompression and processing should occur.
  /// Returns `false` if both are disabled, allowing optimization to skip
  /// unnecessary image decompression for text-only extraction workflows.
  ///
  /// # Optimization Impact
  /// For text-only extractions (no OCR, no image extraction), skipping image
  /// decompression can improve CPU utilization by 5-10% by avoiding wasteful
  /// image I/O and processing when results won't be used.
  /// Returns `true` when image binary data should be extracted.
  ///
  /// True when `config.images.extract_images` is set, captioning is configured,
  /// or QR-code detection is enabled. Captioning and QR-code detection both
  /// require image bytes regardless of whether the caller also requested image
  /// extraction.
  /// </summary>
  public static bool ExtractionConfigNeedsImageData(ulong handle) {
    var nativeResult = NativeMethods.ExtractionConfigNeedsImageData(handle);
    var returnValue = nativeResult != 0;
    return returnValue;
  }

  /// <summary>
  /// Returns `true` when any image processing is needed during extraction.
  ///
  /// # Optimization Impact
  ///
  /// For text-only extractions (no OCR, no image extraction, no captioning),
  /// skipping image decompression can improve CPU utilization by 5-10% by
  /// avoiding wasteful image I/O and processing when results won't be used.
  /// </summary>
  public static bool ExtractionConfigNeedsImageProcessing(ulong handle) {
    var nativeResult =
        NativeMethods.ExtractionConfigNeedsImageProcessing(handle);
    var returnValue = nativeResult != 0;
    return returnValue;
  }

  /// <summary>
  /// Build an output containing one successful result.
  /// </summary>
  /// <param name="result"></param>
  public static ExtractionResult
  ExtractionResultSingle(ExtractedDocument result) {
    ArgumentNullException.ThrowIfNull(result);
    var resultJson = JsonSerializer.Serialize(result, JsonSerializationOptions);
    var resultHandle = NativeMethods.ExtractedDocumentFromJson(resultJson);
    if (resultHandle == 0) {
      throw XbergException.FromLastError("ExtractedDocumentFromJson failed");
    }
    var nativeResult = NativeMethods.ExtractionResultSingle(resultHandle);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.ExtractionResultToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.ExtractionResultFree(nativeResult);
    var returnValue = JsonSerializer.Deserialize<ExtractionResult>(
        json ?? "null", JsonOptions)!;
    if (resultHandle != 0)
      NativeMethods.ExtractedDocumentFree(resultHandle);
    return returnValue;
  }

  /// <summary>
  /// Set whether to parse the citation block.
  /// </summary>
  /// <param name="enabled"></param>
  public static FootnoteConfig FootnoteConfigWithParseCitations(ulong handle,
                                                                bool enabled) {
    var nativeResult = NativeMethods.FootnoteConfigWithParseCitations(
        handle, (enabled ? 1 : 0));
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.FootnoteConfigToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.FootnoteConfigFree(nativeResult);
    var returnValue = JsonSerializer.Deserialize<FootnoteConfig>(json ?? "null",
                                                                 JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Validate the configuration.
  /// </summary>
  /// <exception cref="XbergException">Returns `HeuristicsError.ConfigError`
  /// when:
  /// - `target_pages_per_chunk` is 0
  /// - `max_pages_per_chunk` &lt; `target_pages_per_chunk`
  /// - `file_size_threshold_bytes` is 0</exception>
  public static void HeuristicsConfigValidate(ulong handle) {
    NativeMethods.HeuristicsConfigValidate(handle);
  }

  /// <summary>
  /// Validate the request-time sampling parameters that have a documented
  /// range: `top_p` (`[0.0, 1.0]`), `presence_penalty`, and `frequency_penalty`
  /// (both
  /// `[-2.0, 2.0]`, matching liter-llm's/OpenAI's semantics). An unset field is
  /// always valid — silence in config should never be rejected.
  ///
  /// Called from `llm.client.build_client_config` before a liter-llm
  /// client is built from this config, alongside the existing
  /// `validate_cache_backend` check in that function.
  /// </summary>
  public static void LlmConfigValidate(ulong handle) {
    NativeMethods.LlmConfigValidate(handle);
  }

  /// <summary>
  /// Returns `true` when no metadata fields, format-specific metadata, or
  /// additional postprocessor fields are populated.
  /// </summary>
  public static bool MetadataIsEmpty(ulong handle) {
    var nativeResult = NativeMethods.MetadataIsEmpty(handle);
    var returnValue = nativeResult != 0;
    return returnValue;
  }

  /// <summary>
  /// Returns `true` if `data` holds exactly `num_tokens * dim` values — i.e.
  /// the flat buffer matches the declared shape.
  ///
  /// All fields are `pub` and the type is `Deserialize`, so a value coming
  /// from an untrusted source (FFI caller, JSON, a store row) may be
  /// malformed. `max_sim_score` guards on this so a length-mismatched
  /// buffer scores `0.0` rather than silently mis-scoring (a shorter `data`
  /// would make `rows`' `chunks_exact` drop a trailing partial
  /// chunk). Uses `checked_mul` so an overflowing `num_tokens * dim` is
  /// reported as malformed instead of wrapping.
  /// </summary>
  public static bool MultiVectorEmbeddingIsWellFormed(ulong handle) {
    var nativeResult = NativeMethods.MultiVectorEmbeddingIsWellFormed(handle);
    var returnValue = nativeResult != 0;
    return returnValue;
  }

  /// <summary>
  /// Sets a custom Hugging Face Hub cache root for model files.
  /// </summary>
  /// <param name="path">Path to cache directory</param>
  /// <param name="path"></param>
  public static PaddleOcrConfig PaddleOcrConfigWithCacheDir(ulong handle,
                                                            string path) {
    var nativeResult = NativeMethods.PaddleOcrConfigWithCacheDir(handle, path);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.PaddleOcrConfigToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.PaddleOcrConfigFree(nativeResult);
    var returnValue = JsonSerializer.Deserialize<PaddleOcrConfig>(
        json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Enables or disables table structure detection.
  /// </summary>
  /// <param name="enable">Whether to enable table detection</param>
  /// <param name="enable"></param>
  public static PaddleOcrConfig PaddleOcrConfigWithTableDetection(ulong handle,
                                                                  bool enable) {
    var nativeResult = NativeMethods.PaddleOcrConfigWithTableDetection(
        handle, (enable ? 1 : 0));
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.PaddleOcrConfigToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.PaddleOcrConfigFree(nativeResult);
    var returnValue = JsonSerializer.Deserialize<PaddleOcrConfig>(
        json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Enables or disables angle classification for rotated text.
  /// </summary>
  /// <param name="enable">Whether to enable angle classification</param>
  /// <param name="enable"></param>
  public static PaddleOcrConfig PaddleOcrConfigWithAngleCls(ulong handle,
                                                            bool enable) {
    var nativeResult =
        NativeMethods.PaddleOcrConfigWithAngleCls(handle, (enable ? 1 : 0));
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.PaddleOcrConfigToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.PaddleOcrConfigFree(nativeResult);
    var returnValue = JsonSerializer.Deserialize<PaddleOcrConfig>(
        json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Sets the database threshold for text detection.
  /// </summary>
  /// <param name="threshold">Detection threshold (0.0-1.0)</param>
  /// <param name="threshold"></param>
  public static PaddleOcrConfig
  PaddleOcrConfigWithDetDbThresh(ulong handle, float threshold) {
    var nativeResult =
        NativeMethods.PaddleOcrConfigWithDetDbThresh(handle, threshold);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.PaddleOcrConfigToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.PaddleOcrConfigFree(nativeResult);
    var returnValue = JsonSerializer.Deserialize<PaddleOcrConfig>(
        json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Sets the box threshold for text bounding box refinement.
  /// </summary>
  /// <param name="threshold">Box threshold (0.0-1.0)</param>
  /// <param name="threshold"></param>
  public static PaddleOcrConfig
  PaddleOcrConfigWithDetDbBoxThresh(ulong handle, float threshold) {
    var nativeResult =
        NativeMethods.PaddleOcrConfigWithDetDbBoxThresh(handle, threshold);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.PaddleOcrConfigToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.PaddleOcrConfigFree(nativeResult);
    var returnValue = JsonSerializer.Deserialize<PaddleOcrConfig>(
        json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Sets the unclip ratio for expanding text bounding boxes.
  /// </summary>
  /// <param name="ratio">Unclip ratio (typically 1.5-2.0)</param>
  /// <param name="ratio"></param>
  public static PaddleOcrConfig
  PaddleOcrConfigWithDetDbUnclipRatio(ulong handle, float ratio) {
    var nativeResult =
        NativeMethods.PaddleOcrConfigWithDetDbUnclipRatio(handle, ratio);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.PaddleOcrConfigToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.PaddleOcrConfigFree(nativeResult);
    var returnValue = JsonSerializer.Deserialize<PaddleOcrConfig>(
        json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Sets the maximum side length for detection images.
  /// </summary>
  /// <param name="length">Maximum side length in pixels</param>
  /// <param name="length"></param>
  public static PaddleOcrConfig
  PaddleOcrConfigWithDetLimitSideLen(ulong handle, uint length) {
    var nativeResult =
        NativeMethods.PaddleOcrConfigWithDetLimitSideLen(handle, length);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.PaddleOcrConfigToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.PaddleOcrConfigFree(nativeResult);
    var returnValue = JsonSerializer.Deserialize<PaddleOcrConfig>(
        json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Sets the batch size for recognition inference.
  /// </summary>
  /// <param name="batch_size">Number of text regions to process
  /// simultaneously</param> <param name="batchSize"></param>
  public static PaddleOcrConfig PaddleOcrConfigWithRecBatchNum(ulong handle,
                                                               uint batchSize) {
    var nativeResult =
        NativeMethods.PaddleOcrConfigWithRecBatchNum(handle, batchSize);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.PaddleOcrConfigToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.PaddleOcrConfigFree(nativeResult);
    var returnValue = JsonSerializer.Deserialize<PaddleOcrConfig>(
        json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Sets the minimum recognition confidence threshold.
  /// </summary>
  /// <param name="score">Minimum confidence (0.0-1.0), text below this is
  /// dropped</param> <param name="score"></param>
  public static PaddleOcrConfig PaddleOcrConfigWithDropScore(ulong handle,
                                                             float score) {
    var nativeResult =
        NativeMethods.PaddleOcrConfigWithDropScore(handle, score);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.PaddleOcrConfigToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.PaddleOcrConfigFree(nativeResult);
    var returnValue = JsonSerializer.Deserialize<PaddleOcrConfig>(
        json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Sets padding in pixels added around images before detection.
  /// </summary>
  /// <param name="padding">Padding in pixels (0-100)</param>
  /// <param name="padding"></param>
  public static PaddleOcrConfig PaddleOcrConfigWithPadding(ulong handle,
                                                           uint padding) {
    var nativeResult =
        NativeMethods.PaddleOcrConfigWithPadding(handle, padding);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.PaddleOcrConfigToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.PaddleOcrConfigFree(nativeResult);
    var returnValue = JsonSerializer.Deserialize<PaddleOcrConfig>(
        json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Sets the model tier controlling detection/recognition model size.
  /// </summary>
  /// <param name="tier">`"mobile"` (default, lightweight, faster) or `"server"`
  /// (high accuracy, GPU/complex documents)</param> <param name="tier"></param>
  public static PaddleOcrConfig PaddleOcrConfigWithModelTier(ulong handle,
                                                             string tier) {
    ArgumentNullException.ThrowIfNull(tier);
    var nativeResult = NativeMethods.PaddleOcrConfigWithModelTier(handle, tier);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.PaddleOcrConfigToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.PaddleOcrConfigFree(nativeResult);
    var returnValue = JsonSerializer.Deserialize<PaddleOcrConfig>(
        json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Sets the model generation.
  /// </summary>
  /// <param name="version">`"pp-ocrv6"` (default) or `"pp-ocrv5"`. Under
  /// `"pp-ocrv6"`, `model_tier` selects among
  /// `"medium"`/`"small"`/`"tiny"`.</param> <param name="version"></param>
  public static PaddleOcrConfig
  PaddleOcrConfigWithModelVersion(ulong handle, string version) {
    ArgumentNullException.ThrowIfNull(version);
    var nativeResult =
        NativeMethods.PaddleOcrConfigWithModelVersion(handle, version);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.PaddleOcrConfigToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.PaddleOcrConfigFree(nativeResult);
    var returnValue = JsonSerializer.Deserialize<PaddleOcrConfig>(
        json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Get the number of pages in this range.
  /// </summary>
  public static uint PageRangePageCount(ulong handle) {
    var nativeResult = NativeMethods.PageRangePageCount(handle);
    var returnValue = nativeResult;
    return returnValue;
  }

  /// <summary>
  /// Derive signals from raw page text.
  ///
  /// Callers that already have structured per-page data (e.g. from a PDF
  /// extractor) can set individual fields directly.  This constructor is for
  /// callers that only have the plain-text content of a page (e.g. from
  /// `PageContent`).
  /// </summary>
  /// <param name="page_number">— 1-indexed page number.</param>
  ///
  /// <param name="text">— Full extracted text for the page.</param>
  ///
  /// <param name="layout_text_density">— Pre-computed text density in
  /// `[0.0, 1.0]`.  Pass `0.0` when unknown (disables density-shift detection
  /// for this page). # Heuristics All signal derivations are *conservative
  /// starting points*.  Each is documented inline.  They err on the side of
  /// fewer false positives; tune thresholds via `MultidocThresholds` rather
  /// than by changing these heuristics.</param> <param
  /// name="pageNumber"></param> <param name="text"></param> <param
  /// name="layoutTextDensity"></param>
  public static PageSignals PageSignalsFromPageText(uint pageNumber,
                                                    string text,
                                                    float layoutTextDensity) {
    ArgumentNullException.ThrowIfNull(text);
    var nativeResult = NativeMethods.PageSignalsFromPageText(pageNumber, text,
                                                             layoutTextDensity);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.PageSignalsToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.PageSignalsFree(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<PageSignals>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Validate PDF-specific extraction settings.
  /// </summary>
  /// <exception cref="XbergException">Returns `Validation` when a configured
  /// page margin is non-finite or outside `[0.0, 1.0]`, when hierarchy
  /// clustering requests fewer than one or more than seven clusters, or when an
  /// enabled option is unavailable in the current feature set.</exception>
  public static void PdfConfigValidate(ulong handle) {
    NativeMethods.PdfConfigValidate(handle);
  }

  /// <summary>
  /// Validate user-supplied terms and patterns at config-construction time.
  ///
  /// Compiles every `RedactionPattern.pattern` (with the case-insensitive
  /// inline flag where applicable) and returns the first compilation error so
  /// the caller can reject the config before the redaction pipeline runs.
  /// Pure terms (regex-escaped) cannot fail to compile, but the function
  /// still rejects empty values to avoid degenerate zero-length matches.
  /// </summary>
  public static void RedactionConfigValidate(ulong handle) {
    NativeMethods.RedactionConfigValidate(handle);
  }

  /// <summary>
  /// Build a pattern with the given label (case-insensitive by default).
  /// </summary>
  /// <param name="label"></param>
  /// <param name="pattern"></param>
  public static RedactionPattern RedactionPatternLabeled(string label,
                                                         string pattern) {
    ArgumentNullException.ThrowIfNull(label);
    ArgumentNullException.ThrowIfNull(pattern);
    var nativeResult = NativeMethods.RedactionPatternLabeled(label, pattern);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.RedactionPatternToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.RedactionPatternFree(nativeResult);
    var returnValue = JsonSerializer.Deserialize<RedactionPattern>(
        json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Build a term whose label is the literal value itself (case-insensitive).
  /// </summary>
  /// <param name="value"></param>
  public static RedactionTerm RedactionTermLiteral(string value) {
    ArgumentNullException.ThrowIfNull(value);
    var nativeResult = NativeMethods.RedactionTermLiteral(value);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.RedactionTermToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.RedactionTermFree(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<RedactionTerm>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Build a term with a custom label.
  /// </summary>
  /// <param name="label"></param>
  /// <param name="value"></param>
  public static RedactionTerm RedactionTermLabeled(string label, string value) {
    ArgumentNullException.ThrowIfNull(label);
    ArgumentNullException.ThrowIfNull(value);
    var nativeResult = NativeMethods.RedactionTermLabeled(label, value);
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.RedactionTermToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.RedactionTermFree(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<RedactionTerm>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>
  /// Get the server listen address (host:port).
  /// </summary>
  public static string ServerConfigListenAddr(ulong handle) {
    var nativeResult = NativeMethods.ServerConfigListenAddr(handle);
    if (nativeResult == IntPtr.Zero) {
      throw GetLastError();
    }
    var returnValue =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
            nativeResult) ??
        string.Empty;
    NativeMethods.FreeString(nativeResult);
    return returnValue;
  }

  /// <summary>
  /// Check if CORS allows all origins.
  ///
  /// Returns `true` if the `cors_origins` vector is empty, meaning all origins
  /// are allowed. Returns `false` if specific origins are configured.
  /// </summary>
  public static bool ServerConfigCorsAllowsAll(ulong handle) {
    var nativeResult = NativeMethods.ServerConfigCorsAllowsAll(handle);
    var returnValue = nativeResult != 0;
    return returnValue;
  }

  /// <summary>
  /// Check if a given origin is allowed by CORS configuration.
  ///
  /// Returns `true` if:
  /// - CORS allows all origins (empty origins list), or
  /// - The given origin is in the allowed origins list
  /// </summary>
  /// <param name="origin">The origin to check (e.g.,
  /// "&lt;https://example.com&gt;")</param> <param name="origin"></param>
  public static bool ServerConfigIsOriginAllowed(ulong handle, string origin) {
    ArgumentNullException.ThrowIfNull(origin);
    var nativeResult =
        NativeMethods.ServerConfigIsOriginAllowed(handle, origin);
    var returnValue = nativeResult != 0;
    return returnValue;
  }

  /// <summary>
  /// Get maximum request body size in megabytes (rounded up).
  /// </summary>
  public static ulong ServerConfigMaxRequestBodyMb(ulong handle) {
    var nativeResult = NativeMethods.ServerConfigMaxRequestBodyMb(handle);
    var returnValue = nativeResult;
    return returnValue;
  }

  /// <summary>
  /// Get maximum multipart field size in megabytes (rounded up).
  /// </summary>
  public static ulong ServerConfigMaxMultipartFieldMb(ulong handle) {
    var nativeResult = NativeMethods.ServerConfigMaxMultipartFieldMb(handle);
    var returnValue = nativeResult;
    return returnValue;
  }

  /// <summary>
  /// Default `Self.schema_name` passed to the LLM's structured-output mode.
  ///
  /// Public and on the type rather than a free private `fn` because generated
  /// bindings have to call it to reproduce the default, and a private one is
  /// out of their reach.
  /// </summary>
  public static string StructuredExtractionConfigDefaultSchemaName() {
    var nativeResult =
        NativeMethods.StructuredExtractionConfigDefaultSchemaName();
    if (nativeResult == IntPtr.Zero) {
      throw GetLastError();
    }
    var returnValue =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
            nativeResult) ??
        string.Empty;
    NativeMethods.FreeString(nativeResult);
    return returnValue;
  }

  /// <summary>
  /// Default `Self.crawl` policy.
  ///
  /// Public and on the type rather than a free private `fn` because generated
  /// bindings have to call it to reproduce the default, and a private one is
  /// out of their reach.
  /// </summary>
  public static CrawlConfig UrlExtractionConfigDefaultXbergCrawlConfig() {
    var nativeResult =
        NativeMethods.UrlExtractionConfigDefaultXbergCrawlConfig();
    if (nativeResult == 0) {
      throw GetLastError();
    }
    var jsonPtr = NativeMethods.CrawlConfigToJson(nativeResult);
    var json =
        global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
    NativeMethods.FreeString(jsonPtr);
    NativeMethods.CrawlConfigFree(nativeResult);
    var returnValue =
        JsonSerializer.Deserialize<CrawlConfig>(json ?? "null", JsonOptions)!;
    return returnValue;
  }

  /// <summary>Complete native registration of a OcrBackend
  /// implementation</summary>
  public static void RegisterOcrBackend(IntPtr handle) {
    if (handle == IntPtr.Zero)
      throw new ArgumentException("handle is null");
    var bridge = GCHandle.FromIntPtr(handle).Target as OcrBackendBridge ??
                 throw new InvalidOperationException("Invalid bridge handle");
    var impl =
        bridge.GetType()
            .GetField("_impl", System.Reflection.BindingFlags.NonPublic |
                                   System.Reflection.BindingFlags.Instance)
            ?.GetValue(bridge) as IOcrBackend;
    if (impl == null)
      throw new InvalidOperationException("Cannot extract impl from bridge");
    var name = impl.Name;
    var ec = NativeMethods.RegisterOcrBackend(name, bridge._vtable, handle,
                                              out var outError);
    if (ec != 0) {
      var msg = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                    outError) ??
                "Register failed";
      throw new XbergException(ec, msg);
    }
  }
  /// <summary>Unregister a OcrBackend implementation by name</summary>
  public static void UnregisterOcrBackend(string name) {
    ArgumentNullException.ThrowIfNull(name);
    var ec = NativeMethods.UnregisterOcrBackend(name, out var outError);
    if (ec != 0) {
      var msg = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                    outError) ??
                "Unregister failed";
      throw new XbergException(ec, msg);
    }
  }
  /// <summary>Complete native registration of a PostProcessor
  /// implementation</summary>
  public static void RegisterPostProcessor(IntPtr handle) {
    if (handle == IntPtr.Zero)
      throw new ArgumentException("handle is null");
    var bridge = GCHandle.FromIntPtr(handle).Target as PostProcessorBridge ??
                 throw new InvalidOperationException("Invalid bridge handle");
    var impl =
        bridge.GetType()
            .GetField("_impl", System.Reflection.BindingFlags.NonPublic |
                                   System.Reflection.BindingFlags.Instance)
            ?.GetValue(bridge) as IPostProcessor;
    if (impl == null)
      throw new InvalidOperationException("Cannot extract impl from bridge");
    var name = impl.Name;
    var ec = NativeMethods.RegisterPostProcessor(name, bridge._vtable, handle,
                                                 out var outError);
    if (ec != 0) {
      var msg = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                    outError) ??
                "Register failed";
      throw new XbergException(ec, msg);
    }
  }
  /// <summary>Unregister a PostProcessor implementation by name</summary>
  public static void UnregisterPostProcessor(string name) {
    ArgumentNullException.ThrowIfNull(name);
    var ec = NativeMethods.UnregisterPostProcessor(name, out var outError);
    if (ec != 0) {
      var msg = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                    outError) ??
                "Unregister failed";
      throw new XbergException(ec, msg);
    }
  }
  /// <summary>Complete native registration of a Validator
  /// implementation</summary>
  public static void RegisterValidator(IntPtr handle) {
    if (handle == IntPtr.Zero)
      throw new ArgumentException("handle is null");
    var bridge = GCHandle.FromIntPtr(handle).Target as ValidatorBridge ??
                 throw new InvalidOperationException("Invalid bridge handle");
    var impl =
        bridge.GetType()
            .GetField("_impl", System.Reflection.BindingFlags.NonPublic |
                                   System.Reflection.BindingFlags.Instance)
            ?.GetValue(bridge) as IValidator;
    if (impl == null)
      throw new InvalidOperationException("Cannot extract impl from bridge");
    var name = impl.Name;
    var ec = NativeMethods.RegisterValidator(name, bridge._vtable, handle,
                                             out var outError);
    if (ec != 0) {
      var msg = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                    outError) ??
                "Register failed";
      throw new XbergException(ec, msg);
    }
  }
  /// <summary>Unregister a Validator implementation by name</summary>
  public static void UnregisterValidator(string name) {
    ArgumentNullException.ThrowIfNull(name);
    var ec = NativeMethods.UnregisterValidator(name, out var outError);
    if (ec != 0) {
      var msg = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                    outError) ??
                "Unregister failed";
      throw new XbergException(ec, msg);
    }
  }
  /// <summary>Complete native registration of a DocumentExtractor
  /// implementation</summary>
  public static void RegisterDocumentExtractor(IntPtr handle) {
    if (handle == IntPtr.Zero)
      throw new ArgumentException("handle is null");
    var bridge =
        GCHandle.FromIntPtr(handle).Target as DocumentExtractorBridge ??
        throw new InvalidOperationException("Invalid bridge handle");
    var impl =
        bridge.GetType()
            .GetField("_impl", System.Reflection.BindingFlags.NonPublic |
                                   System.Reflection.BindingFlags.Instance)
            ?.GetValue(bridge) as IDocumentExtractor;
    if (impl == null)
      throw new InvalidOperationException("Cannot extract impl from bridge");
    var name = impl.Name;
    var ec = NativeMethods.RegisterDocumentExtractor(name, bridge._vtable,
                                                     handle, out var outError);
    if (ec != 0) {
      var msg = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                    outError) ??
                "Register failed";
      throw new XbergException(ec, msg);
    }
  }
  /// <summary>Unregister a DocumentExtractor implementation by name</summary>
  public static void UnregisterDocumentExtractor(string name) {
    ArgumentNullException.ThrowIfNull(name);
    var ec = NativeMethods.UnregisterDocumentExtractor(name, out var outError);
    if (ec != 0) {
      var msg = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                    outError) ??
                "Unregister failed";
      throw new XbergException(ec, msg);
    }
  }
  /// <summary>Complete native registration of a EmbeddingBackend
  /// implementation</summary>
  public static void RegisterEmbeddingBackend(IntPtr handle) {
    if (handle == IntPtr.Zero)
      throw new ArgumentException("handle is null");
    var bridge = GCHandle.FromIntPtr(handle).Target as EmbeddingBackendBridge ??
                 throw new InvalidOperationException("Invalid bridge handle");
    var impl =
        bridge.GetType()
            .GetField("_impl", System.Reflection.BindingFlags.NonPublic |
                                   System.Reflection.BindingFlags.Instance)
            ?.GetValue(bridge) as IEmbeddingBackend;
    if (impl == null)
      throw new InvalidOperationException("Cannot extract impl from bridge");
    var name = impl.Name;
    var ec = NativeMethods.RegisterEmbeddingBackend(name, bridge._vtable,
                                                    handle, out var outError);
    if (ec != 0) {
      var msg = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                    outError) ??
                "Register failed";
      throw new XbergException(ec, msg);
    }
  }
  /// <summary>Unregister a EmbeddingBackend implementation by name</summary>
  public static void UnregisterEmbeddingBackend(string name) {
    ArgumentNullException.ThrowIfNull(name);
    var ec = NativeMethods.UnregisterEmbeddingBackend(name, out var outError);
    if (ec != 0) {
      var msg = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                    outError) ??
                "Unregister failed";
      throw new XbergException(ec, msg);
    }
  }
  /// <summary>Complete native registration of a Renderer
  /// implementation</summary>
  public static void RegisterRenderer(IntPtr handle) {
    if (handle == IntPtr.Zero)
      throw new ArgumentException("handle is null");
    var bridge = GCHandle.FromIntPtr(handle).Target as RendererBridge ??
                 throw new InvalidOperationException("Invalid bridge handle");
    var impl =
        bridge.GetType()
            .GetField("_impl", System.Reflection.BindingFlags.NonPublic |
                                   System.Reflection.BindingFlags.Instance)
            ?.GetValue(bridge) as IRenderer;
    if (impl == null)
      throw new InvalidOperationException("Cannot extract impl from bridge");
    var name = impl.Name;
    var ec = NativeMethods.RegisterRenderer(name, bridge._vtable, handle,
                                            out var outError);
    if (ec != 0) {
      var msg = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                    outError) ??
                "Register failed";
      throw new XbergException(ec, msg);
    }
  }
  /// <summary>Unregister a Renderer implementation by name</summary>
  public static void UnregisterRenderer(string name) {
    ArgumentNullException.ThrowIfNull(name);
    var ec = NativeMethods.UnregisterRenderer(name, out var outError);
    if (ec != 0) {
      var msg = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                    outError) ??
                "Unregister failed";
      throw new XbergException(ec, msg);
    }
  }
  /// <summary>Complete native registration of a RerankerBackend
  /// implementation</summary>
  public static void RegisterRerankerBackend(IntPtr handle) {
    if (handle == IntPtr.Zero)
      throw new ArgumentException("handle is null");
    var bridge = GCHandle.FromIntPtr(handle).Target as RerankerBackendBridge ??
                 throw new InvalidOperationException("Invalid bridge handle");
    var impl =
        bridge.GetType()
            .GetField("_impl", System.Reflection.BindingFlags.NonPublic |
                                   System.Reflection.BindingFlags.Instance)
            ?.GetValue(bridge) as IRerankerBackend;
    if (impl == null)
      throw new InvalidOperationException("Cannot extract impl from bridge");
    var name = impl.Name;
    var ec = NativeMethods.RegisterRerankerBackend(name, bridge._vtable, handle,
                                                   out var outError);
    if (ec != 0) {
      var msg = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                    outError) ??
                "Register failed";
      throw new XbergException(ec, msg);
    }
  }
  /// <summary>Unregister a RerankerBackend implementation by name</summary>
  public static void UnregisterRerankerBackend(string name) {
    ArgumentNullException.ThrowIfNull(name);
    var ec = NativeMethods.UnregisterRerankerBackend(name, out var outError);
    if (ec != 0) {
      var msg = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                    outError) ??
                "Unregister failed";
      throw new XbergException(ec, msg);
    }
  }
  /// <summary>Complete native registration of a TokenizerBackend
  /// implementation</summary>
  public static void RegisterTokenizerBackend(IntPtr handle) {
    if (handle == IntPtr.Zero)
      throw new ArgumentException("handle is null");
    var bridge = GCHandle.FromIntPtr(handle).Target as TokenizerBackendBridge ??
                 throw new InvalidOperationException("Invalid bridge handle");
    var impl =
        bridge.GetType()
            .GetField("_impl", System.Reflection.BindingFlags.NonPublic |
                                   System.Reflection.BindingFlags.Instance)
            ?.GetValue(bridge) as ITokenizerBackend;
    if (impl == null)
      throw new InvalidOperationException("Cannot extract impl from bridge");
    var name = impl.Name;
    var ec = NativeMethods.RegisterTokenizerBackend(name, bridge._vtable,
                                                    handle, out var outError);
    if (ec != 0) {
      var msg = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                    outError) ??
                "Register failed";
      throw new XbergException(ec, msg);
    }
  }
  /// <summary>Unregister a TokenizerBackend implementation by name</summary>
  public static void UnregisterTokenizerBackend(string name) {
    ArgumentNullException.ThrowIfNull(name);
    var ec = NativeMethods.UnregisterTokenizerBackend(name, out var outError);
    if (ec != 0) {
      var msg = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(
                    outError) ??
                "Unregister failed";
      throw new XbergException(ec, msg);
    }
  }
  /// <summary>Clear all registered OcrBackend implementations</summary>
  public static void ClearOcrBackends() { OcrBackendRegistry.Clear(); }
  /// <summary>Clear all registered PostProcessor implementations</summary>
  public static void ClearPostProcessors() { PostProcessorRegistry.Clear(); }
  /// <summary>Clear all registered Validator implementations</summary>
  public static void ClearValidators() { ValidatorRegistry.Clear(); }
  /// <summary>Clear all registered DocumentExtractor implementations</summary>
  public static void ClearDocumentExtractors() {
    DocumentExtractorRegistry.Clear();
  }
  /// <summary>Clear all registered EmbeddingBackend implementations</summary>
  public static void ClearEmbeddingBackends() {
    EmbeddingBackendRegistry.Clear();
  }
  /// <summary>Clear all registered Renderer implementations</summary>
  public static void ClearRenderers() { RendererRegistry.Clear(); }
  /// <summary>Clear all registered RerankerBackend implementations</summary>
  public static void ClearRerankerBackends() {
    RerankerBackendRegistry.Clear();
  }
  /// <summary>Clear all registered TokenizerBackend implementations</summary>
  public static void ClearTokenizerBackends() {
    TokenizerBackendRegistry.Clear();
  }
  private static Exception GetLastError() {
    return XbergException.FromLastError("Unknown error");
  }
}
