// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:979e708cbef8b048367c0a76523273115c602ac2e14d627eb0b1a77f1c55adf1
// To regenerate: alef generate
// To verify freshness: alef verify
const std = @import("std");
const testing = std.testing;
const xberg = @import("xberg");

extern "c" fn setenv(name: [*:0]const u8, value: [*:0]const u8, overwrite: c_int) c_int;
fn allow_private_network() void {
    _ = setenv("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true", 1);
    _ = setenv("RUST_MIN_STACK", "16777216", 1);
}

// E2e tests for category: ocr_backend_management

test "ocr_backend_capabilities_list" {
    // List all registered OCR backends with their declared language capabilities
    allow_private_network();
    const _result_json = try xberg.list_ocr_backend_capabilities();
    defer std.heap.c_allocator.free(_result_json);
    std.debug.print("{s}\n", .{_result_json});
}

test "ocr_backend_supports_language_unknown_backend" {
    // Checking language support on an unregistered OCR backend is an error
    allow_private_network();
    if (xberg.ocr_backend_supports_language("nonexistent-backend-xyz", "eng")) |_| {
        return error.TestUnexpectedResult;
    } else |_| {}
}

test "ocr_backends_clear" {
    // Clear all OCR backends and verify list is empty
    allow_private_network();
    _ = try xberg.clear_ocr_backends();
}

test "ocr_backends_list" {
    // List all registered OCR backends
    allow_private_network();
    _ = try xberg.list_ocr_backends();
}

test "ocr_backends_unregister" {
    // Unregister nonexistent OCR backend gracefully
    allow_private_network();
    _ = try xberg.unregister_ocr_backend("nonexistent-backend-xyz");
}
