// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7f8fe7baa6eb3372b92bc1ae23958abb1d6894018cfdb075874a2ac27ebe06e2
// To regenerate: alef generate
// To verify freshness: alef verify

import { describe, expect, it } from "vitest";
import { extract, registerEmbeddingBackend, registerOcrBackend, registerPostProcessor, registerRerankerBackend, registerTokenizerBackend, registerValidator, unregisterEmbeddingBackend, unregisterPostProcessor, unregisterRerankerBackend, unregisterTokenizerBackend, unregisterValidator, unregisterOcrBackend } from "@xberg-io/xberg";

process.env.CRAWLBERG_ALLOW_PRIVATE_NETWORK ??= "true";


async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let buffer = await response.arrayBuffer();

	if (contentEncoding === "gzip") {
		const { gunzipSync } = await import("zlib");
		buffer = gunzipSync(new Uint8Array(buffer)).buffer;
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		buffer = brotliDecompressSync(new Uint8Array(buffer)).buffer;
	}

	const text = new TextDecoder().decode(buffer);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [_alefE2eText(item), _alefE2eText(record.kind), _alefE2eText(record.name), _alefE2eText(record.source), _alefE2eText(record.alias), _alefE2eText(record.text), _alefE2eText(record.signature), itemsText];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
	// Extract the display string based on the variant type
	if (formatType === "image" && typeof record.image === "object") {
		const imageData = record.image as Record<string, unknown>;
		if (typeof imageData.format === "string") return imageData.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}


describe("plugin_api", () => {

	it("register_embedding_backend_trait_bridge: register_embedding_backend: trait bridge", async () => {
		class _TestStub_register_embedding_backend_trait_bridge {
  name(): string { return "test-embedding-backend"; }
  dimensions(): number { return 768; }
  async embed(_p0?: any): Promise<Array<Array<number>>> { return []; }
  async dispose(): Promise<void> { return undefined; }
}

		const _bridge_backend = new _TestStub_register_embedding_backend_trait_bridge();
		await expect(registerEmbeddingBackend(_bridge_backend)).resolves.not.toThrow();

		await unregisterEmbeddingBackend(_bridge_backend.name());
		await _bridge_backend.dispose();
	}, 30000);

	it("register_ocr_backend_trait_bridge: register_ocr_backend: trait bridge", async () => {
		class _TestStub_register_ocr_backend_trait_bridge {
  name(): string { return "test-backend"; }
  async processImage(_p0?: any, _p1?: any): Promise<ExtractedDocument> { return "{}" as unknown as ExtractedDocument; }
  async processImageFile(_p0?: any, _p1?: any): Promise<ExtractedDocument> { return "{}" as unknown as ExtractedDocument; }
  supportsLanguage(_p0?: any): boolean { return false; }
  backendType(): OcrBackendType { return "\"Tesseract\"" as unknown as OcrBackendType; }
  supportedLanguages(): Array<string> { return []; }
  supportsTableDetection(): boolean { return false; }
  supportsDocumentProcessing(): boolean { return false; }
  emitsStructuredMarkdown(): boolean { return false; }
  confidenceSemantics(): ConfidenceSemantics { return "\"Legibility\"" as unknown as ConfidenceSemantics; }
  pageOrientationHandling(): PageOrientationHandling { return "\"SelfCorrecting\"" as unknown as PageOrientationHandling; }
  async processDocument(_p0?: any, _p1?: any): Promise<ExtractedDocument> { return "{}" as unknown as ExtractedDocument; }
  async dispose(): Promise<void> { return undefined; }
}

		const _bridge_backend = new _TestStub_register_ocr_backend_trait_bridge();
		await expect(registerOcrBackend(_bridge_backend)).resolves.not.toThrow();

		await unregisterOcrBackend(_bridge_backend.name());
		await _bridge_backend.dispose();
	}, 30000);

	it("register_post_processor_trait_bridge: register_post_processor: trait bridge", async () => {
		class _TestStub_register_post_processor_trait_bridge {
  name(): string { return "test-processor"; }
  async process(_p0?: any, _p1?: any): Promise<void> { return undefined; }
  processingStage(): ProcessingStage { return "\"Early\"" as unknown as ProcessingStage; }
  shouldProcess(_p0?: any, _p1?: any): boolean { return false; }
  estimatedDurationMs(_p0?: any): number { return 1; }
  priority(): number { return 1; }
  async dispose(): Promise<void> { return undefined; }
}

		const _bridge_processor = new _TestStub_register_post_processor_trait_bridge();
		await expect(registerPostProcessor(_bridge_processor)).resolves.not.toThrow();

		await unregisterPostProcessor(_bridge_processor.name());
		await _bridge_processor.dispose();
	}, 30000);

	it("register_reranker_backend_trait_bridge: register_reranker_backend: trait bridge", async () => {
		class _TestStub_register_reranker_backend_trait_bridge {
  name(): string { return "test-reranker-backend"; }
  async rerank(_p0?: any, _p1?: any): Promise<Array<number>> { return []; }
  async dispose(): Promise<void> { return undefined; }
}

		const _bridge_backend = new _TestStub_register_reranker_backend_trait_bridge();
		await expect(registerRerankerBackend(_bridge_backend)).resolves.not.toThrow();

		await unregisterRerankerBackend(_bridge_backend.name());
		await _bridge_backend.dispose();
	}, 30000);

	it("register_tokenizer_backend_trait_bridge: register_tokenizer_backend: trait bridge", async () => {
		class _TestStub_register_tokenizer_backend_trait_bridge {
  name(): string { return "test-tokenizer-backend"; }
  countTokens(_p0?: any): number { return 3; }
  async dispose(): Promise<void> { return undefined; }
}

		const _bridge_backend = new _TestStub_register_tokenizer_backend_trait_bridge();
		await expect(registerTokenizerBackend(_bridge_backend)).resolves.not.toThrow();

	}, 30000);

	it("register_validator_trait_bridge: register_validator: trait bridge", async () => {
		class _TestStub_register_validator_trait_bridge {
  name(): string { return "test-validator"; }
  async validate(_p0?: any, _p1?: any): Promise<void> { return undefined; }
  shouldValidate(_p0?: any, _p1?: any): boolean { return false; }
  priority(): number { return 1; }
  async dispose(): Promise<void> { return undefined; }
}

		const _bridge_validator = new _TestStub_register_validator_trait_bridge();
		await expect(registerValidator(_bridge_validator)).resolves.not.toThrow();

		await unregisterValidator(_bridge_validator.name());
		await _bridge_validator.dispose();
	}, 30000);

	it("unregister_embedding_backend_after_register: unregister_embedding_backend", async () => {
		expect(() => unregisterEmbeddingBackend("test-embedding-backend")).not.toThrow();

	}, 30000);

	it("unregister_post_processor_after_register: unregister_post_processor", async () => {
		expect(() => unregisterPostProcessor("test-processor")).not.toThrow();

	}, 30000);

	it("unregister_reranker_backend: unregister_reranker_backend", async () => {
		expect(() => unregisterRerankerBackend("test-reranker-backend")).not.toThrow();

	}, 30000);

	it("unregister_tokenizer_backend_after_register: unregister_tokenizer_backend", async () => {
		expect(() => unregisterTokenizerBackend("test-tokenizer-backend")).not.toThrow();

	}, 30000);

	it("unregister_validator_after_register: unregister_validator", async () => {
		expect(() => unregisterValidator("test-validator")).not.toThrow();

	}, 30000);

});
