# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:22b6acfc763b9dc9f867afdf11c1f3755dfe1c03fbbc5969a08f14116a05666e
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: error."""

from pathlib import Path

import pytest
from xberg import ExtractInput, ExtractInputKind, ExtractionConfig, extract


@pytest.mark.asyncio
async def test_error_empty_bytes() -> None:
    """Graceful handling of empty bytes (should not error)."""
    input = ExtractInput(
        bytes=[], config={}, filename="empty.txt", kind=ExtractInputKind("bytes"), mime_type="text/plain"
    )
    config = ExtractionConfig()

    result = await extract(input, config)
    assert result is not None


@pytest.mark.asyncio
async def test_error_empty_mime() -> None:
    """Error when extracting with empty MIME type."""
    with pytest.raises(Exception):
        input = ExtractInput(
            bytes=Path("text/plain.txt").read_bytes(),
            config={},
            filename="plain.txt",
            kind=ExtractInputKind("bytes"),
            mime_type="",
        )
        config = ExtractionConfig()
        await extract(input, config)


@pytest.mark.asyncio
async def test_error_extract_input_conflicting_ocr() -> None:
    """extract force+disable OCR."""
    with pytest.raises(Exception):
        input = ExtractInput(
            bytes=Path("text/fake_text.txt").read_bytes(),
            config={"disable_ocr": True, "force_ocr": True},
            filename="fake_text.txt",
            kind=ExtractInputKind("bytes"),
            mime_type="text/plain",
        )
        config = ExtractionConfig(disable_ocr=True, force_ocr=True)
        await extract(input, config)


@pytest.mark.asyncio
async def test_error_invalid_mime_format() -> None:
    """Error when extracting with invalid MIME type format."""
    with pytest.raises(Exception):
        input = ExtractInput(
            bytes=Path("text/plain.txt").read_bytes(),
            config={},
            filename="plain.txt",
            kind=ExtractInputKind("bytes"),
            mime_type="not-a-mime",
        )
        config = ExtractionConfig()
        await extract(input, config)


@pytest.mark.asyncio
async def test_error_unsupported_mime() -> None:
    """Error when extracting with unsupported MIME type."""
    with pytest.raises(Exception):
        input = ExtractInput(
            bytes=Path("text/plain.txt").read_bytes(),
            config={},
            filename="plain.txt",
            kind=ExtractInputKind("bytes"),
            mime_type="application/x-nonexistent",
        )
        config = ExtractionConfig()
        await extract(input, config)
