# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4415127ddd773677055076e6b596f338ff2be6748f67e51d1ccaacc21f70464f
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: code."""

import json
import os

import pytest
from xberg import ExtractInput, extract


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


@pytest.mark.asyncio
async def test_code_shebang_detection() -> None:
    """Test language detection from shebang line via bytes input."""
    input_mock_base_url = os.environ["MOCK_SERVER_URL"] + "/fixtures/code_shebang_detection"
    input_json = '{"kind":"uri","mime_type":"text/x-source-code","uri":"$mock_url/code/script.sh"}'.replace(
        "$mock_url", input_mock_base_url
    )
    input = ExtractInput(**json.loads(input_json))

    result = await extract(input)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "text/x-source-code".lower()
    assert len(result.results[0].content) >= 10
    assert "build".lower() in str(result.results[0].content).lower()
    assert "clean".lower() in str(result.results[0].content).lower()
