// Generated by alef. Do not edit by hand.
// alef:hash:58b2f884fc8f1fc6d04f1c6f9bc9881918c836d09c096146b1f11aeaecf79fb3
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** How a generated image caption interacts with existing alternate text. */
enum class CaptionAltTextMode {
    /** Keep existing alternate text, using the caption only when it is absent. */
    @com.fasterxml.jackson.annotation.JsonProperty("preserve") PRESERVE,
    /** Join existing alternate text and the generated caption with `: `. */
    @com.fasterxml.jackson.annotation.JsonProperty("combine") COMBINE,
    /** Use the generated caption even when alternate text is present. */
    @com.fasterxml.jackson.annotation.JsonProperty("replace") REPLACE;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            PRESERVE -> "preserve"
            COMBINE -> "combine"
            REPLACE -> "replace"
        }

    override fun toString(): String = toWire()

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): CaptionAltTextMode =
            when (value) {
                "preserve" -> PRESERVE
                "combine" -> COMBINE
                "replace" -> REPLACE
                else -> throw IllegalArgumentException("Unknown CaptionAltTextMode value: $value")
            }
    }
}
