// Generated by alef. Do not edit by hand.
// alef:hash:4c616ca237942efaf27542b911f827aae6ed2fbd62270f82a4704014d5745f98
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Content filter applied to each crawled page before it reaches the result. */
enum class ContentFilterKind {
    /** Keep only pages scoring at or above `bm25_threshold` for `bm25_query`. */
    @com.fasterxml.jackson.annotation.JsonProperty("bm25") BM25;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            BM25 -> "bm25"
        }

    override fun toString(): String = toWire()

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): ContentFilterKind =
            when (value) {
                "bm25" -> BM25
                else -> throw IllegalArgumentException("Unknown ContentFilterKind value: $value")
            }
    }
}
