// Generated by alef. Do not edit by hand.
// alef:hash:5b4af8232a200d03874e1c2479437a254c4b61e929b6e28e2b105d735e553ef0
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Managed credential-provider configuration for OAuth2/STS-based authentication modes liter-llm
 * cannot express via a static `api_key`. See `LlmConfig.credential_provider`.
 *
 * `Debug` is implemented by hand: `CredentialProviderConfig.AzureAd`'s `client_secret` is a
 * credential and must never be printed, matching `LlmConfig`'s own redaction policy. The
 * other variants carry no secret material — `CredentialProviderConfig.VertexOauth2` and
 * `CredentialProviderConfig.BedrockWebIdentity` reference a *file path*, never the key or
 * token itself.
 */
@com.fasterxml.jackson.annotation.JsonTypeInfo(use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME, property = "type", visible = false)
@com.fasterxml.jackson.annotation.JsonSubTypes(
    com.fasterxml.jackson.annotation.JsonSubTypes.Type(value = CredentialProviderConfig.AzureAd::class, name = "azure_ad"),
    com.fasterxml.jackson.annotation.JsonSubTypes.Type(value = CredentialProviderConfig.VertexOauth2::class, name = "vertex_oauth2"),
    com.fasterxml.jackson.annotation.JsonSubTypes.Type(value = CredentialProviderConfig.VertexAdc::class, name = "vertex_adc"),
    com.fasterxml.jackson.annotation.JsonSubTypes.Type(value = CredentialProviderConfig.BedrockWebIdentity::class, name = "bedrock_web_identity")
)
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
sealed class CredentialProviderConfig {
    /** Azure AD OAuth2 client-credentials flow (Azure OpenAI / Azure Cognitive Services). */
    data class AzureAd(
        val tenantId: String,
        val clientId: String,
        val clientSecret: String,
        val scope: String?,
    ) : CredentialProviderConfig()
    /**
     * Google Vertex AI OAuth2 via a service-account JSON key file on disk.
     *
     * Points at a file path rather than embedding the key inline: the key file contains an
     * RSA private key — stronger secret material than an API key — and `LlmConfig` must never
     * carry that directly, matching the credential-handling policy the rest of this module
     * follows.
     */
    data class VertexOauth2(
        val serviceAccountKeyFile: String,
        val scope: String?,
    ) : CredentialProviderConfig()
    /**
     * Google Vertex AI Application Default Credentials, resolved from the GCE/GKE/Cloud Run
     * metadata server. Carries no secret material at all.
     */
    data class VertexAdc(val scope: String?) : CredentialProviderConfig()
    /** AWS STS `AssumeRoleWithWebIdentity` (EKS IRSA / OIDC federation) for Bedrock. */
    data class BedrockWebIdentity(
        val roleArn: String,
        val tokenFile: String,
        val sessionName: String?,
        val region: String?,
    ) : CredentialProviderConfig()
}
