// Generated by alef. Do not edit by hand.
// alef:hash:f3432585f9faf7691cd53e08161f7151f30161aea15ea7fc4bac1af6382bb244
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Options controlling how two `ExtractedDocument` values are compared. */
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
data class DiffOptions(
    /** Include metadata changes in the diff. Default: `true`. */
    val includeMetadata: Boolean = true,
    /** Include embedded-children changes in the diff. Default: `true`. */
    val includeEmbedded: Boolean = true,
    /**
     * Truncate content to this many characters before diffing.
     *
     * Useful for very large documents where only the first N characters matter.
     * `null` means no truncation.
     */
    val maxContentChars: Long? = null,
)
