// Generated by alef. Do not edit by hand.
// alef:hash:3559514c8d4646171fe14caa96f197a1ed2dbf930dca2cd70d20262a0acb29a2
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * One finding reported by an external content-inspection engine.
 *
 * Unknown fields are ignored, so an engine's raw output can be passed as is.
 * Presidio, AWS Comprehend, Azure Language, and GCP DLP payload fields are
 * accepted as aliases. GCP's ordered likelihood buckets are normalized to
 * evenly spaced scores from `0.0` through `1.0`; `LIKELIHOOD_UNSPECIFIED`
 * maps to `0.5`, matching GCP's documented `POSSIBLE` default.
 */
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
data class ExternalRedactionFinding(
    /** Engine category, surfaced as `PiiCategory.Custom(label)`. */
    val label: String = "",
    /**
     * Literal value to redact. When absent, it is read from `content` at
     * `start..end` under the requested `RedactionOffsetEncoding`.
     */
    val text: String? = null,
    /** Start offset (inclusive) into `content`. */
    val start: Int? = null,
    /** End offset (exclusive) into `content`. */
    val end: Int? = null,
    /** Engine confidence in `[0.0, 1.0]`; filtered by `RedactionConfig.min_score` when set. */
    val score: Float? = null,
)
