// Generated by alef. Do not edit by hand.
// alef:hash:0ffe642c9080ea06c96003e5afd265ee23a416e716f4f2551324a4497be9c08a
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Combined confidence on `[0, 1]`.
 *
 * When OCR did not run, the `ocr_aggregate` weight folds into `text_coverage`
 * so the weighted sum still totals 1.0.
 */
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
data class ExtractionConfidence(
    /** Fraction of pages with a usable text layer. */
    val textCoverage: Float,
    /**
     * OCR recognition confidence, word-count-weighted across every recognized word, when OCR
     * ran; `null` when it did not.
     */
    val ocrAggregate: Float? = null,
    /** Whether the merged output validates against the preset schema. */
    val schemaCompliance: SchemaCompliance,
    /** Weighted blend in `[0, 1]`. The value compared against the fallback threshold. */
    val combined: Float,
)
