// Generated by alef. Do not edit by hand.
// alef:hash:6c224d8cd8b244c1538e80830546e069a011ef1f7f650dea7b5c95622747a991
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Source kind for `ExtractInput`. */
enum class ExtractInputKind {
    /** Raw in-memory bytes. */
    @com.fasterxml.jackson.annotation.JsonProperty("bytes") BYTES,
    /** A filesystem path, `file://` URI, or HTTP(S) URL. */
    @com.fasterxml.jackson.annotation.JsonProperty("uri") URI;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            BYTES -> "bytes"
            URI -> "uri"
        }

    override fun toString(): String = toWire()

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): ExtractInputKind =
            when (value) {
                "bytes" -> BYTES
                "uri" -> URI
                else -> throw IllegalArgumentException("Unknown ExtractInputKind value: $value")
            }
    }
}
