// Generated by alef. Do not edit by hand.
// alef:hash:c0f9c1afbdc08be2329ac0d87b366f6d442a43b26d3de9012a11f702962db425
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Hierarchy extraction configuration for PDF text structure analysis.
 *
 * Enables extraction of document hierarchy levels (H1-H6) based on font size
 * clustering and semantic analysis. When enabled, hierarchical blocks are
 * included in page content.
 */
data class HierarchyConfig(
    /** Enable hierarchy extraction */
    val enabled: Boolean = true,
    /**
     * Number of font size clusters to use for hierarchy levels (1-7)
     *
     * Default: 3, which provides two heading levels plus body text.
     * Larger values create more fine-grained hierarchy levels.
     */
    @get:com.fasterxml.jackson.annotation.JsonProperty("k_clusters")
    @param:com.fasterxml.jackson.annotation.JsonProperty("k_clusters")
    val kClusters: Long = 3L,
    /** Include bounding box information in hierarchy blocks */
    val includeBbox: Boolean = true,
)
