// Generated by alef. Do not edit by hand.
// alef:hash:8acd045a9134580fb3bd289c22c3fe7c393f60edb089058424793960ff62cd4f
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * A registered OCR backend's declared name and language capabilities.
 *
 * Returned by `list_ocr_backend_capabilities`. See that function's documentation for the
 * determinism guarantees and the important caveat about what an empty `supported_languages`
 * means.
 */
data class OcrBackendCapabilities(
    /** The backend's registered name, as returned by `list_ocr_backends`. */
    val name: String,
    /**
     * The languages this backend declares support for, via
     * `OcrBackend.supported_languages`.
     *
     * An empty list means the backend does not enumerate its languages — it is *not* a
     * statement that the backend supports no languages. `OcrBackend.supported_languages`
     * is a defaulted trait method that returns `[]`, and not every backend overrides it:
     * the VLM backend (`llm.vlm_ocr.VlmOcrBackend`) accepts every language via
     * `supports_language` while inheriting the empty default here. Use
     * `ocr_backend_supports_language` to decide whether one specific language is usable —
     * never infer "unsupported" from an empty list.
     *
     * The order of this list is preserved exactly as the backend reported it and is *not*
     * re-sorted. Tesseract's order comes from enumerating installed tessdata files; PaddleOCR's
     * comes from its own `SUPPORTED_LANGUAGES` constant. Re-sorting would disagree with the
     * precedence each backend's own `supports_language` implementation uses internally.
     */
    val supportedLanguages: List<String> = emptyList(),
)
