// Generated by alef. Do not edit by hand.
// alef:hash:2e775424f635fec156c6649fad3770fb8663fab7da3eaad0183465cb1192bf33
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Bounding geometry for an OCR element.
 *
 * Supports both axis-aligned rectangles (from Tesseract) and 4-point quadrilaterals
 * (from PaddleOCR and rotated text detection).
 */
@com.fasterxml.jackson.annotation.JsonTypeInfo(use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME, property = "type", visible = false)
@com.fasterxml.jackson.annotation.JsonSubTypes(
    com.fasterxml.jackson.annotation.JsonSubTypes.Type(value = OcrBoundingGeometry.Rectangle::class, name = "rectangle"),
    com.fasterxml.jackson.annotation.JsonSubTypes.Type(value = OcrBoundingGeometry.Quadrilateral::class, name = "quadrilateral")
)
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
sealed class OcrBoundingGeometry {
    /** Axis-aligned bounding box (typical for Tesseract output). */
    data class Rectangle(
        val left: Int,
        val top: Int,
        val width: Int,
        val height: Int,
    ) : OcrBoundingGeometry()
    /**
     * 4-point quadrilateral for rotated/skewed text (PaddleOCR).
     *
     * Points are in clockwise order starting from top-left:
     * `[top_left, top_right, bottom_right, bottom_left]`
     */
    data class Quadrilateral(val points: List<OcrPoint>) : OcrBoundingGeometry()
}
