// Generated by alef. Do not edit by hand.
// alef:hash:8e6e7c22d504465e51c7c648dfa10262c7fb845d106b0ad42971d8feba06baf6
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** OCR configuration. */
data class OcrConfig(
    /**
     * Whether OCR is enabled.
     *
     * Setting `enabled: false` is a shorthand for `disable_ocr: true` on the parent
     * `ExtractionConfig`. Images return
     * metadata only; PDFs use native text extraction without OCR fallback.
     *
     * Defaults to `true`. When `false`, all other OCR settings are ignored.
     */
    val enabled: Boolean = true,
    /**
     * OCR backend: tesseract, paddleocr, paddle-ocr, sceptre, or vlm.
     * Sceptre uses ONNX Runtime on desktop/server and tract on supported mobile builds.
     * Browser WebAssembly uses the separate byte-fed Sceptre worker API.
     */
    val backend: String = "tesseract",
    /**
     * Language code(s) for OCR recognition. Defaults to `["eng"]`. For Tesseract,
     * languages are joined with "+".
     *
     * A list is the canonical form and the only form accepted by the binding
     * object APIs (Python, Node, PHP, WASM, etc.): `["eng", "deu"]`. When
     * deserializing from a config file, JSON body, or the REST/MCP API, a
     * single string is also accepted, either as one code ("eng") or
     * "+"-joined ("eng+deu").
     */
    val language: List<String> = listOf("eng"),
    /** Tesseract-specific configuration (optional) */
    val tesseractConfig: TesseractConfig? = null,
    /** Output format for OCR results (optional, for format conversion) */
    val outputFormat: OutputFormat? = null,
    /**
     * PaddleOCR-specific configuration (optional, JSON passthrough).
     *
     * Deserialized into a `PaddleOcrConfig`, so any of its fields can be
     * overridden here — most notably `model_version` (`"pp-ocrv6"` default / `"pp-ocrv5"`) and
     * `model_tier`. In TOML:
     *
     * ```toml
     * [ocr.paddle_ocr_config]
     * model_version = "pp-ocrv5"
     * model_tier = "server"
     * ```
     *
     * The `XBERG_OCR_MODEL_VERSION` / `XBERG_OCR_MODEL_TIER` environment variables set the same two
     * keys for env-configured servers (issue #1279).
     */
    val paddleOcrConfig: Any? = null,
    /**
     * Arbitrary per-call options passed through to the backend unchanged.
     *
     * Custom OCR backends and built-in backends that support runtime tuning
     * can read this value and deserialize the keys they care about. Keys
     * unknown to the backend are silently ignored.
     *
     * This is the recommended extension point for per-call parameters that
     * are not covered by the typed fields above (e.g. mode switching,
     * preprocessing flags, inference batch size).
     *
     * **Scope:** when `pipeline` is `null`, this value is propagated to the
     * primary stage of the auto-constructed pipeline. When `pipeline` is
     * explicitly set, this field has **no effect** — the caller must set
     * `OcrPipelineStage.backend_options` directly on the relevant stage(s)
     * instead.
     *
     * Example:
     * ```json
     * { "mode": "fast", "enable_layout": true, "timeout_ms": 5000 }
     * ```
     */
    val backendOptions: Any? = null,
    /** OCR element extraction configuration */
    val elementConfig: OcrElementConfig? = null,
    /**
     * Quality thresholds for the native-text-to-OCR fallback decision.
     * When None, uses compiled defaults (matching previous hardcoded behavior).
     */
    val qualityThresholds: OcrQualityThresholds? = null,
    /**
     * Multi-backend OCR pipeline configuration. When set, enables weighted
     * fallback across multiple OCR backends based on output quality.
     * When None, uses the single `backend` field (same as today).
     */
    val pipeline: OcrPipelineConfig? = null,
    /**
     * Enable automatic page rotation based on orientation detection.
     *
     * When enabled, page orientation (0/90/180/270 degrees) is detected with an
     * ONNX PP-LCNet document-orientation classifier — NOT Tesseract's own
     * `DetectOrientationScript()`/OSD, which this library does not call. If the
     * page is rotated with high confidence, the image is corrected before
     * recognition. Applies to every OCR backend; the tesseract-only
     * `TesseractConfig.preprocessing` field of the same name is OR'd in on
     * top of this one and affects tesseract alone.
     *
     * Independent of a page's PDF `/Rotate` entry, which is handled separately
     * on every OCR route regardless of this setting.
     */
    val autoRotate: Boolean = false,
    /**
     * Ergonomic VLM fallback policy.
     *
     * When set to anything other than `VlmFallbackPolicy.Disabled` and
     * `OcrConfig.pipeline` is `null`, a multi-stage pipeline is synthesised
     * automatically:
     *
     * - `VlmFallbackPolicy.OnLowQuality` → `[classical_stage, vlm_stage]` with the
     *   `quality_threshold` mapped onto `OcrQualityThresholds.pipeline_min_quality`.
     *
     * - `VlmFallbackPolicy.Always` → `[vlm_stage]` only.
     *
     * Requires `OcrConfig.vlm_config` to be `Some` when not `Disabled`.
     * When `OcrConfig.pipeline` is explicitly set, this field is ignored.
     */
    @field:com.fasterxml.jackson.databind.annotation.JsonSerialize(`as` = VlmFallbackPolicy::class)
    val vlmFallback: VlmFallbackPolicy = VlmFallbackPolicy.Disabled,
    /**
     * VLM (Vision Language Model) OCR configuration.
     *
     * Required when `backend` is `"vlm"` or when `vlm_fallback` is not
     * `VlmFallbackPolicy.Disabled`. Uses liter-llm to send page images to a
     * vision model for text extraction.
     */
    val vlmConfig: LlmConfig? = null,
    /**
     * Custom Jinja2 prompt template for VLM OCR.
     *
     * When `null`, uses the default template. Available variables:
     *
     * - `{{ language }}` — The document language code (e.g., "eng", "deu").
     */
    val vlmPrompt: String? = null,
    /**
     * Hardware acceleration for ONNX Runtime models (e.g. PaddleOCR, layout detection).
     *
     * Not user-configurable via config files — injected at runtime from
     * `ExtractionConfig.acceleration` before each `process_image` call.
     */
    val acceleration: AccelerationConfig? = null,
    /**
     * Security limits applied when decoding raw image bytes for OCR (GH#1554).
     *
     * Not user-configurable via config files — injected at runtime from
     * `ExtractionConfig.security_limits` before each `process_image` call, the same
     * pattern `Self.acceleration` uses. `ExtractionConfig.security_limits` is the
     * single source of truth: this field only ever holds a copy the caller placed here
     * immediately before dispatch, so the two cannot drift. A backend consulting a
     * `backend_options` override for this call may still let that override win, but in
     * the absence of one this field is what backends should fall back to instead of
     * `SecurityLimits.default()`. `null` means "use `SecurityLimits.default()`", never
     * "disable the check".
     */
    val securityLimits: SecurityLimits? = null,
    /**
     * Caller-supplied Tesseract `traineddata` bytes per language code.
     *
     * Primary use case is the WASM build, which has no filesystem and cannot
     * download tessdata at runtime. Native builds typically rely on
     * `TessdataManager` and ignore this field. When present, the WASM
     * Tesseract backend prefers these bytes over its compile-time-bundled
     * English data.
     *
     * Skipped by serde to keep config files small — supply via the typed API
     * at runtime.
     */
    val tessdataBytes: Map<String, ByteArray>? = null,
    /**
     * Runtime override for tessdata directory path.
     *
     * When set, uses this path as the highest-priority tessdata location,
     * bypassing environment variables and cache directories. Useful for
     * embedding pre-installed tessdata in applications. When `null`, uses
     * the standard resolution chain: TESSDATA_PREFIX env, cache dir, system paths.
     */
    val tessdataPath: String? = null,
)
