// Generated by alef. Do not edit by hand.
// alef:hash:902bc7a8d9f302316afc108236f3b58fd6a80ce7439376cc0e22cf172e6fc218
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Aggregate OCR legibility score for a page, reported by the backend that produced its text.
 *
 * This is distinct from `OcrConfidence`, which scores a single detected element (a word or
 * line) using detection/recognition confidence from the OCR engine itself. `PageOcrConfidence`
 * is a page-level summary computed after noise filtering, intended for triage of which pages
 * are worth a closer look, not for comparing OCR engines against each other.
 */
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
data class PageOcrConfidence(
    /**
     * Aggregate legibility score in `0.0..=1.0`, or `null` when the backend that
     * produced this page does not report a calibrated legibility scale.
     *
     * Backends differ in what their confidence numbers mean (see `OcrConfidence`'s
     * per-backend normalization), and not every backend maps onto a 0.0-1.0 legibility
     * scale at all. When a backend has no such calibrated scale, this is `null` rather
     * than a misleading number, and scores must never be compared across backends.
     */
    val score: Double? = null,
    /**
     * Number of words the score was averaged over, AFTER noise filtering.
     *
     * A small `word_count` means the average is based on little evidence, so a high
     * `score` next to a small `word_count` is not representative of the whole page.
     */
    val wordCount: Int = 0,
    /** Name of the OCR backend that produced the page text. */
    val backend: String = "",
)
