// Generated by alef. Do not edit by hand.
// alef:hash:e427a1895b9d5fc66329e690de3d428e685a4889ba899efa3da69d2d6ee10048
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
* PDF extraction backend selection.
*
* Controls which engine parses and renders PDF documents. Wire format is
* snake_case in all serializers (JSON, TOML, YAML). Defaults to
* `PdfBackend.Native` -- selecting anything else never changes behavior
* for a caller who does not opt in.
*/
enum class PdfBackend {
    /** xberg's own pure-Rust PDF engine (default), `crates/xberg-native-pdf`. */
    @com.fasterxml.jackson.annotation.JsonProperty("native") NATIVE,
    /**
     * pdfium -- Google's PDFium engine, gated behind the `pdf-pdfium` Cargo
     * feature (#700 added the selection level; #702 added the extraction
     * engine, `extractors.pdf.pdfium_engine`, deliberately smaller in scope
     * than `Native` -- see that module's doc comment for exactly what it
     * extracts). A build without the `pdf-pdfium` feature rejects this at the
     * CLI validation layer rather than silently falling back to `Native`.
     * A build *with* the feature still enforces the selection at extraction
     * time (`extractors.pdf.PdfExtractor.extract_core`), because that is
     * the one dispatch point every caller -- CLI, library use, API/MCP
     * servers, language bindings -- passes through; see that function's doc
     * comment for why the enforcement lives there and not only in CLI
     * validation.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("pdfium") PDFIUM;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            NATIVE -> "native"
            PDFIUM -> "pdfium"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): PdfBackend =
            when (value) {
                "native" -> NATIVE
                "pdfium" -> PDFIUM
                else -> throw IllegalArgumentException("Unknown PdfBackend value: $value")
            }
    }
}
