// Generated by alef. Do not edit by hand.
// alef:hash:59619a25941b7c2219da2ab92bddf10d93bc6279c9a4b28b09987dd5e0dab437
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * PDF-specific metadata.
 *
 * Contains metadata fields specific to PDF documents that are not in the common
 * `Metadata` structure. Common fields like title, authors, keywords, and dates
 * are at the `Metadata` level.
 */
data class PdfMetadata(
    /** PDF version (e.g., "1.7", "2.0") */
    val pdfVersion: String? = null,
    /** PDF producer (application that created the PDF) */
    val producer: String? = null,
    /** Whether the PDF is encrypted/password-protected */
    val isEncrypted: Boolean? = null,
    /** First page width in points (1/72 inch) */
    val width: Long? = null,
    /** First page height in points (1/72 inch) */
    val height: Long? = null,
    /** Total number of pages in the PDF document */
    val pageCount: Int? = null,
    /**
     * How strongly the document's most scan-like page resembles a scan, in `[0.0, 1.0]`.
     *
     * `null` when the document could not be inspected. A full-page raster with no
     * visible text scores at least `0.85`; a born-digital slide with a full-bleed
     * background image scores `0.50`.
     */
    val scannedConfidence: Float? = null,
    /**
     * Pages that look like scans (1-indexed), using the default confidence threshold.
     *
     * `null` when the document could not be inspected; empty when no page qualifies.
     */
    val scannedPages: List<Int>? = null,
    /**
     * Pages whose text was dominated by fabricated character mappings (1-indexed):
     * `MappingProvenance.Fallback`, a font whose glyph-to-Unicode mapping resolved to
     * a value the extractor chose rather than read from the file (issue #1254). This is
     * a fact about how the text was derived, independent of `scanned_pages`'s raster-based
     * scan detection, and independent of whether the resulting text happens to look
     * structurally like prose (issue #1667: a broken mapping that lands on ordinary
     * letters and punctuation passes every character-shape check but is still fabricated).
     *
     * `null` when `OcrQualityThresholds.enable_provenance_ocr_routing` is `false`; empty
     * when no page qualifies.
     */
    val fabricatedTextPages: List<Int>? = null,
    /**
     * Pages whose native text layer reads as no real detectable language (1-indexed): a
     * `/ToUnicode` CMap (or other mapping tier) that resolves every glyph to *a* character,
     * consistently the WRONG one (e.g. a ROT-shifted mapping), so the page is structurally
     * indistinguishable from real prose to `fabricated_text_pages`'s provenance check and to
     * every character-shape heuristic (issue #1696; issue #1667's `quality_score: 1.0` with
     * no warning on such a page is the same underlying gap). This is a content-plausibility
     * fact, independent of `fabricated_text_pages` and of `scanned_pages`.
     *
     * `null` when `OcrQualityThresholds.enable_plausibility_ocr_routing` is `false`; empty
     * when no page qualifies.
     */
    val implausibleTextPages: List<Int>? = null,
    /**
     * Pages the `auto` layout strategy skipped (1-indexed).
     *
     * `null` unless layout detection ran with `LayoutStrategy.Auto`; empty
     * when the gate selected every page.
     */
    val layoutGatedPages: List<Int>? = null,
    /**
     * Why the `auto` layout gate selected or skipped each page.
     *
     * Index `i` is page `i + 1`. Snake_case values such as `multi_column`,
     * `table_grid`, or `plain_text` (the skip reason). `null` unless layout
     * detection ran with `LayoutStrategy.Auto`.
     */
    val layoutGateReasons: List<String>? = null,
)
