// Generated by alef. Do not edit by hand.
// alef:hash:5f1de66fc32ba12de037aa1df85ebf596ad3d1e3989d1f7534115032dab30114
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * One user-supplied regex pattern to redact.
 *
 * The pattern is compiled with the Rust `regex` crate (no look-around). Case
 * sensitivity is encoded in the pattern via the `(?i)` inline flag when
 * `Self.case_sensitive` is `false`.
 */
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
data class RedactionPattern(
    /** Custom category label surfaced in `RedactionFinding.category`. */
    val label: String,
    /** Regex pattern (Rust `regex` crate dialect — no look-around). */
    val pattern: String,
    /** When `true`, match case-sensitively; otherwise prepend `(?i)` to the regex. */
    val caseSensitive: Boolean = false,
)
