// Generated by alef. Do not edit by hand.
// alef:hash:3b78258d3df95d2021196c007d0d2518932f81539bd85dda57bd4c9729edfda5
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Extracted table structure.
 *
 * Represents a table detected and extracted from a document (PDF, image, etc.).
 * Tables are converted to both structured cell data and Markdown format.
 */
data class Table(
    /** Table cells as a 2D vector (rows × columns) */
    val cells: List<List<String>> = emptyList(),
    /** Markdown representation of the table */
    val markdown: String = "",
    /** Page number where the table was found (1-indexed) */
    val pageNumber: Int = 0,
    /**
     * Bounding box of the table's position. Only populated when position data is
     * available from the producing extractor.
     *
     * The coordinate space depends on how the table was produced, and callers must
     * know which route produced a given `Table` before interpreting this field:
     *
     * - Tables extracted from a PDF's native content, and tables recognized on a
     *   scanned PDF page that went through xberg's OCR pipeline (`--force-ocr` /
     *   `--ocr-scanned-pages`), are in **PDF points with a bottom-left origin**
     *   (x0=left, y0=bottom, x1=right, y1=top; y increases upward). For the OCR
     *   case, the pipeline rescales the backend's raw pixel output into this space
     *   before it reaches `Table.bounding_box` — see
     *   `rescale_ocr_bboxes_to_page_points` in `extractors.pdf.ocr`.
     *
     * - Tables detected by OCR on a standalone image with no backing PDF page (for
     *   example extracting a bare PNG/JPEG/TIFF) are in **raster pixel coordinates
     *   with a top-left origin** (x0=left, y0=top, x1=right, y1=bottom; y increases
     *   downward) — the same convention the OCR backend (Tesseract, PaddleOCR,
     *   candle-based backends) or the layout detector reported them in. There is no
     *   PDF page geometry to rescale into for this case, so the raw pixel box is
     *   passed through unchanged.
     */
    val boundingBox: BoundingBox? = null,
    /**
     * Stable identifier shared by every `tables[]` entry that represents a
     * fragment of the same physical table.
     *
     * Assigned deterministically by the extraction pipeline (e.g. a
     * sequential `"table-N"` in document order); never derived from
     * randomness or wall-clock time, so the same input document always
     * produces the same ids. Consumers can use it to reconcile the markdown
     * blocks in `content` / `pages[].content` / `chunks[].content` with the
     * structured entries in `tables[]`. `null` when the extractor did not
     * assign one.
     *
     * Today, same-page fragments of one physical table are already merged
     * into a single `tables[]` entry before ids are assigned (see PDF table
     * stitching), so in practice `table_id` is unique per entry rather than
     * shared across several. A table split across a page boundary is
     * intentionally *not* linked — its per-page pieces get separate ids.
     * Sharing one id across page-boundary fragments is a known possible
     * future extension, not implemented yet.
     */
    val tableId: String? = null,
    /**
     * Paragraph styles carried by individual cells, for the cells that have one.
     *
     * Sparse and flat on purpose. A DOCX banner row -- row 0, one cell spanning the grid,
     * styled `Heading1`..`Heading6` -- is what Word's navigation pane and a `TOC` field treat
     * as the document outline, but as a table cell it reached consumers as anonymous text
     * (GH#1587). `cells` keeps the bare text: prefixing it with `#` would put a markdown
     * heading inside a table cell, which is invalid where it lands and would change text every
     * existing consumer already reads. This list is the signal instead.
     *
     * Entries are only emitted for cells that actually carry a style, so an ordinary table
     * serialises exactly as it did before. Indices are into `cells`.
     */
    val cellStyles: List<TableCellStyle> = emptyList(),
    /**
     * Header cells for this fragment, i.e. the first row of `cells`.
     *
     * Populated even when this fragment's own header row was merged away or
     * physically lives in a sibling fragment (see `table_id`), so a single
     * fragment is interpretable in isolation. `null` when no header row
     * could be determined.
     */
    val columns: List<String>? = null,
)
