// Generated by alef. Do not edit by hand.
// alef:hash:8e1cc1de47d258c73574249d5d2e789fcf200ce7d637cfaf9826c7d450d9065b
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Plain text and Markdown extraction result.
 *
 * Contains the extracted text along with statistics and,
 * for Markdown files, structural elements like headers and links.
 */
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
data class TextExtractionResult(
    /** Extracted text content */
    val content: String,
    /** Number of lines */
    val lineCount: Long,
    /** Number of words */
    val wordCount: Long,
    /** Number of characters */
    val characterCount: Long,
    /** Markdown headers (text only, Markdown files only) */
    val headers: List<String>? = null,
    /** Markdown links (Markdown files only). */
    val links: List<MarkdownLink>? = null,
    /** Code blocks (Markdown files only). */
    val codeBlocks: List<MarkdownCodeBlock>? = null,
)
