// Generated by alef. Do not edit by hand.
// alef:hash:31f3312f87b4b37d4ccc7d4cbf3a56d036cfe6374369d73b31f47359e4c9744e
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Main error type for all Xberg operations.
 *
 * All errors in Xberg use this enum, which preserves error chains
 * and provides context for debugging.
 *
 * # Variants
 *
 * - `Io` - File system and I/O errors (always bubble up)
 * - `Parsing` - Document parsing errors (corrupt files, unsupported features)
 * - `Ocr` - OCR processing errors
 * - `Validation` - Input validation errors (invalid paths, config, parameters)
 * - `Cache` - Cache operation errors (non-fatal, can be ignored)
 * - `ImageProcessing` - Image manipulation errors
 * - `Serialization` - JSON/MessagePack serialization errors
 * - `MissingDependency` - Missing optional dependencies (tesseract, etc.)
 * - `Plugin` - Plugin-specific errors
 * - `LockPoisoned` - Mutex/RwLock poisoning (should not happen in normal operation)
 * - `UnsupportedFormat` - Unsupported MIME type or file format
 * - `Other` - Catch-all for uncommon errors
 *
 * # FFI error codes — a stable public contract
 *
 * Each variant carries `#[cfg_attr(alef, alef(error_code = N))]`. Without it alef has no stable
 * numeric taxonomy to bind to, so `alef_ffi_error_code()` collapses every variant to a single
 * unknown code and EVERY language binding loses the ability to tell error kinds apart --
 * `errors.Is(err, ErrOcr)` in Go, the `checkLastError` switch in Java, and Zig's typed error sets
 * all degrade to one catch-all. Refusing to guess is correct on alef's part; supplying the codes
 * is our job.
 *
 * The blocks are `XbergError` 1000-1017, `HeuristicsError` 1100-1101, `LoadError` 1200-1205,
 * `ResolveError` 1300, chosen to leave room to grow and to stay clear of alef's own reserved
 * 0-4 (`null`/`Conversion`/`Unknown`/`Panic`/`InvalidHandle`).
 *
 * These numbers cross the FFI boundary and are compiled into released bindings, so they are
 * append-only: **never renumber or reuse a code**, and give a new variant the next free number in
 * its block rather than inserting one in declaration order.
 */
sealed class XbergError(message: String) : Exception(message) {
    data class Io(val field0: String) : XbergError("IO error: $field0")
    data class Parsing(
        override val message: String,
        val source: String?,
    ) : XbergError("Parsing error: {message}")
    data class Ocr(
        override val message: String,
        val source: String?,
    ) : XbergError("OCR error: {message}")
    data class Validation(
        override val message: String,
        val source: String?,
    ) : XbergError("Validation error: {message}")
    data class Cache(
        override val message: String,
        val source: String?,
    ) : XbergError("Cache error: {message}")
    data class ImageProcessing(
        override val message: String,
        val source: String?,
    ) : XbergError("Image processing error: {message}")
    data class Serialization(
        override val message: String,
        val source: String?,
    ) : XbergError("Serialization error: {message}")
    data class MissingDependency(val field0: String) : XbergError("Missing dependency: $field0")
    data class Plugin(
        override val message: String,
        val pluginName: String,
    ) : XbergError("Plugin error in '{plugin_name}': {message}")
    data class LockPoisoned(val field0: String) : XbergError("Lock poisoned: $field0")
    data class UnsupportedFormat(val field0: String) : XbergError("Unsupported format: $field0")
    data class Embedding(
        override val message: String,
        val source: String?,
    ) : XbergError("Embedding error: {message}")
    data class Reranking(
        override val message: String,
        val source: String?,
    ) : XbergError("Reranking error: {message}")
    data class Transcription(
        override val message: String,
        val source: String?,
    ) : XbergError("Transcription error: {message}")
    data class Timeout(
        val elapsedMs: Long,
        val limitMs: Long,
    ) : XbergError("Extraction timed out after {elapsed_ms}ms (limit: {limit_ms}ms)")
    object Cancelled : XbergError("Extraction cancelled")
    data class Security(
        override val message: String,
        val source: String?,
    ) : XbergError("Security violation: {message}")
    data class Other(val field0: String) : XbergError("$field0")
}
