// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7f219ffe739d688e1f704f9a3217b8abd67d8a10815d14b5e21020dbcfed20cc
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Browser backend used for JavaScript rendering.
 */
@SuppressWarnings("PMD")
public enum BrowserBackend {
    /**
     * Existing Chromium/CDP backend powered by chromiumoxide.
     */
    CHROMIUMOXIDE("chromiumoxide"),
    /**
     * Crawlberg-owned native browser backend derived from Obscura.
     */
    NATIVE("native");


    /** The string value. */
    private final String value;

    BrowserBackend(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static BrowserBackend fromValue(final String value) {
        for (BrowserBackend e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown BrowserBackend value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
