// DO NOT EDIT - auto-generated by alef
// alef:hash:1f729da1d88a6c19c89fd230779bd48c2c54fa36abaf82aefdac89d018373c34
package io.xberg;

/**
 * The extraction stopped after a cooperative cancellation request.
 *
 * Rust callers can request cancellation through
 * `CancellationToken`. The REST async-jobs API uses the
 * same mechanism. Generated language bindings do not currently expose
 * in-process cancellation.
 */
public class CancelledException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CancelledException with the given message. */
  public CancelledException(final String message) { super(message); }

  /** Creates a new CancelledException with the given message and cause. */
  public CancelledException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
