// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bc319b7d8d10885e42554e97d2ecd2d086b6ebc8a8ab75e631f0536365ef6cbd
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Content layer classification for document nodes.
 *
 * Replaces separate body/furniture arrays with per-node granularity.
 */
@SuppressWarnings("PMD")
public enum ContentLayer {
  /**
   * Main document body content.
   */
  BODY("body"),
  /**
   * Page/section header (running header).
   */
  HEADER("header"),
  /**
   * Page/section footer (running footer).
   */
  FOOTER("footer"),
  /**
   * Footnote content.
   */
  FOOTNOTE("footnote");

  /** The string value. */
  private final String value;

  ContentLayer(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static ContentLayer fromValue(final String value) {
    for (ContentLayer e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown ContentLayer value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
