// DO NOT EDIT - auto-generated by alef
// alef:hash:7a16a2f905c8a0d6e0fad128d310a30b6a24f0602d0dd9d9b12abfebf99af286
package io.xberg;

/**
 * The file validates but cannot be deserialized into [`Preset`].
 */
public class DeserializeException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DeserializeException with the given message. */
  public DeserializeException(final String message) { super(message); }

  /** Creates a new DeserializeException with the given message and cause. */
  public DeserializeException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
