// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:327dc4a2c89d78cc25bdd2cc788e67239c72e8c8921d782910ab4022d9aaa518
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * FictionBook (FB2) metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FictionBookMetadata.Builder.class)
public record
FictionBookMetadata(@JsonProperty("genres") List<String> genres,
                    @JsonProperty("sequences") List<String> sequences,
                    @Nullable @JsonProperty("annotation") String annotation) {
  /** Creates a new Builder for constructing instances of this record. */
  public static Builder builder() { return new Builder(); }
  public FictionBookMetadata {
    if (genres == null) {
      genres = List.of();
    }
    if (sequences == null) {
      sequences = List.of();
    }
  }

  // CPD-OFF
  /** Jackson builder for FictionBookMetadata deserialization. */
  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    @Nullable private List<String> genres = List.of();
    @Nullable private List<String> sequences = List.of();
    @Nullable private String annotation;

    /** Sets the genres field. */
    @JsonProperty("genres")
    public Builder withGenres(final @Nullable List<String> value) {
      this.genres = value;
      return this;
    }

    /** Sets the sequences field. */
    @JsonProperty("sequences")
    public Builder withSequences(final @Nullable List<String> value) {
      this.sequences = value;
      return this;
    }

    /** Sets the annotation field. */
    @JsonProperty("annotation")
    public Builder withAnnotation(final @Nullable String value) {
      this.annotation = value;
      return this;
    }

    /**
     * Constructs a FictionBookMetadata instance from the builder's current
     * state.
     */
    public FictionBookMetadata build() {
      return new FictionBookMetadata(genres, sequences, annotation);
    }
  }
  // CPD-ON
}
