// DO NOT EDIT - auto-generated by alef
// alef:hash:8c57a8f3da26ed1da95734e07f49c45e2c4b39c28b2610b82335de42f385398c
package io.xberg;

/**
 * Errors that can occur during heuristics analysis.
 */
public class HeuristicsErrorException extends XbergRsException {
  private static final long serialVersionUID = 1L;
  /** Creates a new HeuristicsErrorException with the given message. */
  public HeuristicsErrorException(final String message) { super(message); }

  /**
   * Creates a new HeuristicsErrorException with the given message and cause.
   */
  public HeuristicsErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
