// DO NOT EDIT - auto-generated by alef
// alef:hash:4fe2e03f98702c18102071cc4d800c1b927c1660bfda70c63cc9c5c4bf32c4d3
package io.xberg;

/**
 * Errors that can occur during heuristics analysis.
 */
public class HeuristicsErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new HeuristicsErrorException with the given message. */
  public HeuristicsErrorException(final String message) { super(message); }

  /**
   * Creates a new HeuristicsErrorException with the given message and cause.
   */
  public HeuristicsErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
