// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3d90b582e48f588920b4d447409bdc2c296b1bd6a2130a9fba92e326cbc367d7
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Image type classification.
 */
@SuppressWarnings("PMD")
public enum ImageType {
  /**
   * Data URI image
   */
  DATA_URI("data-uri"),
  /**
   * Inline SVG
   */
  INLINE_SVG("inline-svg"),
  /**
   * External image URL
   */
  EXTERNAL("external"),
  /**
   * Relative path image
   */
  RELATIVE("relative");

  /** The string value. */
  private final String value;

  ImageType(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static ImageType fromValue(final String value) {
    for (ImageType e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown ImageType value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
