// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:93217594124c2a5ec85341438da25b9f783df0ef524284bed07a1f4bec953aa7
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Heuristic classification of what an image likely depicts.
 */
@SuppressWarnings("PMD")
public enum ImageKind {
  /**
   * Photographic image (natural scene, photograph)
   */
  PHOTOGRAPH("photograph"),
  /**
   * Technical or schematic diagram
   */
  DIAGRAM("diagram"),
  /**
   * Chart, graph, or plot
   */
  CHART("chart"),
  /**
   * Freehand or technical drawing
   */
  DRAWING("drawing"),
  /**
   * Text-heavy image (scanned text, document)
   */
  TEXT_BLOCK("text_block"),
  /**
   * Decorative element or border
   */
  DECORATION("decoration"),
  /**
   * Logo or brand mark
   */
  LOGO("logo"),
  /**
   * Small icon
   */
  ICON("icon"),
  /**
   * Fragment of a larger tiled image (tile of a technical drawing)
   */
  TILE_FRAGMENT("tile_fragment"),
  /**
   * Mask or transparency map
   */
  MASK("mask"),
  /**
   * Full-page render produced during OCR preprocessing; used as a citation
   * thumbnail.
   */
  PAGE_RASTER("page_raster"),
  /**
   * Could not classify with reasonable confidence
   */
  UNKNOWN("unknown");

  /** The string value. */
  private final String value;

  ImageKind(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static ImageKind fromValue(final String value) {
    for (ImageKind e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown ImageKind value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
