// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:84c500b28f39e4202096fdd8fda0a6a2871d027e121e1f7f5404a7e6021b2b22
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Types of inline elements in Djot.
 */
@SuppressWarnings("PMD")
public enum InlineType {
  /**
   * Plain text run.
   */
  TEXT("text"),
  /**
   * Bold / strong emphasis.
   */
  STRONG("strong"),
  /**
   * Italic / regular emphasis.
   */
  EMPHASIS("emphasis"),
  /**
   * Highlighted text (marker pen).
   */
  HIGHLIGHT("highlight"),
  /**
   * Subscript text.
   */
  SUBSCRIPT("subscript"),
  /**
   * Superscript text.
   */
  SUPERSCRIPT("superscript"),
  /**
   * Inserted text (tracked change).
   */
  INSERT("insert"),
  /**
   * Deleted text (tracked change).
   */
  DELETE("delete"),
  /**
   * Inline code span.
   */
  CODE("code"),
  /**
   * Hyperlink with URL.
   */
  LINK("link"),
  /**
   * Inline image reference.
   */
  IMAGE("image"),
  /**
   * Generic inline span with optional attributes.
   */
  SPAN("span"),
  /**
   * Inline mathematical expression.
   */
  MATH("math"),
  /**
   * Raw inline content in a specified format.
   */
  RAW_INLINE("raw_inline"),
  /**
   * Footnote reference marker.
   */
  FOOTNOTE_REF("footnote_ref"),
  /**
   * Named symbol or emoji shortcode.
   */
  SYMBOL("symbol");

  /** The string value. */
  private final String value;

  InlineType(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static InlineType fromValue(final String value) {
    for (InlineType e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown InlineType value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
