// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b15be2cc4698526e2e84ca69199d3cbc9d921454bd7cf752ca878cf30258a01e
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;

/**
 * Bridge interface for the Validator plugin system.
 *
 * Implementations are wrapped by ValidatorBridge and exposed to the native
 * runtime through Panama FFM upcall stubs.
 */
public interface IValidator {

  /** Plugin name (used for registry keying). */
  String name();

  /** Plugin version. */
  String version();

  /** Initialize the plugin. */
  default void initialize() throws Exception {}

  /** Shut down the plugin. */
  default void shutdown() throws Exception {}

  /** validate. */ void validate(ExtractedDocument result,
                                 ExtractionConfig config) throws Exception;

  /** should_validate. */ boolean should_validate(ExtractedDocument _result,
                                                  ExtractionConfig _config)
      throws Exception;

  /** priority. */ int priority() throws Exception;
}
