// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2f7eb925de576807822f40021ec7ff864165640417c52c77751fcfb5542e1e61
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Link type classification.
 */
@SuppressWarnings("PMD")
public enum LinkType {
    /**
     * Anchor link (#section)
     */
    ANCHOR("anchor"),
    /**
     * Internal link (same domain)
     */
    INTERNAL("internal"),
    /**
     * External link (different domain)
     */
    EXTERNAL("external"),
    /**
     * Email link (mailto:)
     */
    EMAIL("email"),
    /**
     * Phone link (tel:)
     */
    PHONE("phone"),
    /**
     * Other link type
     */
    OTHER("other");


    /** The string value. */
    private final String value;

    LinkType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static LinkType fromValue(final String value) {
        for (LinkType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown LinkType value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
