// DO NOT EDIT - auto-generated by alef
// alef:hash:969594fe95f77611c159a87f46310a6764f1dc60379d52d0ccb72ad7bc655509
package io.xberg;

/**
 * Errors produced while loading or validating a preset file.
 */
public class LoadErrorException extends XbergRsException {
  private static final long serialVersionUID = 1L;
  /** Creates a new LoadErrorException with the given message. */
  public LoadErrorException(final String message) { super(message); }

  /** Creates a new LoadErrorException with the given message and cause. */
  public LoadErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
