// DO NOT EDIT - auto-generated by alef
// alef:hash:40d2022a9f0a4afb0a55adf264928407f034d9d246794a7916b006d2a7314370
package io.xberg;

/**
 * An internal `Mutex` or `RwLock` was found in a poisoned state.
 */
public class LockPoisonedException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new LockPoisonedException with the given message. */
  public LockPoisonedException(final String message) { super(message); }

  /** Creates a new LockPoisonedException with the given message and cause. */
  public LockPoisonedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
