// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:31298125b0c893508f558c9cb4c26b7a1ef56efac71a4f2148903ace3eb1e806
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import java.util.List;

/**
 * The result of a map operation, containing discovered URLs.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MapResult.Builder.class)
public record MapResult(@JsonProperty("urls") List<SitemapUrl> urls) {
  /** Creates a new Builder for constructing instances of this record. */
  public static Builder builder() { return new Builder(); }

  // CPD-OFF
  /** Jackson builder for MapResult deserialization. */
  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    private List<SitemapUrl> urls = List.of();

    /** Sets the urls field. */
    @JsonProperty("urls")
    public Builder withUrls(final List<SitemapUrl> value) {
      this.urls = value;
      return this;
    }

    /** Constructs a MapResult instance from the builder's current state. */
    public MapResult build() { return new MapResult(urls); }
  }
  // CPD-ON
}
