// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a7954694ab89cc918af448b118be62c160e62a4ede4a31778f9fa72cf74d9ea7
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * A link extracted from Markdown.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MarkdownLink.Builder.class)
public record MarkdownLink(@JsonProperty("text") String text,
                           @JsonProperty("url") String url) {
  /** Creates a new Builder for constructing instances of this record. */
  public static Builder builder() { return new Builder(); }

  // CPD-OFF
  /** Jackson builder for MarkdownLink deserialization. */
  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    private String text;
    private String url;

    /** Sets the text field. */
    @JsonProperty("text")
    public Builder withText(final String value) {
      this.text = value;
      return this;
    }

    /** Sets the url field. */
    @JsonProperty("url")
    public Builder withUrl(final String value) {
      this.url = value;
      return this;
    }

    /** Constructs a MarkdownLink instance from the builder's current state. */
    public MarkdownLink build() { return new MarkdownLink(text, url); }
  }
  // CPD-ON
}
