// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:724a480386dbf6a7075bc834bc2275409156b59742c1971eb2062a6c2adf49e0
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * How partial results from multiple model calls (e.g. per page batch) are combined.
 *
 * Canonical home for the merge strategy referenced by presets and by the
 * structured pipeline's post-processing. There is intentionally only one merge
 * type across the crate — do not introduce a second.
 */
@SuppressWarnings("PMD")
public enum MergeMode {
    /**
     * Deep-merge JSON objects field by field (later calls fill missing fields).
     */
    OBJECT_MERGE("object_merge"),
    /**
     * Concatenate top-level arrays across calls.
     */
    ARRAY_CONCAT("array_concat"),
    /**
     * Keep the first non-empty result; ignore subsequent calls.
     */
    OBJECT_FIRST("object_first");


    /** The string value. */
    private final String value;

    MergeMode(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static MergeMode fromValue(final String value) {
        for (MergeMode e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown MergeMode value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
