// DO NOT EDIT - auto-generated by alef
// alef:hash:9a6fe39b1a2576384fc08b4a993202e97f404dfb3fe1ca66b9c58909d66bb871
package io.xberg;

/**
 * A required optional system dependency (e.g. `tesseract`) was not found.
 */
public class MissingDependencyException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new MissingDependencyException with the given message. */
  public MissingDependencyException(final String message) { super(message); }

  /**
   * Creates a new MissingDependencyException with the given message and cause.
   */
  public MissingDependencyException(final String message,
                                    final Throwable cause) {
    super(message, cause);
  }
}
