// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:76bb1598ffee772c1723f10a4bef904ef6e0f4865c2f48117789228fb0ed878a
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import java.util.List;

/**
 * A registered OCR backend's declared name and language capabilities.
 *
 * Returned by list_ocr_backend_capabilities. See that function's documentation
 * for the determinism guarantees and the important caveat about what an empty
 * {@code supported_languages} means.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OcrBackendCapabilities.Builder.class)
public record OcrBackendCapabilities(@JsonProperty("name") String name,
                                     @JsonProperty("supported_languages")
                                     List<String> supportedLanguages) {
  /** Creates a new Builder for constructing instances of this record. */
  public static Builder builder() { return new Builder(); }

  // CPD-OFF
  /** Jackson builder for OcrBackendCapabilities deserialization. */
  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    private String name;
    @JsonProperty("supported_languages")
    private List<String> supportedLanguages = List.of();

    /** Sets the name field. */
    @JsonProperty("name")
    public Builder withName(final String value) {
      this.name = value;
      return this;
    }

    /** Sets the supportedLanguages field. */
    @JsonProperty("supported_languages")
    public Builder withSupportedLanguages(final List<String> value) {
      this.supportedLanguages = value;
      return this;
    }

    /**
     * Constructs a OcrBackendCapabilities instance from the builder's current
     * state.
     */
    public OcrBackendCapabilities build() {
      return new OcrBackendCapabilities(name, supportedLanguages);
    }
  }
  // CPD-ON
}
