// DO NOT EDIT - auto-generated by alef
// alef:hash:ebbd8e086ff9076d34007564eea7e701a1cffd765166dd82f4a90a6238652a43
package io.xberg;

/**
 * A catch-all for uncommon errors that do not fit another variant.
 */
public class OtherException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new OtherException with the given message. */
  public OtherException(final String message) { super(message); }

  /** Creates a new OtherException with the given message and cause. */
  public OtherException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
