// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:754ca70609a5289a8f70590742e9cd00df47b928442ec48f45055b300c21110a
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Output format for extraction results.
 *
 * Controls the format of the {@code content} field in {@code
 * ExtractedDocument}. When set to {@code Markdown}, {@code Djot}, or {@code
 * Html}, the output uses that format.
 * {@code Plain} returns the raw extracted text.
 */
@SuppressWarnings("PMD")
public enum OutputFormat {
  /**
   * Plain text content only (default)
   */
  PLAIN("plain"),
  /**
   * Markdown format
   */
  MARKDOWN("markdown"),
  /**
   * Djot markup format
   */
  DJOT("djot"),
  /**
   * HTML format
   */
  HTML("html"),
  /**
   * JSON tree format with heading-driven sections.
   */
  JSON("json"),
  /**
   * Docling DocTags format (tables rendered as OTSL).
   */
  DOC_TAGS("doctags"),
  /**
   * Custom renderer registered via the RendererRegistry.
   * The string is the renderer name (e.g., "docx", "latex").
   */
  CUSTOM("custom");

  /** The string value. */
  private final String value;

  OutputFormat(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static OutputFormat fromValue(final String value) {
    for (OutputFormat e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown OutputFormat value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
