// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c46478b0e071d49fb84264c1654ed6e7a97d140c407480f24c8429a387c1f815
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Configuration for PaddleOCR backend.
 *
 * Configures PaddleOCR text detection and recognition with multi-language
 * support. Uses a builder pattern for convenient configuration.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PaddleOcrConfig.Builder.class)
public record PaddleOcrConfig(
    @JsonProperty("language") String language,
    @JsonProperty("cache_dir") java.nio.file.@Nullable Path cacheDir,
    @JsonProperty("use_angle_cls") boolean useAngleCls,
    @JsonProperty("enable_table_detection") boolean enableTableDetection,
    @Nullable @JsonProperty("det_db_thresh") Float detDbThresh,
    @Nullable @JsonProperty("det_db_box_thresh") Float detDbBoxThresh,
    @Nullable @JsonProperty("det_db_unclip_ratio") Float detDbUnclipRatio,
    @Nullable @JsonProperty("det_limit_side_len") Integer detLimitSideLen,
    @Nullable @JsonProperty("rec_batch_num") Integer recBatchNum,
    @Nullable @JsonProperty("padding") Integer padding,
    @Nullable @JsonProperty("drop_score") Float dropScore,
    @JsonProperty("model_tier") String modelTier,
    @JsonProperty("model_version") String modelVersion,
    @Nullable @JsonProperty("inference_backend")
    PaddleInferenceBackend inferenceBackend) {
  /** Creates a new Builder for constructing instances of this record. */
  public static Builder builder() { return new Builder(); }
  public PaddleOcrConfig {
    if (detDbThresh == null) {
      detDbThresh = 0.3f;
    }
    if (detDbBoxThresh == null) {
      detDbBoxThresh = 0.5f;
    }
    if (detDbUnclipRatio == null) {
      detDbUnclipRatio = 1.6f;
    }
    if (detLimitSideLen == null) {
      detLimitSideLen = 1024;
    }
    if (recBatchNum == null) {
      recBatchNum = 6;
    }
    if (padding == null) {
      padding = 10;
    }
    if (dropScore == null) {
      dropScore = 0.5f;
    }
  }

  // CPD-OFF
  /** Jackson builder for PaddleOcrConfig deserialization. */
  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    private String language = "en";
    @JsonProperty("cache_dir") private java.nio.file.@Nullable Path cacheDir;
    @JsonProperty("use_angle_cls") private boolean useAngleCls;
    @JsonProperty("enable_table_detection")
    private boolean enableTableDetection;
    @JsonProperty("det_db_thresh") private Float detDbThresh;
    @JsonProperty("det_db_box_thresh") private Float detDbBoxThresh;
    @JsonProperty("det_db_unclip_ratio") private Float detDbUnclipRatio;
    @JsonProperty("det_limit_side_len") private Integer detLimitSideLen;
    @JsonProperty("rec_batch_num") private Integer recBatchNum;
    private Integer padding;
    @JsonProperty("drop_score") private Float dropScore;
    @JsonProperty("model_tier") private String modelTier = "mobile";
    @JsonProperty("model_version") private String modelVersion = "pp-ocrv6";
    @JsonProperty("inference_backend")
    @Nullable
    private PaddleInferenceBackend inferenceBackend;

    /** Sets the language field. */
    @JsonProperty("language")
    public Builder withLanguage(final String value) {
      this.language = value;
      return this;
    }

    /** Sets the cacheDir field. */
    @JsonProperty("cache_dir")
    public Builder withCacheDir(final java.nio.file.@Nullable Path value) {
      this.cacheDir = value;
      return this;
    }

    /** Sets the useAngleCls field. */
    @JsonProperty("use_angle_cls")
    public Builder withUseAngleCls(final boolean value) {
      this.useAngleCls = value;
      return this;
    }

    /** Sets the enableTableDetection field. */
    @JsonProperty("enable_table_detection")
    public Builder withEnableTableDetection(final boolean value) {
      this.enableTableDetection = value;
      return this;
    }

    /** Sets the detDbThresh field. */
    @JsonProperty("det_db_thresh")
    public Builder withDetDbThresh(final @Nullable Float value) {
      this.detDbThresh = value;
      return this;
    }

    /** Sets the detDbBoxThresh field. */
    @JsonProperty("det_db_box_thresh")
    public Builder withDetDbBoxThresh(final @Nullable Float value) {
      this.detDbBoxThresh = value;
      return this;
    }

    /** Sets the detDbUnclipRatio field. */
    @JsonProperty("det_db_unclip_ratio")
    public Builder withDetDbUnclipRatio(final @Nullable Float value) {
      this.detDbUnclipRatio = value;
      return this;
    }

    /** Sets the detLimitSideLen field. */
    @JsonProperty("det_limit_side_len")
    public Builder withDetLimitSideLen(final @Nullable Integer value) {
      this.detLimitSideLen = value;
      return this;
    }

    /** Sets the recBatchNum field. */
    @JsonProperty("rec_batch_num")
    public Builder withRecBatchNum(final @Nullable Integer value) {
      this.recBatchNum = value;
      return this;
    }

    /** Sets the padding field. */
    @JsonProperty("padding")
    public Builder withPadding(final @Nullable Integer value) {
      this.padding = value;
      return this;
    }

    /** Sets the dropScore field. */
    @JsonProperty("drop_score")
    public Builder withDropScore(final @Nullable Float value) {
      this.dropScore = value;
      return this;
    }

    /** Sets the modelTier field. */
    @JsonProperty("model_tier")
    public Builder withModelTier(final String value) {
      this.modelTier = value;
      return this;
    }

    /** Sets the modelVersion field. */
    @JsonProperty("model_version")
    public Builder withModelVersion(final String value) {
      this.modelVersion = value;
      return this;
    }

    /** Sets the inferenceBackend field. */
    @JsonProperty("inference_backend")
    public Builder
    withInferenceBackend(final @Nullable PaddleInferenceBackend value) {
      this.inferenceBackend = value;
      return this;
    }

    /**
     * Constructs a PaddleOcrConfig instance from the builder's current state.
     */
    public PaddleOcrConfig build() {
      return new PaddleOcrConfig(
          language, cacheDir, useAngleCls, enableTableDetection, detDbThresh,
          detDbBoxThresh, detDbUnclipRatio, detLimitSideLen, recBatchNum,
          padding, dropScore, modelTier, modelVersion, inferenceBackend);
    }
  }
  // CPD-ON
}
