// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:08dc49a5b297b25d0b204b75c479f2b1b5354897b1a2ef461e2c77a3c5f4a46d
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Supported languages in PaddleOCR.
 *
 * Maps user-friendly language codes to paddle-ocr-rs language identifiers.
 */
@SuppressWarnings("PMD")
public enum PaddleLanguage {
    /**
     * English
     */
    ENGLISH("English"),
    /**
     * Simplified Chinese
     */
    CHINESE("Chinese"),
    /**
     * Japanese
     */
    JAPANESE("Japanese"),
    /**
     * Korean
     */
    KOREAN("Korean"),
    /**
     * German
     */
    GERMAN("German"),
    /**
     * French
     */
    FRENCH("French"),
    /**
     * Latin script (covers most European languages)
     */
    LATIN("Latin"),
    /**
     * Cyrillic (Russian and related)
     */
    CYRILLIC("Cyrillic"),
    /**
     * Traditional Chinese
     */
    TRADITIONAL_CHINESE("TraditionalChinese"),
    /**
     * Thai
     */
    THAI("Thai"),
    /**
     * Greek
     */
    GREEK("Greek"),
    /**
     * East Slavic (Russian, Ukrainian, Belarusian)
     */
    EAST_SLAVIC("EastSlavic"),
    /**
     * Arabic (Arabic, Persian, Urdu)
     */
    ARABIC("Arabic"),
    /**
     * Devanagari (Hindi, Marathi, Sanskrit, Nepali)
     */
    DEVANAGARI("Devanagari"),
    /**
     * Tamil
     */
    TAMIL("Tamil"),
    /**
     * Telugu
     */
    TELUGU("Telugu");


    /** The string value. */
    private final String value;

    PaddleLanguage(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static PaddleLanguage fromValue(final String value) {
        for (PaddleLanguage e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown PaddleLanguage value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
