// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1be90e3c4388d0bc55effed5915086a62265ed7be102c4bffd3a0ce9036296b9
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Type of paginated unit in a document.
 *
 * Distinguishes between different types of "pages" (PDF pages, presentation slides, spreadsheet sheets).
 */
@SuppressWarnings("PMD")
public enum PageUnitType {
    /**
     * Standard document pages (PDF, DOCX, images)
     */
    PAGE("page"),
    /**
     * Presentation slides (PPTX, ODP)
     */
    SLIDE("slide"),
    /**
     * Spreadsheet sheets (XLSX, ODS)
     */
    SHEET("sheet");


    /** The string value. */
    private final String value;

    PageUnitType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static PageUnitType fromValue(final String value) {
        for (PageUnitType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown PageUnitType value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
