// DO NOT EDIT - auto-generated by alef
// alef:hash:0e290bf51ba4980df32f7918e710460c100417bf4d6bd81647d152049f35d1ff
package io.xberg;

/**
 * The file is not valid JSON.
 */
public class ParseException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParseException with the given message. */
  public ParseException(final String message) { super(message); }

  /** Creates a new ParseException with the given message and cause. */
  public ParseException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
