// DO NOT EDIT - auto-generated by alef
// alef:hash:a9b3f8f1da9767e4ffb8603370aed2fa64865f056ecc5683cc33dadbd5ff5f42
package io.xberg;

/**
 * PDF analysis step failed (only when `heuristics-pdf` feature is active).
 */
public class PdfAnalysisErrorException extends HeuristicsErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PdfAnalysisErrorException with the given message. */
  public PdfAnalysisErrorException(final String message) { super(message); }

  /**
   * Creates a new PdfAnalysisErrorException with the given message and cause.
   */
  public PdfAnalysisErrorException(final String message,
                                   final Throwable cause) {
    super(message, cause);
  }
}
