// DO NOT EDIT - auto-generated by alef
// alef:hash:7446cfee875633cef052a9963ba873bb51e3dcfd118b516f660684951b211249
package io.xberg;

/**
 * A registered plugin returned an error during extraction.
 */
public class PluginException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PluginException with the given message. */
  public PluginException(final String message) { super(message); }

  /** Creates a new PluginException with the given message and cause. */
  public PluginException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
