// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e1a3f76a809e16ae7aa6882f5cd85f7f4fc0219ace2fa55e72f07e0693ca398a
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Intensity level for the token-reduction pipeline.
 */
@SuppressWarnings("PMD")
public enum ReductionLevel {
  /**
   * No reduction applied; text is returned as-is.
   */
  OFF("Off"),
  /**
   * Remove only the most common stopwords.
   */
  LIGHT("Light"),
  /**
   * Balanced stopword removal and redundancy filtering.
   */
  MODERATE("Moderate"),
  /**
   * Aggressive filtering; may remove less common content words.
   */
  AGGRESSIVE("Aggressive"),
  /**
   * Maximum compression; prioritizes brevity over completeness.
   */
  MAXIMUM("Maximum");

  /** The string value. */
  private final String value;

  ReductionLevel(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static ReductionLevel fromValue(final String value) {
    for (ReductionLevel e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown ReductionLevel value: " +
                                       value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
