// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:af2e1c7ed598c92104942564bc08eddaf0bb92f89773cdfa0662a24fc24ced71
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;

/**
 * Path A Bridge implementation for IRenderer.
 *
 * Wraps a user-supplied implementation and delegates all method calls.
 * This adapter conforms to the hand-authored sealed interface.
 */
public final class RendererAdapter implements IRenderer {
  private final IRenderer impl;

  public RendererAdapter(IRenderer impl) { this.impl = impl; }

  @Override
  public String name() {
    return impl.name();
  }

  @Override
  public String version() {
    return impl.version();
  }

  @Override
  public void initialize() throws Exception {
    impl.initialize();
  }

  @Override
  public void shutdown() throws Exception {
    impl.shutdown();
  }

  @Override
  public String render_result(ExtractedDocument result) throws Exception {
    return impl.render_result(result);
  }
}
