// DO NOT EDIT - auto-generated by alef
// alef:hash:0e092b8346fa21d65de02d9ac31e291eac152a6dadbf931f17fca175245bdd22
package io.xberg;

/**
 * The reranker model or reranking pipeline returned an error.
 */
public class RerankingException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new RerankingException with the given message. */
  public RerankingException(final String message) { super(message); }

  /** Creates a new RerankingException with the given message and cause. */
  public RerankingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
