// DO NOT EDIT - auto-generated by alef
// alef:hash:8e77dadf0c588c7883e5000dd096affd9c38e1143391ae86eb8a55123898f1ed
package io.xberg;

/**
 * A security policy was violated (e.g. zip bomb, oversized archive).
 */
public class SecurityException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SecurityException with the given message. */
  public SecurityException(final String message) { super(message); }

  /** Creates a new SecurityException with the given message and cause. */
  public SecurityException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
