// DO NOT EDIT - auto-generated by alef
// alef:hash:609d31401ee8812a644052ae483cba3718c163d80a116a24c68f1e953657109c
package io.xberg;

/**
 * JSON or MessagePack serialization/deserialization failed.
 */
public class SerializationException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SerializationException with the given message. */
  public SerializationException(final String message) { super(message); }

  /** Creates a new SerializationException with the given message and cause. */
  public SerializationException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
