// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fc786499513dce912af01d6c8540491a9d564e5288fd3a8b56673faafca589a3
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Summarisation strategy.
 */
@SuppressWarnings("PMD")
public enum SummaryStrategy {
  /**
   * Pure-Rust extractive summary (TextRank over the chunk graph).
   * Deterministic, fast, no external service required.
   */
  EXTRACTIVE("extractive"),
  /**
   * Abstractive summary produced by liter-llm. Requires {@code liter-llm}
   * feature and a configured {@code LlmConfig}. Token usage is captured in
   * ExtractedDocument.llm_usage(super.extraction.ExtractedDocument.llm_usage).
   */
  ABSTRACTIVE("abstractive");

  /** The string value. */
  private final String value;

  SummaryStrategy(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static SummaryStrategy fromValue(final String value) {
    for (SummaryStrategy e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown SummaryStrategy value: " +
                                       value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
