// DO NOT EDIT - auto-generated by alef
// alef:hash:f89cba82515cee63e852088aacbb94e9756f395eeff6f66fcc8a950a00959960
package io.xberg;

/**
 * The extraction operation exceeded the configured time limit.
 */
public class TimeoutException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new TimeoutException with the given message. */
  public TimeoutException(final String message) { super(message); }

  /** Creates a new TimeoutException with the given message and cause. */
  public TimeoutException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
