// DO NOT EDIT - auto-generated by alef
// alef:hash:dd78e4bc1367679108b302032869be6bed2abdb5e1ef2052906d725e4977ae83
package io.xberg;

/**
 * Audio/video transcription failed.
 */
public class TranscriptionException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new TranscriptionException with the given message. */
  public TranscriptionException(final String message) { super(message); }

  /** Creates a new TranscriptionException with the given message and cause. */
  public TranscriptionException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
