// DO NOT EDIT - auto-generated by alef
// alef:hash:b5ef9b6df6c85ad44a962703b15a3369fa11e3b5db99b097cdbd2cdd02e962ef
package io.xberg;

/**
 * The document's MIME type is not supported by any registered extractor.
 */
public class UnsupportedFormatException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new UnsupportedFormatException with the given message. */
  public UnsupportedFormatException(final String message) { super(message); }

  /**
   * Creates a new UnsupportedFormatException with the given message and cause.
   */
  public UnsupportedFormatException(final String message,
                                    final Throwable cause) {
    super(message, cause);
  }
}
