// DO NOT EDIT - auto-generated by alef
// alef:hash:62957bb5eb265397e5f1cf183fffa7aacc04e9600d8378197d6d94f3d896aa7e
package io.xberg;

/**
 * Invalid configuration or input parameters were supplied.
 */
public class ValidationException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ValidationException with the given message. */
  public ValidationException(final String message) { super(message); }

  /** Creates a new ValidationException with the given message and cause. */
  public ValidationException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
