# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:49ce69ad0d044e0b83320a5dd3eefaebf328bcf29ddcdcfa681b1f5cdcb2febb
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module Xberg
  ## The version string for this package.
  VERSION = "1.2.7"
end
