# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c7a2e4c0b7a9168d08ef7f09b8b967926ae2bdff61094ac93d54a86a9813924d
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module Xberg
  ## The version string for this package.
  VERSION = "1.3.2"
end
