<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:292eadc2c3de83a6e4e8a3d5754164eec13895f33cf87e103e1fdf5f32e23217
// To regenerate: alef generate
// To verify freshness: alef verify
declare(strict_types=1);

namespace Xberg;

/**
 * Plugin interface for RerankerBackend.
 *
 * Implement this interface and register an instance with the corresponding
 * registration function to provide custom behavior for extraction.
 */
interface RerankerBackend
{
    /**
     * Score a list of documents against a query.
     *
     *
     * @param string $query
     * @param mixed $documents
     * @return mixed Return value from the plugin method
     */
    public function rerank(string $query, mixed $documents): mixed;
}
