<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:914bddcf806879e7c0b2e40c987812df558b840af0c11e6782bc3ffb6a85de01
// To regenerate: alef generate
// To verify freshness: alef verify
declare(strict_types=1);

namespace Xberg;

/**
 * Plugin interface for Validator.
 *
 * Implement this interface and register an instance with the corresponding
 * registration function to provide custom behavior for extraction.
 */
interface Validator
{
    // Optional methods the bridge calls when the class defines them (the
    // trait's Rust default behavior applies otherwise): should_validate, priority.
    // The lifecycle hooks initialize()/shutdown() are likewise optional.
    /**
     * Validate an extraction result.
     *
     *
     * @param ExtractedDocument $result
     * @param ExtractionConfig $config
     * @return mixed Return value from the plugin method
     */
    public function validate(ExtractedDocument $result, ExtractionConfig $config): mixed;
}
