// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c9786d2e5b9f5dd4cbb77e3ccc072d9d13afcb2f3f6e7fadc9631f84494ff38b
// To regenerate: alef generate
// To verify freshness: alef verify
// ignore_for_file: unused_local_variable, unused_element

import 'package:test/test.dart';
import 'package:xberg/xberg.dart';
import 'package:xberg/src/xberg_bridge_generated/frb_generated.dart' show RustLib;
import 'dart:ffi';
import 'package:ffi/ffi.dart';

// E2e tests for category: registry

void _setEnv(String key, String value) {
  final libc = DynamicLibrary.process();
  final setenv = libc.lookupFunction<
      Int32 Function(Pointer<Utf8>, Pointer<Utf8>, Int32),
      int Function(Pointer<Utf8>, Pointer<Utf8>, int)>('setenv');
  final keyPtr = key.toNativeUtf8();
  final valuePtr = value.toNativeUtf8();
  try {
    final result = setenv(keyPtr, valuePtr, 1);
    if (result != 0) {
      throw StateError('setenv failed for ${key}=${value} with return code $result');
    }
  } finally {
    calloc.free(keyPtr);
    calloc.free(valuePtr);
  }
}

void main() {
  var _rustLibInitialized = false;

  setUpAll(() async {
    _setEnv('CRAWLBERG_ALLOW_PRIVATE_NETWORK', 'true');
    _setEnv('RUST_MIN_STACK', '16777216');
    await RustLib.init();
    _rustLibInitialized = true;
  });

  tearDownAll(() async {
    if (_rustLibInitialized) {
      RustLib.dispose();
    }
  });

  test('List embedding backends', () async {
    final result = await XbergBridge.listEmbeddingBackends();
    expect(result, isNotNull);
  });

  test('List OCR backends', () async {
    final result = await XbergBridge.listOcrBackends();
    expect(result, isNotNull);
  });

  test('List post-processors', () async {
    final result = await XbergBridge.listPostProcessors();
    expect(result, isNotNull);
  });

  test('List renderers', () async {
    final result = await XbergBridge.listRenderers();
    expect(result, isNotNull);
  });

  test('List validators', () async {
    final result = await XbergBridge.listValidators();
    expect(result, isNotNull);
  });

}
