// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:76a6326517e780548b14f64faf2e362d49bac4ae0c831f52aa587d69b0fe1510
// To regenerate: alef generate
// To verify freshness: alef verify

// E2e tests for category: ocr_backend_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg/packages/go"
)

func Test_OcrBackendCapabilitiesList(t *testing.T) {
	// List all registered OCR backends with their declared language capabilities
	_, err := xberg.ListOcrBackendCapabilities()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OcrBackendSupportsLanguageUnknownBackend(t *testing.T) {
	// Checking language support on an unregistered OCR backend is an error
	_, err := xberg.OcrBackendSupportsLanguage(`nonexistent-backend-xyz`, `eng`)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_OcrBackendsClear(t *testing.T) {
	// Clear all OCR backends and verify list is empty
	err := xberg.ClearOcrBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OcrBackendsList(t *testing.T) {
	// List all registered OCR backends
	_, err := xberg.ListOcrBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OcrBackendsUnregister(t *testing.T) {
	// Unregister nonexistent OCR backend gracefully
	err := xberg.UnregisterOcrBackend(`nonexistent-backend-xyz`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
